mongodb/mongoid

- lib/rails/generators/mongoid/config/templates/mongoid.yml
Adding in all of the Moped/session configuration options...was having a hard time tracking these down.
> Updating mongoid.yml template

- CHANGELOG.md
- lib/mongoid/persistable/creatable.rb
- lib/mongoid/persistable/updatable.rb
- spec/app/models/contextable_item.rb
- spec/mongoid/persistable/savable_spec.rb
Based on #3812 .
Added context verification in prepare_insert and prepare_update methods
> 3812 validation context failed

- lib/mongoid/attributes/processing.rb
- spec/mongoid/relations/eager/belongs_to_spec.rb
@arthurnn this is the cause of my problems I emailed out at https://groups.google.com/forum/#!topic/mongoid/Wby7De2Ug0Q.
> Fix regression I caused in 9e5a279f306db9905f7cf331c6915a4ff24518f9

- lib/mongoid/changeable.rb
- spec/mongoid/changeable_spec.rb
fix https://github.com/mongoid/mongoid/issues/4069
> #changed returns an array of changed field names

- spec/app/models/answer.rb
- spec/mongoid/persistable/incrementable_spec.rb
Thanks to this comparison by @gurix
https://github.com/mongodb/mongoid/compare/master...gurix:deep_increment
> MONGOID-3611 Show that the incrementing values in deep embedded documents issue is resolved

- lib/mongoid/timestamps/created.rb
- lib/mongoid/timestamps/timeless.rb
- lib/mongoid/timestamps/updated.rb
- spec/mongoid/timestamps/timeless_spec.rb
Thanks to @kcdragon for this fix.
> MONGOID-3826 MONGOID-4109 Fix timeless leaks

- lib/mongoid/clients.rb
Test:
```
puts(Benchmark.measure do
1000.times do
coll = MyModel.collection
end
end)
```
Before:
```
0.040000   0.000000   0.040000 (  0.044849)
```
After:
```
0.040000   0.000000   0.040000 (  0.036465)
```
> RUBY-1046. Minor performance optimization for getting a collection in Mongoid

- lib/mongoid/scopable.rb
- lib/mongoid/threaded.rb
- spec/app/models/article.rb
- spec/app/models/author.rb
- spec/app/models/kaleidoscope.rb
- spec/mongoid/scopable_spec.rb
scopes are now stored by class rather than thread.
> MONGOID 4159 fix chain scoping

- spec/mongoid/relations/referenced/many_to_many_spec.rb
> MONGOID-3246 Added spec such that 3246 is no longer a bug

- lib/mongoid/criteria.rb
- lib/mongoid/criteria/includable.rb
- lib/mongoid/relations/eager.rb
- lib/mongoid/relations/eager/base.rb
- spec/app/models/alert.rb
- spec/app/models/post.rb
- spec/mongoid/criteria_spec.rb
> MONGOID-4173 nested eager loading

- lib/mongoid/matchable/and.rb
- lib/mongoid/matchable/or.rb
- spec/mongoid/matchable/and_spec.rb
- spec/mongoid/matchable/or_spec.rb
> The $and and $or Matcher should recurse on Document#matches? in order to handle $not properly.

- lib/mongoid/atomic.rb
- lib/mongoid/relations/touchable.rb
- spec/mongoid/relations/touchable_spec.rb
https://jira.mongodb.org/browse/MONGOID-4241
> MONGOID-4241 Fix touch to only update timestamp and optional passed field

- lib/mongoid/relations/touchable.rb
- spec/mongoid/relations/metadata_spec.rb
https://jira.mongodb.org/browse/MONGOID-4304
> Accept extra field for association `touch` option

- docs/tutorials/mongoid-installation.txt
Fixed typos as reported by Luke Prochazca
> DOCS-8837: Mongoid config typos

- docs/tutorials/mongoid-documents.txt
Just some spacing fix (needed an extra space in code blocks)
> docs: spacing fix

- docs/tutorials/mongoid-documents.txt
Clarify language, fix some typos.
> Docs: Clean up Documents

- lib/mongoid/clients/options.rb
- spec/mongoid/clients/options_spec.rb
> Add backwards compatibility for #with block change in Mongoid 5.2.

- lib/mongoid/persistable.rb
- spec/mongoid/persistable_spec.rb
See https://jira.mongodb.org/browse/MONGOID-4487
> Mongoid-4487: Fix atomically to support empty updates

- .travis.yml
(respond with OK status before allowed_failures complete)
> Enable fast_finish for travis

- lib/mongoid/factory.rb
- spec/mongoid/factory_spec.rb
Solved the problem with https://jira.mongodb.org/browse/MONGOID-4497
> [MONGOID-4497] _type could be a hash or a string

- lib/mongoid/contextual/memory.rb
Allows inc to be used with embedded docs.
> Add support for .inc to contextual

- .rubocop.yml
- .versions.conf
- mongoid.gemspec
Allow rails master in gemspec
Bump dev ruby version
> Allow test rails master

- docs/tutorials/mongoid-persistence.txt
I hope that it's right place for this.
Sorry for the end of document, I don't know why it was changed.
> fix Model#update_attributes and add Model#update_attributes! document description

- README.md
Hi, just using last version for deps status badge; cheers
> Use last version for Dependency Status badge

- .travis.yml
- lib/mongoid/atomic/modifiers.rb
- lib/mongoid/contextual/atomic.rb
- lib/mongoid/relations/embedded/batchable.rb
- lib/mongoid/relations/embedded/many.rb
- mongoid.gemspec
- spec/mongoid/atomic/modifiers_spec.rb
- spec/mongoid/atomic_spec.rb
- spec/mongoid/contextual/atomic_spec.rb
- spec/mongoid/persistable/savable_spec.rb
- spec/mongoid/positional_spec.rb
Port fixes from #4465 into 5.4.
References https://jira.mongodb.org/browse/MONGOID-4538.
> Port mongoid 4469 5.4.x

- lib/mongoid/association/referenced/has_many/enumerable.rb
- spec/mongoid/association/referenced/has_many/enumerable_spec.rb
https://jira.mongodb.org/projects/MONGOID/issues/MONGOID-4547?
> Add #one method on has_many associations

- .evergreen/.evg.yml
- lib/mongoid/persistence_context.rb
- spec/mongoid/clients/options_spec.rb
- spec/mongoid/clients/sessions_spec.rb
https://jira.mongodb.org/browse/MONGOID-4564
> Fix read preference passing to ruby driver

- .yardopts
- Gemfile
- Rakefile
> Add a `rake docs` task

- docs/index.txt
- docs/tutorials/mongoid-configuration.txt
- docs/tutorials/mongoid-sessions.txt
- docs/tutorials/mongoid-transactions.txt
- lib/mongoid/persistence_context.rb
- spec/mongoid/clients/factory_spec.rb
- spec/mongoid/clients/options_spec.rb
- spec/mongoid/clients/sessions_spec.rb
- spec/mongoid/clients/transactions_spec.rb
- spec/spec_helper.rb
This PR backports the changes from master necessary for the 7.0.0-stable branch to pass evergreen as well as documentation updates that would be useful to have in the documentation for that branch.
See the evergreen task here: https://evergreen.mongodb.com/version/5b96e8722fbabe13aeaffc96
> 7.0.0 stable

- lib/mongoid/matchable.rb
- lib/mongoid/matchable/nor.rb
- spec/app/models/array_field.rb
- spec/mongoid/matchable/nor_spec.rb
- spec/mongoid/matchable_spec.rb
* Add support for $nor to the Mongoid matcher.
* Fix $nor
* Add frozen string literals
* Fix since and shorten the code
* Expand test coverage
* More test cases
* Fix multi field $nor
> Add support for $nor to the Mongoid matcher. (#4523)

- docs/tutorials/mongoid-installation.txt
- docs/tutorials/mongoid-rails.txt
- docs/tutorials/mongoid-upgrade.txt
Backport from master to fix the docs warnings
> Add Ruby 2.5 & rails to support matrix (#4511)

- docs/tutorials/mongoid-relations.txt
https://jira.mongodb.org/browse/MONGOID-4584
> Replace relation with association in relations doc

- lib/mongoid/document.rb
- spec/mongoid/criteria_spec.rb
- spec/mongoid/document_spec.rb
- spec/spec_helper.rb
- spec/support/constraints.rb
> Fix MONGOID-4595 Test failure against rails master (#4560)

- Gemfile
- lib/mongoid/extensions/string.rb
- spec/mongoid/extensions/string_spec.rb
Reference issue: https://jira.mongodb.org/browse/MONGOID-4742
> Fix MONGOID-4742 String#numeric? can return values other than true & false

- lib/mongoid/association/relatable.rb
- lib/mongoid/copyable.rb
- spec/mongoid/association/embedded/embedded_in_spec.rb
- spec/mongoid/association/embedded/embeds_one_dnl_models.rb
- spec/mongoid/association/embedded/embeds_one_models.rb
- spec/mongoid/association/embedded/embeds_one_spec.rb
- spec/mongoid/association/referenced/has_one_spec.rb
https://jira.mongodb.com/browse/MONGOID-4750
> Fix MONGOID-4750 Association definitions can trigger autoloading and cause NameError's

- .evergreen/functions.sh
Per changes made in https://github.com/mongodb/bson-ruby/pull/123
> Update evergreen functions

- spec/integration/matchable_spec.rb
https://jira.mongodb.com/browse/MONGOID-4781
> MONGOID-4781 Add integration tests for embedded matchers

- docs/tutorials/mongoid-documents.txt
- docs/tutorials/mongoid-queries.txt
https://jira.mongodb.com/browse/MONGOID-4669
> MONGOID-4669 Document regular expressions use in Mongoid

- docs/tutorials/mongoid-installation.txt
- gemfiles/driver_min.gemfile
- gemfiles/driver_min_jruby.gemfile
- lib/mongoid.rb
- mongoid.gemspec
- spec/integration/criteria/time_with_zone_spec.rb
- spec/lite_spec_helper.rb
https://jira.mongodb.com/browse/MONGOID-4658
https://jira.mongodb.com/browse/MONGOID-4770
> MONGOID-4658 MONGOID-4770 test/fix TimeWithZone driver integration, automatically load drivers ActiveSupport compatibility

- spec/mongoid/document_fields_spec.rb
> MONGOID-4823 Add failing tests for BSON::Binary fields not converting values

- .evergreen/config.yml
- .evergreen/functions.sh
- docs/tutorials/mongoid-installation.txt
https://jira.mongodb.org/browse/MONGOID-4828
> MONGOID-4828 Test Mongoid on Ruby 2.7

- docs/tutorials/mongoid-relations.txt
- lib/mongoid/association/referenced/has_many/enumerable.rb
- spec/mongoid/association/referenced/has_many/enumerable_spec.rb
https://jira.mongodb.com/browse/MONGOID-4830
> MONGOID-4830 Remove #one method from has_many associations

- CHANGELOG.md
- docs/tutorials/mongoid-relations.txt
- lib/config/locales/en.yml
I don't think our documentation should make light of alcoholism. Cars are much nicer. :)
> MONGOID-4858 Replace documentation and error resolution example

- lib/mongoid/criteria/queryable/storable.rb
- spec/mongoid/criteria/queryable/storable_spec.rb
https://jira.mongodb.com/browse/MONGOID-4870
> MONGOID-4870 reorder Storable methods to make them easier to read and fix up docstrings to match the code, add test coverage

- lib/mongoid/matchable.rb
- lib/mongoid/matchable/and.rb
- lib/mongoid/matchable/default.rb
- lib/mongoid/matchable/elem_match.rb
- lib/mongoid/matchable/nor.rb
- lib/mongoid/matchable/or.rb
https://jira.mongodb.com/browse/MONGOID-4781
> MONGOID-4781 minor readability and documentation improvements for embedded matchers

- .evergreen/config.yml
- .evergreen/run-tests.sh
- Gemfile
- spec/integration/app_spec.rb
- spec/lite_spec_helper.rb
- spec/support/child_process_helper.rb
- spec/support/spec_config.rb
https://jira.mongodb.org/browse/MONGOID-4661
> MONGOID-4661 Test applications that use Mongoid

- .evergreen/config.yml
- .gitmodules
- spec/integration/app_spec.rb
https://jira.mongodb.com/browse/MONGOID-4802
> MONGOID-4802 Test create_index rake task

- docs/tutorials/mongoid-documents.txt
> MONGOID-4858 Remove remaining reference to alcoholism in documentation 

- lib/mongoid/criteria/queryable/selectable.rb
- spec/mongoid/criteria/queryable/selectable_spec.rb
I just added an alias under the geo_spacial method...
I didn't think this required testing as it's a simple thing... I did replace geo_spacial with geo_spatial in some places just to test that I did the aliasing right...
> MONGOID-4703 added geo-spatial as an alias

- spec/integration/associations/has_many_spec.rb
- spec/integration/associations/has_one_spec.rb
- spec/mongoid/association/referenced/has_many_models.rb
- spec/mongoid/association/referenced/has_one_models.rb
> MONGOID-4890 add more tests for dependent association destruction in transactions

- docs/tutorials/mongoid-relations.txt
- lib/config/locales/en.yml
- lib/mongoid/association/referenced/has_and_belongs_to_many/proxy.rb
- lib/mongoid/association/referenced/has_many/proxy.rb
- spec/mongoid/errors/delete_restriction_spec.rb
I tested all of the dependency types for both has_many and has_one and they all work as intended for each type.
> MONGOID-4909 updated documentation to include correct dependency types

- lib/mongoid/criteria/queryable/storable.rb
- lib/mongoid/errors/invalid_query.rb
- lib/mongoid/matcher/all.rb
- lib/mongoid/matcher/exists.rb
- lib/mongoid/matcher/expression.rb
- lib/mongoid/matcher/nor.rb
- lib/mongoid/matcher/not.rb
- lib/mongoid/matcher/or.rb
- lib/mongoid/matcher/regex.rb
- lib/mongoid/matcher/size.rb
- spec/integration/matcher_operator_data/all.yml
- spec/integration/matcher_operator_data/and.yml
- spec/integration/matcher_operator_data/elem_match.yml
- spec/integration/matcher_operator_data/eq.yml
- spec/integration/matcher_operator_data/exists.yml
- spec/integration/matcher_operator_data/gt.yml
- spec/integration/matcher_operator_data/gte.yml
- spec/integration/matcher_operator_data/implicit.yml
- spec/integration/matcher_operator_data/in.yml
- spec/integration/matcher_operator_data/lt.yml
- spec/integration/matcher_operator_data/lte.yml
- spec/integration/matcher_operator_data/ne.yml
- spec/integration/matcher_operator_data/nin.yml
- spec/integration/matcher_operator_data/nor.yml
- spec/integration/matcher_operator_data/not.yml
- spec/integration/matcher_operator_data/or.yml
- spec/integration/matcher_operator_data/regex.yml
- spec/integration/matcher_operator_data/size.yml
- spec/integration/matcher_operator_spec.rb
https://jira.mongodb.com/browse/MONGOID-4892
> MONGOID-4892 Test embedded matchers with wrong operator argument types

- spec/integration/matcher_operator_data/nin.yml
https://jira.mongodb.com/browse/MONGOID-4781
Was accidentally querying on the wrong field.
> MONGOID-4781 fix $nin tests

- spec/support/spec_config.rb
Added port 27017. This fixes failing test.
> MONGOID-4924 change default host to have port

- spec/integration/matcher_examples_spec.rb
> MONGOID-4894 Enable remaining tests for invalid operators

- lib/mongoid/copyable.rb
- lib/mongoid/criteria.rb
- lib/mongoid/indexable.rb
- lib/mongoid/persistable/deletable.rb
- lib/mongoid/serializable.rb
- spec/integration/discriminator_key_spec.rb
- spec/mongoid/copyable_spec.rb
- spec/mongoid/criteria_spec.rb
- spec/mongoid/indexable_spec.rb
- spec/mongoid/persistable/deletable_spec.rb
- spec/mongoid/serializable_spec.rb
Also found and replaced places where _type was hard-coded
> MONGOID-4943 fixed persistability bug when setting a custom discriminator_key

- docs/tutorials/mongoid-documents.txt
The documentation seems a lot shorter for this than`discriminator_key`... Am I missing anything?
> MONGOID-4946 write up discriminator value documentation

- docs/tutorials/mongoid-relations.txt
https://jira.mongodb.com/browse/MONGOID-4781
> MONGOID-4781 final documentation tweaks

- lib/mongoid/association/referenced/has_many/enumerable.rb
- spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb
- spec/mongoid/association/referenced/has_many/enumerable_spec.rb
Apologies for all the whitespace changes in the diff.
> MONGOID-4947 include block and pattern params in any?

- lib/mongoid/association/referenced/has_many/enumerable.rb
- lib/mongoid/association/referenced/has_many/proxy.rb
- spec/mongoid/association/referenced/has_many/proxy_spec.rb
> MONGOID-4522 add tests for #any? not retrieving entire result set, like #exists?

- lib/mongoid/atomic/modifiers.rb
- spec/integration/atomic/modifiers_spec.rb
- spec/mongoid/atomic/modifiers_spec.rb
https://jira.mongodb.com/browse/MONGOID-4980
> Fix MONGOID-4980 Atomic push incorrectly determines whether there is a conflict

- lib/mongoid/query_cache.rb
- spec/mongoid/query_cache_spec.rb
The change couldn't be cherry-picked directly into 7.1, so I've replicated it here. I will also backport this change to 7.0.
> MONGOID-4978 Backport test and fix to 7.1

- spec/mongoid/query_cache_spec.rb
I took all tests that didn't have an `expect_query` call and added one. I also discovered that calling `Xyz.first` queries with a sort by id, so I added a note to MONGOID-4972 about it.
> MONGOID-4756: modify query cache tests to check that query cache is used

- lib/mongoid/fields/validators/macro.rb
- spec/mongoid/fields_spec.rb
Fixes https://jira.mongodb.org/projects/MONGOID/issues/MONGOID-4988
> MONGOID-4988 Only warn FIELD_TYPE_IS_SYMBOL once

- docs/tutorials/mongoid-queries.txt
- lib/mongoid/criteria.rb
- lib/mongoid/findable.rb
- spec/mongoid/criteria_spec.rb
https://jira.mongodb.com/browse/MONGOID-4914
> MONGOID-4914 Unmask Enumerable#find on one to many associations

- lib/mongoid/copyable.rb
- spec/mongoid/copyable_spec.rb
- spec/mongoid/copyable_spec_models.rb
https://jira.mongodb.com/browse/MONGOID-4969
> MONGOID-4969 Improve efficiency of clone method

- Gemfile
- docs/tutorials/mongoid-relations.txt
- gemfiles/driver_master.gemfile
- gemfiles/driver_master_jruby.gemfile
- gemfiles/driver_min.gemfile
- gemfiles/driver_min_jruby.gemfile
- gemfiles/driver_oldstable.gemfile
- gemfiles/driver_oldstable_jruby.gemfile
- gemfiles/driver_stable.gemfile
- gemfiles/driver_stable_jruby.gemfile
- gemfiles/i18n-1.0.gemfile
- gemfiles/rails_51.gemfile
- gemfiles/rails_52.gemfile
- gemfiles/rails_master.gemfile
- lib/mongoid/association/embedded/embedded_in.rb
- lib/mongoid/touchable.rb
- spec/lite_spec_helper.rb
- spec/mongoid/touchable_spec.rb
- spec/mongoid/touchable_spec_models.rb
https://jira.mongodb.com/browse/MONGOID-3468
> MONGOID-3468 Always touch parents of embedded documents when embedded documents are touched

- docs/tutorials/mongoid-relations.txt
- lib/mongoid/association/proxy.rb
- lib/mongoid/document.rb
- spec/mongoid/association/referenced/belongs_to/proxy_spec.rb
- spec/support/models/person.rb
https://jira.mongodb.com/browse/MONGOID-5009
> Test & document MONGOID-5009 Belongs to relationship changes method visibility

- docs/tutorials/mongoid-upgrade.txt
- lib/mongoid/criteria/queryable/mergeable.rb
- spec/integration/matcher_operator_data/in.yml
- spec/mongoid/criteria/queryable/mergeable_spec.rb
- spec/mongoid/criteria/queryable/selectable_logical_spec.rb
https://jira.mongodb.com/browse/MONGOID-5020
> Fix MONGOID-5020 Condition lifting breaks with symbol operators on Ruby <= 2.6

- .evergreen/config.yml
- docs/tutorials/mongoid-installation.txt
- gemfiles/rails_60.gemfile
- lib/mongoid/document.rb
- lib/mongoid/interceptable.rb
- mongoid.gemspec
- spec/integration/app_spec.rb
https://jira.mongodb.com/browse/MONGOID-5027
> MONGOID-5027 Rails 6.1 support

- spec/mongoid/association/embedded/embedded_in/proxy_spec.rb
- spec/mongoid/atomic/paths_spec.rb
- spec/support/models/customer.rb
- spec/support/models/customer_address.rb
https://jira.mongodb.org/browse/MONGOID-5039
> Test cases for MONGOID-5039 Multiple polymorphic embeds cause wrong association to be assigned

- docs/tutorials/mongoid-relations.txt
> MONGOID-4962 Clarify storage of referenced associations

- .dockerignore
- Gemfile
- gemfiles/driver_master.gemfile
- gemfiles/driver_master_jruby.gemfile
- gemfiles/driver_min.gemfile
- gemfiles/driver_min_jruby.gemfile
- gemfiles/driver_oldstable.gemfile
- gemfiles/driver_oldstable_jruby.gemfile
- gemfiles/driver_stable.gemfile
- gemfiles/driver_stable_jruby.gemfile
- gemfiles/i18n-1.0.gemfile
- gemfiles/rails_51.gemfile
- gemfiles/rails_52.gemfile
- gemfiles/rails_60.gemfile
- gemfiles/rails_master.gemfile
- gemfiles/standard.rb
https://jira.mongodb.com/browse/MONGOID-5051
> MONGOID-5051 Fix JRuby test failures on master

- spec/integration/callbacks_models.rb
- spec/integration/callbacks_spec.rb
> Test for MONGOID-5104 attribute_was returns previous value in after_save callback

- .evergreen/config.yml
This one should be merged after https://github.com/mongodb-labs/mongo-ruby-spec-shared/pull/17
> MONGOID-5113 Enable 3.6 configurations

- lib/config/locales/en.yml
- spec/mongoid/errors/invalid_scope_spec.rb
- spec/mongoid/errors/unknown_attribute_spec.rb
Fixes MONGOID-5055
Also fix various typos in errors.
> MONGOID-5055 Improve error message for UnknownAttribute

- spec/mongoid/config_spec.rb
Only added specs, no behavior change.
Fixes MONGOID-5017
> MONGOID-5017 Better specs for #truncate! and #purge!

- lib/mongoid/document.rb
- lib/mongoid/tasks/database.rb
- spec/mongoid/document_spec.rb
> MONGOID-4737 Deprecate the :compact option on Document#as_json

- lib/mongoid/association/embedded/embeds_many/proxy.rb
- spec/mongoid/association/embedded/embeds_many/proxy_spec.rb
- spec/mongoid/association/referenced/has_many/proxy_spec.rb
https://jira.mongodb.com/browse/MONGOID-5105
> MONGOID-5105 Allow block form in Mongoid::Association::EmbedsMany::Proxy#count 

- SECURITY.md
Instructions copied from https://github.com/mongodb/mongo-ruby-driver#security-issues.
> Create security policy following github's template

- lib/mongoid/selectable.rb
- spec/integration/callbacks_spec.rb
> MONGOID-5078 Updated atomic_selector in after_save

- docs/reference/configuration.txt
- lib/mongoid/association/embedded/embeds_one/proxy.rb
- lib/mongoid/config.rb
- spec/mongoid/association/accessors_spec.rb
- spec/mongoid/reloadable_spec.rb
> MONGOID-5235 Add Feature Flag: Reloading retains stale changed value

- docs/reference/configuration.txt
- lib/mongoid/config.rb
- lib/mongoid/contextual/aggregable/mongo.rb
- lib/mongoid/contextual/none.rb
- spec/mongoid/config_spec.rb
- spec/mongoid/contextual/aggregable/mongo_spec.rb
- spec/mongoid/contextual/aggregable/none_spec.rb
> MONGOID-5239 Add Feature Flag: Mongoid::Contextual::Aggregable::Mongo#sum does not return nil as expected for Mongoid::Document#none

- docs/reference/configuration.txt
- lib/mongoid/config.rb
- lib/mongoid/criteria/queryable/storable.rb
- spec/integration/criteria/logical_spec.rb
- spec/mongoid/config_spec.rb
- spec/mongoid/criteria/queryable/storable_spec.rb
> MONGOID-5236 Add Feature Flag: Existing `$and` clause in query is overwritten by `where` condition

- docs/reference/crud.txt
- spec/mongoid/reloadable_spec.rb
- spec/support/macros.rb
https://jira.mongodb.com/browse/MONGOID-5205
> MONGOID-5205 Document reloading behavior for changed attributes

- docs/reference/configuration.txt
- docs/release-notes/mongoid-7.4.txt
- lib/mongoid/config.rb
- lib/mongoid/extensions.rb
- spec/mongoid/config_spec.rb
- spec/mongoid/extensions_spec.rb
> MONGOID-5234 Add Feature Flag: Remove BSON::ObjectId#as_json override

- lib/mongoid/association/proxy.rb
- lib/mongoid/association/referenced/has_and_belongs_to_many/proxy.rb
- lib/mongoid/association/referenced/has_many/proxy.rb
- spec/integration/callbacks_models.rb
- spec/integration/callbacks_spec.rb
> MONGOID-3552 call after_save/after_remove callbacks at correct time in has_and_belongs_to_many association

- lib/mongoid/association/eager_loadable.rb
- spec/mongoid/criteria/includable_spec.rb
> MONGOID-4716 Fix eager loading of nested referenced associations

- spec/mongoid/criteria/findable_spec.rb
- spec/mongoid/extensions/date_time_spec.rb
- spec/mongoid/extensions/time_spec.rb
- spec/mongoid/extensions/time_with_zone_spec.rb
- spec/mongoid/findable_spec.rb
- spec/mongoid/traversable_spec.rb
- spec/rails/mongoid_spec.rb
https://jira.mongodb.com/browse/MONGOID-5261
> MONGOID-5261 Partial PR for using config_override

- lib/mongoid/traversable.rb
- spec/integration/associations/embedded_dirty_spec.rb
- spec/mongoid/atomic_spec.rb
- spec/support/models/membership.rb
> Fix MONGOID-5280 Mongoid 7.4 inserts only one embedded document when multiple documents are created with nil _id

- spec/mongoid/attributes/nested_spec.rb
- spec/mongoid/attributes/nested_spec_models.rb
MONGOID-4222
This is working as intended, I have added a test to document that.
> MONGOID-4222 Test: accept_nested_attributes doesn't work for multiple levels

- spec/integration/associations/embedded_spec.rb
- spec/mongoid/association/embedded/embeds_many_models.rb
MONGOID-4779
This is working as intended, I have added a test to document this.
> MONGOID-4779 Test: Calculation is different by cache in memory for association document

- lib/mongoid/association/referenced/counter_cache.rb
- spec/mongoid/association/referenced/has_many/proxy_spec.rb
- spec/support/models/person.rb
> MONGOID-4514 Counter cache not decremented when nullifying relation/association

- docs/reference/crud.txt
- lib/mongoid/association/referenced/has_and_belongs_to_many/proxy.rb
- lib/mongoid/fields.rb
- spec/mongoid/changeable_spec.rb
> MONGOID-4843 don't populate .changed_attributes setting has_and_belongs_to_many association

- lib/mongoid/association/referenced/has_many/proxy.rb
- spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb
- spec/mongoid/association/referenced/has_many/proxy_spec.rb
> MONGOID-5079 clear has_many association locally after destroy_all

- .evergreen/config.yml
- .evergreen/run-tests.sh
- gemfiles/standard.rb
- spec/integration/app_spec.rb
https://jira.mongodb.com/browse/MONGOID-5216
> RUBY-2947 MONGOID-5216 Update Mongoid test tooling for driver/MRSS 5.2/6.0 changes + partial work on app tests fixes

- lib/mongoid/fields.rb
This comment was added in a PR that was closed, and I thought that it was helpful to have around for the future.
> Add comment explaining how the result of database_field_name is used

- spec/mongoid/document_spec.rb
This PR dpends on #5301.
@p-mongo is this what you envisioned? Would you like me to add more tests? I will remove the feature flag 
changes when backporting.
> MONGOID-5362 Test return value type of #attributes

- lib/mongoid/association/embedded/batchable.rb
- lib/mongoid/atomic/paths/embedded/many.rb
- spec/mongoid/association/embedded/embeds_many/proxy_spec.rb
- spec/mongoid/association/embedded/embeds_many_models.rb
This PR does not add visible changes from MONGOID-4869.
> Backport MONGOID-5352 to 7.4-stable

- spec/mongoid/clients/options_spec.rb
- spec/mongoid/config_spec.rb
> MONGOID-5412 Fix JRuby 9.2/9.3 tests

- docs/tutorials/getting-started-rails.txt
https://resources.mongodb.com/migrating-to-mongodb/rdbmstomongodbmigration is no longer valid
> Update Rails Tutorial doc links

- spec/integration/discriminator_key_spec.rb
- spec/mongoid/document_spec.rb
> MONGOID-5427 Get rid of warnings generated in discriminator_key_spec

- lib/config/locales/en.yml
- spec/mongoid/errors/document_not_found_spec.rb
Refer to https://jira.mongodb.org/browse/MONGOID-5423
> MONGOID-5423: Improve DocumentNotFound error resolution language

- docs/reference/queries.txt
- lib/mongoid/contextual/mongo.rb
- spec/mongoid/contextual/memory_spec.rb
- spec/mongoid/contextual/none_spec.rb
https://jira.mongodb.com/browse/MONGOID-5391
> MONGOID-5391 improve pluck documentation, add tests

- lib/mongoid/scopable.rb
- spec/mongoid/scopable_spec.rb
https://jira.mongodb.org/browse/MONGOID-5435
> MONGOID-5435 Fix ArgumentError when block has positional and keyword arguments

- docs/reference/configuration.txt
- docs/release-notes.txt
- docs/release-notes/mongoid-8.1.txt
- lib/mongoid/config.rb
- lib/mongoid/config/defaults.rb
- spec/mongoid/config/defaults_spec.rb
> MONGOID-5293 Add Rails-style defaults & config.load_defaults

- lib/mongoid/persistence_context.rb
- spec/mongoid/clients_spec.rb
https://jira.mongodb.org/browse/MONGOID-5417
> MONGOID-5417 Fix memory leak when call 'with'

- docs/reference/queries.txt
- docs/reference/validation.txt
- lib/mongoid/validatable/uniqueness.rb
- spec/mongoid/validatable/uniqueness_spec.rb
https://jira.mongodb.org/browse/MONGOID-5150
> MONGOID-5150 Use primary read preference for validates_uniqueness_of 

- lib/config/locales/en.yml
- lib/mongoid/config.rb
- lib/mongoid/config/defaults.rb
- lib/mongoid/persistable.rb
- lib/mongoid/persistable/creatable.rb
- lib/mongoid/persistable/deletable.rb
- lib/mongoid/persistable/updatable.rb
- lib/mongoid/persistable/upsertable.rb
- lib/mongoid/stateful.rb
- lib/mongoid/warnings.rb
- spec/mongoid/config_spec.rb
- spec/mongoid/errors/readonly_document_spec.rb
- spec/mongoid/persistable/deletable_spec.rb
- spec/mongoid/persistable/destroyable_spec.rb
- spec/mongoid/persistable/incrementable_spec.rb
- spec/mongoid/persistable/logical_spec.rb
- spec/mongoid/persistable/poppable_spec.rb
- spec/mongoid/persistable/pullable_spec.rb
- spec/mongoid/persistable/pushable_spec.rb
- spec/mongoid/persistable/renamable_spec.rb
- spec/mongoid/persistable/savable_spec.rb
- spec/mongoid/persistable/settable_spec.rb
- spec/mongoid/persistable/unsettable_spec.rb
- spec/mongoid/persistable/upsertable_spec.rb
- spec/mongoid/reloadable_spec.rb
- spec/mongoid/stateful_spec.rb
Flip feature flag on 8.1: #5456
> MONGOID-5474 add readonly! and raise on save/update

- docs/reference/configuration.txt
- lib/mongoid/config.rb
- lib/mongoid/config/defaults.rb
- spec/mongoid/config_spec.rb
Wait for #5457 to be merged so we can flip the configuration docs.
> MONGOID-5474 flip the feature flag in 8.1

- mongoid.gemspec
Format modeled after https://github.com/mongodb/node-mongodb-native/blob/main/package.json
> MONGOID-5493: Update Gem::Specification team info

- docs/release-notes/mongoid-9.0.txt
> MONGOID-5515 Add release notes for smaller bug fixes/improvements for 9.0 features until now

- spec/mongoid/scopable_spec.rb
This PR contains pending specs for the issue described in https://jira.mongodb.org/browse/MONGOID-5483
> MONGOID-5483 Add pending tests for default_scope

- docs/tutorials/getting-started-rails7.txt
* Remove `--skip-bundle` from _Optionally Skip Tests_ section
> MONGOID-5496: Update Rails 7 Tutorial

- docs/reference/transactions.txt
- docs/release-notes/mongoid-9.0.txt
This PR adds documentation for the new features added in scope of https://jira.mongodb.org/browse/MONGOID-4732
Since I am not a native English speaker, suggestions are very welcome.
I am not sure about terms "Higher Level API" and "Lower Lever API", I hope we can come up with something better.
> MONGOID-4766 Document new transactions API

- lib/mongoid/config.rb
- lib/mongoid/interceptable.rb
- spec/integration/callbacks_models.rb
- spec/integration/callbacks_spec.rb
- spec/mongoid/interceptable_spec.rb
ref https://jira.mongodb.org/browse/MONGOID-5542
> MONGOID-5542 Prevent multiple calls of embedded docs callbacks

- lib/mongoid/matcher.rb
Backport of https://jira.mongodb.org/browse/MONGOID-5617
> MONGOID-5617 - Increase performance of `Matcher#extract_attribute`

- docs/reference/associations.txt
Addresses the documentation issue raised in discussion #5619
> MONGOID-5616: Dependent Behavior Documentation is incorrect

- lib/mongoid/atomic.rb
- lib/mongoid/changeable.rb
- lib/mongoid/reloadable.rb
- lib/mongoid/utils.rb
This PR enables rubocop on all non-spec files touched by MONGOID-5076, and addresses the resulting complaints.
> Enable rubocop on some files and address the resulting complaints

- docs/tutorials/automatic-encryption.txt
- lib/mongoid/clients.rb
- lib/mongoid/clients/factory.rb
- lib/mongoid/config/encryption.rb
- lib/mongoid/encryptable.rb
This PR fixes various problems encountered while developing FLE sample app:
- Documentation update
- Fixed deadlock while creating a default client if key vault client is used.
- Fixed schema generation
> MONGOID-5615 Fix various FLE issues

- lib/mongoid/association/macros.rb
- lib/mongoid/attributes/processing.rb
This PR is a linter-related follow-up for https://github.com/mongodb/mongoid/pull/5675
> Fix linter warnings

- lib/mongoid/contextual/mongo.rb
- spec/mongoid/contextual/mongo_spec.rb
> MONGOID-5647 #for_js with #count (backport to 8.0-stable)

- lib/mongoid/contextual/mongo.rb
- spec/mongoid/contextual/mongo_spec.rb
> MONGOID-5647 #for_js with #count (backport to 7.5-stable)

- Rakefile
I added a few rake tasks for some common evergreen commands that I got tired of typing out. :)
> Convenience tasks for evergreen

- docs/release-notes/mongoid-9.0.txt
- lib/mongoid/contextual/mongo.rb
- lib/mongoid/criteria.rb
- lib/mongoid/deprecation.rb
- spec/mongoid/criteria_spec.rb
https://jira.mongodb.org/browse/MONGOID-5681
> MONGOID-5651 Deprecate for_js API

- lib/mongoid/persistable/updatable.rb
- spec/mongoid/persistable/savable_spec.rb
Resolves MONGOID-5026
Refer to comment thread in ticket. There is nothing more to be fixed due to fundamental server limitations. Ticket should be closed.
> MONGOID-5026 - Remove code comments and close ticket

- docs/reference/configuration.txt
> Fix formatting in configuration.txt

- docs/release-notes/mongoid-9.0.txt
- lib/mongoid/contextual/aggregable/memory.rb
- lib/mongoid/contextual/aggregable/mongo.rb
- lib/mongoid/contextual/aggregable/none.rb
https://jira.mongodb.org/browse/MONGOID-5735
> MONGOID-5735 Deprecate aggregable API

- docs/reference/configuration.txt
- docs/reference/sharding.txt
- docs/reference/text-search.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37038
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-37038/
> DOCSP-37038: Fix broken links

- docs/reference/configuration.txt
- docs/reference/sharding.txt
- docs/reference/text-search.txt
(cherry picked from commit 861ce09993e145c7efc19a46aba04ceb2bb1efff)
> DOCSP-37038: Fix broken links backport

- docs/release-notes/mongoid-9.0.txt
- docs/release-notes/upgrading.txt
- docs/tutorials/automatic-encryption.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37059
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-37059/
Build log - https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65d8c9c67111165982a4d7af
> DOCSP-37059: Fix build errors

- docs/release-notes/mongoid-8.0.txt
(cherry picked from commit bd0ca4e5eea07f05106bbc6dce88aaacadb6fbf4)
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-37327-backport/release-notes/mongoid-8.0/
> DOCSP-37327: Fix table format (#5798)

- docs/release-notes/mongoid-9.0.txt
- lib/mongoid/contextual/aggregable/memory.rb
- lib/mongoid/contextual/aggregable/mongo.rb
- lib/mongoid/contextual/aggregable/none.rb
This reverts commit 8154e7c14efeb45a88a58a11aa53c5702e8008ac.
> Revert "MONGOID-5735 Deprecate aggregable API (#5778)"

- lib/mongoid/version.rb
Forgot to bump the version number for 8.1.6! (Oops...)
> Prep for 8.1.6
