mongodb/mongoid

lib/mongoid/traversable.rb, spec/mongoid/relations/referenced/many_spec.rb
The @_parent variable defined in Traversable was colliding with the "@_#{name}" variables defined by Relations. Added an extra underscore to the name to protect against this.
Fixes #3911
=> Fix relations named "parent".

lib/mongoid/railties/database.rake
This change will allow to load this rake tasks outside Rails enviroment :).
=> Require rails only if Rails variable is present

lib/mongoid/tasks/database.rb
Currently the task removes all of the indexes from Mongoid.models.
BSON::Document does not allow symbolic keys so we need to convert to
hash first.
=> Fix remove_undefined_indexes.

lib/mongoid/findable.rb, spec/mongoid/findable_spec.rb
This is an alternative version for find_by that raises error regardless of the value of Mongoid.raise_not_found_error
/cc @arthurnn
=> Add find_by!

CHANGELOG.md, lib/mongoid/relations/many.rb, spec/mongoid/persistable/creatable_spec.rb, spec/mongoid/relations/embedded/many_spec.rb, spec/mongoid/relations/referenced/many_spec.rb, spec/mongoid/relations/referenced/many_to_many_spec.rb
Pull request for Issue #3931. This adds a find_or_create_by! method to many associations.
person.posts.find_or_create_by!(:title => 'Testing')
=> Add #find_or_create_by! to many associations

CHANGELOG.md, lib/mongoid/contextual/none.rb, spec/mongoid/contextual/none_spec.rb
This addresses #3846 by adding the pluck method to the None class.
=> Allow pluck after with none. #3846

spec/mongoid/contextual/atomic_spec.rb, spec/mongoid/criteria_spec.rb, spec/spec_helper.rb
Some specs fail on `3.1.0-stable` because of updated dependencies. This PR updates specs to pass, mirroring changes on `master`. Hope this helps! :koala: 
**1. i18n  [`v0.7.0`](https://github.com/svenfuchs/i18n/blob/v0.7.0/CHANGELOG.md) `enforce_available_locales` now defaults to true:**
fix mirrors PR to `master` (https://github.com/mongoid/mongoid/pull/3899)
**2. Changing behavior in MongoDB 2.6+:**
fix mirrors commit to `master` (https://github.com/mongoid/mongoid/commit/e93a4837b0266db46c24aae172e184f57c847b04)
**3. Moped::Errors::QueryFailure message change:**
fix mirrors commit to `master` (https://github.com/mongoid/mongoid/commit/fa57fca58a19b7eba4ac03cdaacee57a8924145e)
=> Fix specs on 3.1.0-stable

lib/mongoid/relations/proxy.rb, spec/mongoid/relations/proxy_spec.rb
Quite hard to see where does the problem comes but I finally managed to find why does `public_send(:find)` does not behave the same as `find`: http://stackoverflow.com/questions/29695736/mongoid-embedded-collection-response-to-find
The pull request is really simple, and I added a test that fails without this PR.
=> Mongoid::Relations::Proxy#public_send should not be delegated to @target

lib/mongoid/scopable.rb, spec/app/models/audio.rb, spec/mongoid/document_spec.rb
This fixes #3723. The previous code was looking for "#each_pair", thus expecting a complex query to be a hash, but a scope like the following:
```ruby
default_scope ->{ self.or({:likes => nil}, {:likes.gt => 100}) }
```
creates an array of hashes. I think looking for "#each" instead is the best solution.
=> Fix default_scope sometimes generating an unwanted field because of a complex query

lib/mongoid/attributes/readonly.rb, spec/mongoid/attributes/readonly_spec.rb
`attr_readonly` did not work as expected when being provided the aliases of fields. See 060687d for the failure scenario.
(I may have gone a little overboard with the specs… Feel free to cut as appropriate.)
=> Make attr_readonly compatible with field aliases

lib/mongoid/relations/counter_cache.rb, spec/mongoid/relations/counter_cache_spec.rb
Sometimes actions on nested records with counter caches can be triggered on already destroyed records. When records are frozen, avoid attempting to update the counter_cache column.
Without this, counter_cache.rb:119 causes RuntimeError: can't modify frozen Hash.
=> don't try to update counter_cache on frozen records

lib/mongoid/extensions/set.rb
It appears the code documentation for Set was copied incorrectly from Range. Set mongoizes/demongoizes to/from Array, not Hash.
=> Correct code documentation for Set extension

lib/rails/mongoid.rb, spec/rails/mongoid_spec.rb
According to the documentation `preload_models` is either a Boolean or an Array of models to preload. Unfortunatelly specifing the model name (`User`) would not cause proper preloading on case sensitive file systems.
This commit fixes this and also adds support for preloading camel cased model names by calling `.underscore` on the given model name.
=> Converts preloaded models to their actual filename when loading them

lib/mongoid/atomic.rb, lib/mongoid/attributes.rb, lib/mongoid/changeable.rb, lib/mongoid/composable.rb, lib/mongoid/config.rb, lib/mongoid/document.rb, lib/mongoid/fields.rb, lib/mongoid/indexable.rb, lib/mongoid/query_cache.rb, lib/mongoid/serializable.rb, lib/mongoid/sessions.rb, lib/mongoid/validatable.rb, spec/mongoid/copyable_spec.rb, spec/mongoid/fields/localized_spec.rb, spec/mongoid/fields_spec.rb, spec/mongoid/persistable/updatable_spec.rb
1) Hash#has_key? has been depreciated in favour of Hash#key?
2) &block is unused variable , it would be better to name it starting with _.
=> changes done as per ruby style guide

lib/mongoid/traversable.rb, spec/mongoid/traversable_spec.rb
`.hereditary?` returns nil for the parent. Small, but caused an issue for me. Fixed tests to ensure strict true/false checking.
=> ensure .heriditary? returns true or false, not nil.

CHANGELOG.md, lib/mongoid/criteria.rb, spec/mongoid/criteria_spec.rb
Force to use '_id' on method only and don't permit to remove '_id' with
method without.
Fixes #3740
=> Avoid "Missing attribute: '_id'" error when using methods only or without

lib/rails/generators/mongoid/config/templates/mongoid.yml
Updates the generator for mongo driver options:
Adds 'mode' on 'read' (maybe also add a commented :tag_sets later?)
Keeps yml structure on 'write'.
=> Updates `mongoid.yml` generator for mongo driver

lib/mongoid/scopable.rb, spec/mongoid/scopable_spec.rb
Example:
```ruby
class Shape
scope :visible, -> { large }
scope :large, -> { all }
end
class Circle < Shape
scope :large, -> { where(radius: 5) }
end
```
`Circle.visible.selector` returns `{}`, instead of `{ "radius" => 5 }`.
ActiveRecord also uses `instance_exec` when [calling scopes](https://github.com/rails/rails/blob/6b5f815cf832524ebcf7585a44bbb7e291423c71/activerecord/lib/active_record/scoping/named.rb#L151).
This should also fix #3599.
=> Use sublcass context when calling a scope defined in a superclass

lib/mongoid/tasks/database.rb
Just a suggestion. It seems like it would be nice to enable the same logger configuration in rake tasks as are allowed during regular mongoid operation.
=> rake tasks should use Mongoid.logger

lib/mongoid/config/options.rb, lib/mongoid/railtie.rb
`persist_in_safe_mode` was removed in version 3.
=> Remove all references to 'persist_in_safe_mode'.

lib/mongoid/errors/mongoid_error.rb, spec/mongoid/errors/mongoid_error_spec.rb
In some cases, I want to catch Mongoid::Errors::MongoidError and include the **problem** field in my own exception, without the **summary** or **exception** fields.  Currently i'm using `problem = exception.instance_variable_get(:@problem)` and I can't think of a reason why these fields shouldn't be readable from outside the class.
=> Provide read-access to problem, summary and resolution fields for Mongoid::Errors::MongoidError

lib/rails/generators/mongoid/config/templates/mongoid.yml
Hey there,
first of all, many thanks for Mongoid.
This is a small pull request which fixes the generated Mongoid configuration. I think, with Mongoid 5.0.0, the mode must be a symbol.
=> Fixed template for Mongoid configuration

lib/mongoid/contextual/aggregable/mongo.rb, spec/mongoid/contextual/aggregable/mongo_spec.rb, spec/mongoid/contextual/mongo_spec.rb
Need to figure out a better way to test, i.e. not test a private method specifically.
Change code to apply two $match operators, first will apply the $exists selector, the second will apply the user-defined selector.
Test the situation in which the selector refers to a field that is not present to make sure calculations don't fail.
=> MONGOID-4119 Ensure that criteria selector becomes pipeline operator value

lib/mongoid/indexable/specification.rb, spec/mongoid/indexable/specification_spec.rb, spec/mongoid/indexable_spec.rb
See [Mongo::Index::View::OPTIONS](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/index/view.rb#L48), [Mongo::Index::View#create_one](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/index/view.rb#L95) and
http://docs.mongodb.org/manual/reference/method/db.collection.createIndex/#ensureindex-options.
=> Adapt index option mappings to new driver

lib/mongoid/indexable/validators/options.rb
specifically I was missing 'language_override' in my project and had to create the index manually
I've also add 'storage_engine' although I'm not sure what it does
based on
http://docs.mongodb.org/manual/reference/method/db.collection.createIndex/
=> add missing index options

lib/mongoid/clients.rb, spec/mongoid/clients/options_spec.rb
This pull request solves a few problems:
- If #with is called on a Model, the database name is passed as an option to the new client as a Symbol. In the driver, the database name is a string, so [this line](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/client.rb#L324) will return false and a new cluster will be created. A new cluster means more monitoring threads.
- Arbitrary options passed to Mongo::Client#with, creating new clusters (and monitoring threads); if an option is passed to Mongo::Client#with that isn't even a valid option, a new cluster will be created because the option won't be a member of [this list](https://github.com/mongodb/mongo-ruby-driver/blob/master/lib/mongo/client.rb#L28).
- Mongoid now never calls #with on Mongo::Client with options that …
=> MONGOID-4157 Ensure that new clusters are not created when new client options are set

lib/mongoid/attributes.rb, spec/mongoid/attributes_spec.rb
This is to fix issue https://github.com/mongoid/mongoid/issues/4055
=> Fix assigning a localized field when attributes is a BSON::Document

lib/mongoid/relations/embedded/batchable.rb, spec/mongoid/attributes/nested_spec.rb
fixes updating DB before validation, but now if validation fails on document deletion that document will return true for 'doc.destroyed?' even though it wasn't destroyed
=> Mongoid 3808, Mongoid 2984

lib/mongoid/clients.rb, lib/mongoid/clients/options.rb, spec/mongoid/clients/options_spec.rb, spec/spec_helper.rb, spec/support/authorization.rb
This goes in 5.1.0 so don't merge until later.
=> MONGOID-4190 Disconnect new clusters to avoid leaving monitor threads running in calls to Model#with

lib/mongoid/matchable.rb, spec/mongoid/matchable_spec.rb
https://jira.mongodb.org/browse/MONGOID-4202
=> Support $not matching for matches? so embedded document search can use $not

lib/mongoid/relations/targets/enumerable.rb
Marshal state of @executed to allow for complete state saving. Without this, caching a query with .includes in it will raise error "undefined method `selector' for nil:NilClass" when trying to enumerate over the included part. Example:
```
def cached_users
Rails.cache.fetch('users') do
users.includes(:friends).entries
end
end
friends_group = cached_users.select { |u| u.friends.include? best_friend }
```
=> More complete enumerable marshaling

lib/mongoid/indexable/validators/options.rb
Partial indexes were added in MongoDB 3.2 and ruby driver 2.2.
=> Support partial indexes.

lib/mongoid/clients/options.rb, spec/mongoid/clients/options_spec.rb
Redesign using a context object instead of class/instance variables is needed. We need to get rid of the use of Thread local variables.
=> MONGOID-4196 Temporarily fix concurrency issues with persistence options. Redesign is needed.

lib/mongoid/changeable.rb, spec/mongoid/changeable_spec.rb
Mongoid::Changeable#changes should return a HashWithIndifferentAccess.
Or whether there is a reason to return the Hash it 's not HashWithIndifferentAccess?
=> Mongoid::Changeable#changes returns a hash with indifferent access.

lib/mongoid/extensions/string.rb
Dynamic attributes relies on this regex to filter method name candidates that are valid to def: https://github.com/mongodb/mongoid/blob/master/lib/mongoid/attributes/dynamic.rb#L39
=> Method names containing hyphens are not valid

lib/mongoid.rb
Those methods had the word session instead of client in versions prior mongoid 5.0.0.
Thus it is irritating to say that the method default_client is available since version 3.0.0, since I can't call it in versions 3.0.0 or 4.0.0.
=> Update @since attributes for Mongoid client methods

lib/rails/generators/mongoid/config/templates/mongoid.yml
I had a problem recently where I couldn't connect to an SSL instance that used self-signed certificates. I found out that if I manually specify `ssl_verify: false`, it will connect, and if I specify `ssl_verify: true`, I get the same error as I did while using the default. Therefore I've determined that the default for this is actually true, not false, as it currently says in the config file. Changing the config file to reflect this will likely help others avoid headaches in the future.
=> Update the config template to reflect that ssl_verify is on by default

lib/mongoid/attributes.rb, spec/mongoid/attributes_spec.rb
MONGOID-4260 introduced a regression when checking for presence on blank
fields. This PR switches back to the old lookup method and adds a spec
to prevent this issue in the future.
/cc @estolfo 
Please review my PR
=> MONGOID-4260 Fix regression with blank fields

lib/mongoid/contextual/mongo.rb, spec/mongoid/contextual/mongo_spec.rb
Following the idea of thomas morgan in this ticket: https://jira.mongodb.org/browse/MONGOID-4175 
@pedroescudero and I have developed this fix for maintaining the legacy of #first and #last in has_many relationships with the new functionality removing the default sort criteria ({id_ 1}) with a flag called sort: :none.
We have plenty of applications with mongoid 4 and other SQL servers so to keep the same standard/behaviour if we want to upgrade the gem to v5 we think this solution allow to maintain the previous code without breaking all #last calls.
ex:
Band.all.first #legacy functionality, returns the first document with sort: {id: 1}
Band.all.last #legacy functionality, returns the last document with sort: {id: 1}
Band.all.first(sort: :none) #default functionality, returns the first …
=> MONGOID-4175 has_many first and last supporting legacy functionality

lib/mongoid/config.rb, lib/mongoid/relations/embedded/in.rb, lib/mongoid/relations/embedded/many.rb, lib/mongoid/relations/embedded/one.rb, lib/mongoid/relations/macros.rb, lib/mongoid/relations/options.rb, lib/mongoid/relations/referenced/in.rb, lib/mongoid/relations/referenced/many.rb, lib/mongoid/relations/referenced/many_to_many.rb, lib/mongoid/relations/referenced/one.rb, spec/config/mongoid.yml, spec/mongoid/config_spec.rb, spec/mongoid/relations/macros_spec.rb, spec/mongoid/relations/referenced/in_spec.rb, spec/spec_helper.rb
ActiveRecord by default requires an association for belongs_to relations. This pull request implements that behavior in Mongoid as well.
Commit in Rails: https://github.com/rails/rails/pull/18937/files
=> MONGOID-4264 Require a belongs_to association by default and accept :required and :optional relation options

lib/mongoid/attributes.rb, lib/mongoid/attributes/readonly.rb, lib/mongoid/persistable.rb, lib/mongoid/persistable/updatable.rb, spec/app/models/person.rb, spec/mongoid/attributes/readonly_spec.rb, spec/mongoid/attributes_spec.rb, spec/mongoid/persistable/savable_spec.rb, spec/mongoid/persistable/updatable_spec.rb
This pull request adds the ability to change attributes that have been explicitly loaded using #only or #without. It takes out the behavior that such documents are entirely readonly.
=> MONGOID-3535 Allow explicitly loaded attributes to be changed. Take out entire doc readonly enforcement if #only or #without are used.

lib/mongoid/extensions/big_decimal.rb, lib/mongoid/extensions/string.rb, lib/mongoid/findable.rb, spec/mongoid/attributes/nested_spec.rb, spec/mongoid/extensions/big_decimal_spec.rb, spec/mongoid/extensions/float_spec.rb, spec/mongoid/extensions/integer_spec.rb, spec/mongoid/extensions/object_spec.rb, spec/mongoid/extensions/string_spec.rb, spec/mongoid/relations/accessors_spec.rb
Recently I attempted to migrate a number of `Float` fields to `BigDecimal`, and I found that the behavior is inconsistent between the two. This PR rectifies that situation. Note that `BigDecimal` is stored in MongoDB as a string, as there is no native BSON type for it.
- `demongoize` should always return a BigDecimal or else nil, never an empty string (this mirrors how Floats and Integers behave).
- `mongoize` should always return a String which can be demongoized to a BigDecimal, otherwise nil
- Support storing BigDecimal values `"Infinity"` and `"-Infinity"` in the database.
- The strings `"Infinity"` and `"-Infinity"` now evaluate as numeric? true.
- `BigDecimal`s now evaluate as numeric? true.
- Additional tests for BigDecimal covering all edge cases.
| Value to Demongoize | Current …
=> Improve BigDecimal mongoize behavior

lib/mongoid/criteria/modifiable.rb, lib/mongoid/document.rb, spec/app/models/record.rb, spec/mongoid/criteria/modifiable_spec.rb
depends on mongo >= 2.3, which depends on bson 4.1.1, so BSON::String::ILLEGAL_KEY can be referenced.
UPDATE: removed use of BSON::String::ILLEGAL_KEY and put in Mongoid's own constant so there's no dependency on driver 2.3
=> MONGOID-4261 MONGOID-3887 Assign hash attributes in first_or_* methods on Criteria

lib/mongoid/query_cache.rb, spec/mongoid/query_cache_spec.rb
The `sort` option is not added to the cache key, leading to wrong results when querying a collection:
```ruby
Mongoid::QueryCache.enabled = true
Band.asc(:name).pluck(:name)
=> ["AC DC", "ZZ Top"]
Band.desc(:name).pluck(:name)
=> ["AC DC", "ZZ Top"]
```
This PR adds the hash returned by the `Mongoid::Criteria::Queryable::Options#sort` method to the cache key.
=> Add sorting options to the cache key

lib/mongoid/copyable.rb, spec/mongoid/copyable_spec.rb
when cloning process_localized_fields only works from the parent
document causing embedded documents with translations to get
set to a hash instead of the proper translation
=> MONGOID-4289 Fix cloning with embedded translations

lib/mongoid/attributes.rb, lib/mongoid/criteria/queryable/optional.rb, lib/mongoid/criteria/queryable/options.rb, lib/mongoid/criteria/queryable/selector.rb, lib/mongoid/criteria/queryable/smash.rb, spec/mongoid/criteria_spec.rb
I have renamed `#normalized_key` to `#localized_key` for clarity.
The behavior should be clear by reading the added specs.
Fixes MONGOID-4052
Replaces #4277 
@estolfo @simi please review
=> #only and #without methods should not be scoped to specific locales, unless user explicitly does so.

lib/mongoid/contextual/mongo.rb, spec/mongoid/contextual/mongo_spec.rb
It's not safe to use `only` in a __lot__ (most?) cases. Back in the good ol' days (Mongoid 3) lazy-loading attributes worked as expected, so this would have been fine. However, `only` has essentially been producing invalid ORM objects since Mongoid 4. `map`'s behaviour needs to be changed to accomodate this.
Example crash caused by the existing `map` implementation:
```
> criteria.map :position
ActiveModel::MissingAttributeError: Missing attribute: 'type'.
from /app/vendor/bundle/ruby/2.3.0/gems/mongoid-5.1.3/lib/mongoid/attributes.rb:97:in `read_attribute'
from /app/vendor/bundle/ruby/2.3.0/gems/mongoid-5.1.3/lib/mongoid/fields.rb:414:in `block (2 levels) in create_field_getter'
from /app/vendor/bundle/ruby/2.3.0/gems/enumerize-1.1.1/lib/enumerize/attribute.rb:86:in `type'
from …
```
=> Mongo/Criteria map should use pluck, not only

lib/mongoid/relations/eager/has_and_belongs_to_many.rb, spec/mongoid/relations/eager/has_and_belongs_to_many_spec.rb
Because [`values_at`](http://ruby-doc.org/core-2.1.0/Hash.html#method-i-values_at) will return an `Array` of values corresponding to each key, and it's possible for a document to be removed from the database without updating the inverse document in a `has_and_belongs_to_many` association, using `includes` to eager load the association can assign `nil` in the list of documents.
Since that is not the behaviour when accessing a `has_and_belongs_to_many` association without eager loading (only the existing documents are loaded, no `nil`s), we should be consistent and do the same when eager loading.
I'd be interested in having this fix in _5.1_, let me know and I can make a PR 😃
=> Don't assign empty documents to HasAndBelongsToMany association

lib/mongoid/relations/proxy.rb, spec/mongoid/relations/proxy_spec.rb
This makes #object_id and #equals? consistent with each other so they are both always called against the Proxy.
Another possibility would be to pass through #object_id and #equals? to the target so that the Proxy and its target would look like the exact same object. This seems more likely to cause confusion/problems since they aren't actually the exact same object, and the code has being calling #object_id on the Proxy for a long time. 
The first commit rewrites the regex slightly. It now always does an exact match except for '__' prefixes. I'm happy to undo that refactoring if there is a reason the old way was better or more correct.
=> Make Proxy objects #equal? to themselves

lib/mongoid/clients/options.rb, spec/mongoid/clients_spec.rb
Mongoid would not always use the right database to persist data when persistence options (even an empty hash) are given, while at the same time using the `Mongoid.override_database` feature.
Our application is using `Mongoid.override_database` and although we are not using persistence options explicitly, empty hashes would end up in `Options#mongo_client`, and the method would return a `mongo` client that would use the default database, and not the one given to `override_database`.
We experienced very weird behaviour where one document would be saved in one database, and others in another one.
Here is the code sample that I used to figure out the problem, for your entertainment:
```
class Foo
has_many :bars
accepts_nested_attributes_for :bars
end
class Bar …
```
=> Use right database when override_database + options.

lib/mongoid/extensions/hash.rb, spec/mongoid/extensions/hash_spec.rb
fixes e.g:
`{ "name" => { "en" => "test" }}.__nested__("email.en")`
=> prevent NoMethodError when using __nested__

README.md
It seems current tested Ruby versions are described in [`.travis.yml`](https://github.com/mongodb/mongoid/blob/71c29a80599087008ecfbd057d3d049c2153c7ce/.travis.yml#L8-L10).
=> Fix tested Ruby versions in README.md

lib/mongoid/attributes.rb, spec/mongoid/attributes_spec.rb
From the model Person in the specs...
```ruby
class Person
field :desc, localize: true
end
```
```ruby
p = Person.new
p.desc = nil
p.desc? #=> false
p = Person.new
p.desc? #=>
NoMethodError: undefined method `[]' for nil:NilClass
from /Users/nicolasblanco/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/mongoid-6.0.0/lib/mongoid/fields/localized.rb:80:in `lookup'
```
After patch:
```ruby
p = Person.new
p.desc = nil
p.desc? #=> false
p = Person.new
p.desc? #=> false
```
This patch fixes the exception by doing the localized lookup only if there is an actual value and also adds one more test to the tests suite.
=> Localized attribute presence lookup which has a nil value should not fail

docs/tutorials/mongoid-indexes.txt
Sometimes creating/removing indexes for the entire database can be very expensive, when searching for the same behavior for just one collection I found out that it can be used directly on models, I thought that could be interesting to have mentioned on the docs :smile:
=> Add docs for create/remove indexes called on models

lib/mongoid/copyable.rb, spec/mongoid/copyable_spec.rb
This fixes cloning documents with legacy schemas in which one of the key is set to `nil`.
Before it would raise an error such as:
```
Mongoid::Errors::UnknownAttribute (
message:
Attempted to set a value for '...' which is not allowed on the model ...
summary:
Without including Mongoid::Attributes::Dynamic in your model and the attribute does not already exist in the attributes hash, attempting to call ...= for it is not allowed. This is also triggered by passing the attribute to any method that accepts an attributes hash, and is raised instead of getting a NoMethodError.
resolution:
You can include Mongoid::Attributes::Dynamic if you expect to be writing values for undefined fields often.):
```
=> Add support for cloning documents that have nil legacy attributes

lib/mongoid/contextual/map_reduce.rb, spec/mongoid/contextual/map_reduce_spec.rb
The read mode is forced to `primary` on a `map_reduce` client, when `inline == 1`, which makes it impossible to apply any other read mode (`secondary`, `secondary_preferred`...) when performing a `map_reduce` operation.
* MongoDB read replicas remain idle while performing a succession of `map_reduce` operations, even when the read mode is set to `secondary` in Mongoid configuration
* By outputing MongoDB logs in a Rails console, I get confirmation that the requests are sent to the primary node only.
Allow the `map_reduce` operation to use the client's `options` when applying the `command`.
This way, assuming you've configured a client in `secondary` read mode, a query like `criteria.with(client: :secondary).map_reduce(map, reduce).out(inline: 1)` would perform the operation in `secondary` …
=> Fix : map_reduce read mode is forced to "primary"

lib/mongoid/attributes/readonly.rb
In order to avoid namespace pollution, we could prefix the `loaded?` method as discussed in 
https://jira.mongodb.org/browse/MONGOID-4393
=> Prefix Readonly#_loaded? method to avoid namespace pollution

lib/mongoid/query_cache.rb, spec/mongoid/query_cache_spec.rb
When I call `#reload` on a document, I expect the data to be reloaded from the server, even if query caching is enabled.
=> Bypass the query cache when reloading a document

lib/mongoid/query_cache.rb, spec/mongoid/query_cache_spec.rb
This backports https://github.com/mongodb/mongoid/pull/4295 to the `5.1.0-stable` branch.
Rails 4.2 apps can't use Mongoid 6, so they'll be affected by this bug if they enable the query cache.
=> Backport #4295 to 5.1.0-stable

lib/mongoid/query_cache.rb, spec/mongoid/query_cache_spec.rb
One more query cache pull request 😁 
This backports https://github.com/mongodb/mongoid/pull/4350 to the `5.1.0-stable` branch, so that Rails 4.2 apps can get the fix.
=> Backport #4350 to 5.1.0-stable

lib/mongoid/relations/referenced/many.rb, spec/mongoid/relations/metadata_spec.rb
This fixes a bug in `Mongoid::Relations::Referenced::Many` when it goes
to find the inverse of a relationship within the
`#with_inverse_field_criterion` method. The method was trying to use
`:inverse_of_field` which doesn't exist on the metadata and is, instead,
`:inverse_of', resulting in a method-not-found error.
=> Fixed bug in relationships with `inverse_of` field

Gemfile, lib/mongoid/contextual/map_reduce.rb, spec/mongoid/contextual/map_reduce_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/spec_helper.rb
This prepares Mongoid's MapReduce implementation to be able to support collation.
I'm using the driver's Collection::View::MapReduce object in the Mongoid MapReduce object instead of manipulating and keeping track of its own command spec.
Collation can now be automatically applied.
Bugs in the ruby driver were discovered as a result of this. See https://github.com/mongodb/mongo-ruby-driver/pull/842
=> MONGOID-4326 Update MapReduce implementation to use driver object to lay groundwork for supporting collation

lib/mongoid/criteria/queryable/extensions/boolean.rb, spec/mongoid/extensions/boolean_spec.rb
HTML forms use "on" to indicate a checked checkbox value. This would provide seamless transition from an html form to a boolean value on a model.
=> [6.1.0] add string “on” to list of true boolean values

docs/mongoid.txt
mongomatic.com is gone
mongomodel.org is blog spam
=> Remove dead/spam Additional Mappers links

docs/tutorials/mongoid-installation.txt, lib/rails/generators/mongoid/config/templates/mongoid.yml
The default value of local_threshold configuration has been changed from 5 to 0.015 since [mongo-ruby-driver](https://github.com/mongodb/mongo-ruby-driver) ver 2.0.
[See source code and comments here](https://github.com/mongodb/mongo-ruby-driver/blob/8b442d8ff30083ef8dca3bc8dac78d4b924d9ff8/lib/mongo/server_selector.rb#L34)
So we'd better to update the document in the code.
There are no changes to the implementation.
=> Update the template and readme: local_threshold's default from 5 to 0.015

lib/mongoid/attributes.rb, spec/mongoid/attributes_spec.rb
I've read many issues about typed attributes absence in Mongoid (particularly, the latest is ["Custom types typecasting problem"](https://jira.mongodb.org/browse/MONGOID-2533), I guess). Despite of `#attributes` mongonized nature, I'd like to add method which allows to retrieve type casted (demongoized ) attributes.
This is my first PR to Mongoid project, so don't hesitate to abandon it or give some advices for the improvements.
=> Add typed attributes

lib/mongoid/relations/reflections.rb, spec/mongoid/relations/reflections_spec.rb
Hi guys!
I have noticed that there is something wrong with `Mongoid::Relations::Reflections.reflect_on_all_associations` method.
It said in rdoc that method supports `[ Array<String, Symbol> ]` as argument but it works only with symbols because `meta.macro` is `Symbol`.
Now I just fixed it so the method indeed can accept strings.
But maybe we just should left the method as is and simply update rdoc?
Also I've made the method work even without any arguments (in this case it returns all relations).
I saw that `ActiveRecord` [works](https://github.com/rails/rails/blob/ac027338e4a165273607dccee49a3d38bc836794/activerecord/lib/active_record/reflection.rb#L98) this way and it is useful for a task I'm working on.
But I am not sure if it would be useful for others. 
Thank you.
=> Update Relations::Reflections.reflect_on_all_associations method

lib/mongoid/criteria.rb, lib/mongoid/criteria/queryable.rb, lib/mongoid/document.rb, lib/mongoid/relations/builders.rb, lib/mongoid/relations/eager.rb, mongoid.gemspec
I see so many ruby warnings when I run my app with `RUBYOPT="-w"`,  so here's a fix for them.
Please note that I only fixed the ones that I see in my app. I'm not sure if there's any other place to fix.
=> Ruby Warnings

lib/rails/generators/mongoid/config/templates/mongoid.yml
Hi.
I have noticed that config [template](https://github.com/mongodb/mongoid/blob/master/lib/rails/generators/mongoid/config/templates/mongoid.yml) doesn't contain information about some options such as `duplicate_fields_exception` and `belongs_to_required_by_default`.
I added these options but I am not sure about descriptions.
I took description for `duplicate_fields_exception` option from CHANGELOG:
> #2938 A configuration option duplicate_fields_exception has been added that when set to true will raise an exception when defining a field that will override an existing method. (Arthur Neves)
And I wrote description for `belongs_to_required_by_default` by myself.
So maybe I should reword it somehow?
Thanks.
=> Update config template

lib/mongoid/criteria.rb
Hi.
This uncommented new line breaks documentation for `Criteria#merge` method.
Now it looks like:
While it should look like:
=> Fix YARD doc for Criteria#merge method

spec/mongoid/relations/touchable_spec.rb
In specs, when touching a model, assert that changes are not rolled back authomatically.
=> Small improvement to spec for Touchable

lib/mongoid/relations/eager.rb
In some case (more than one circular associations included) It is possible to get a `SystemStackError: stack level too deep`.
After some digging I found it localized in `Eager#preload` code. This patch fix it (ec2a1c6), remove a double iteration (3fc2e2b) and make the method body more readable (413613e, 81901fb and 6cefdb5).
=> Refactor eager preload to avoid stack overflow

lib/mongoid/contextual/mongo.rb
`Mongoid::Criteria#first({sort:none})` doesn't actually work. 
But this works: `Mongoid::Criteria#first({id_sort:none}`.
I've just fixed the typo in the documentation.
=> Fix sort to id_sort option typos

lib/mongoid/interceptable.rb, lib/mongoid/relations/touchable.rb, spec/mongoid/relations/touchable_spec.rb
While testing #4391 I discovered another infinite loop case is still possible with two embedded child docs:
touch Child A --> calls touch on Parent --> calls touch on Child B --> calls touch on Parent --> calls touch on Child A --> ...
I also discovered that **in most cases** the `touch` callback **does not actually cascade from parent to child docs**, it only cascades when the child has been modified.
```ruby
def in_callback_state?(kind)   # kind == :touch
[ :create, :destroy ].include?(kind) || new_record? || flagged_for_destroy? || changed?
end
```
Therefore, I believe the best solution is to never cascade the touch callback from parent -> child, and instead only do child -> parent, which avoids any possibility of loops.
This PR reverts the changes in #4391
=> Do not cascade :touch callback from parent to child

lib/mongoid/contextual/none.rb, spec/mongoid/contextual/none_spec.rb
Currently `Mongoid::Contextual::None` does not implement the `distinct` method.
Since `Mongoid::Contextual::None` is intended to provide a compatible API with the other contexts (to be used when no documents should be returned), it should implement `distinct` as well.
Added a test case that fails before the change, and passes after implementing the method.
```ruby
users = if admin?
User.where(email: /@mongodb.com/)
else
User.none
end
ids = users.distinct(:id)
```
=> Fix compatibility of Mongoid::Contextual::None with other contexts by adding distinct

lib/mongoid/matchable.rb, spec/mongoid/matchable_spec.rb
This allows selecting an item in an array by index.
Ex:
document: `{"occupants" => ["Tim","Logan"]}`
selector: `{ "occupants.0" => "Tim" }`
`document.matches?(selector)` will be true.
=> add support for matching index of an array

docs/tutorials/mongoid-queries.txt
`|scope|` is on the wrong side of the `do` keyword
=> Update mongoid-queries.txt with valid ruby

lib/mongoid/criteria/queryable/extensions/regexp.rb, lib/mongoid/matchable.rb, lib/mongoid/matchable/regexp.rb, spec/mongoid/criteria/queryable/extensions/regexp_raw_spec.rb, spec/mongoid/criteria/queryable/selectable_spec.rb, spec/mongoid/matchable/regexp_spec.rb, spec/mongoid/matchable_spec.rb
When a field is specified as a String, Mongoid previously assumed anything other than a native ruby regex should be converted to a String when defining the query selector. This pull request allows a BSON::Regexp::Raw type to be part of the query selector, without being converted to a String.
Also allow a BSON::Regexp::Raw object to be used in an in-memory query.
=> Allow raw bson regexp query criteria on fields specified as Strings

lib/mongoid/atomic.rb, lib/mongoid/contextual/memory.rb, lib/mongoid/copyable.rb, lib/mongoid/document.rb, lib/mongoid/matchable.rb, lib/mongoid/persistable/creatable.rb, lib/mongoid/persistable/upsertable.rb, lib/mongoid/relations/embedded/batchable.rb, lib/mongoid/relations/embedded/many.rb, lib/mongoid/relations/referenced/many.rb, lib/mongoid/serializable.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/validatable/uniqueness_spec.rb
Mongoid's callbacks rely on being able to mutate the ``attributes`` hash of a model object directly, so we replace the use of ``#as_document`` with ``#as_attributes``, and allow the public API method ``#as_document`` to continue returning a ``BSON::Document``.
=> MONGOID-4425 #as_document continues to return BSON::Document, but use internal api method #as_attributes otherwise

docs/index.txt
When publishing mongoid docs from 10gen/docs-mongoid, the process will now generate the API docs and publish along with the other docs.
=> Add link to v5.2 API docs

docs/index.txt
When publishing mongoid docs from 10gen/docs-mongoid, the process will now generate the API docs and publish along with the other docs.
=> Add link to 6.1 API docs

lib/mongoid/composable.rb
MONGOID-4418 included PersistenceContext method names in the list of prohibited field names, but Clients::Options should have been included instead.
=> MONGOID-4444 Don't include PersistenceContext methods in prohibted field names, include Clients::Options

lib/mongoid/config.rb, lib/mongoid/indexable.rb, lib/rails/generators/mongoid/config/templates/mongoid.yml, spec/config/mongoid.yml, spec/mongoid/config_spec.rb, spec/mongoid/indexable_spec.rb
Hey,
I wonder if we can add an additional option to create DB indexes in the background by default. 
I think it might be useful in case if somebody added an index on a huge collection and forgot to specify `background: true`. By setting something like:
```yaml
production:
options:
background_indexing: true
```
And after adding a new index:
```ruby
class Person
field :ssn
index ssn: 1 # <=== NEW INDEX
end
```
And running:
```sh
bundle exec rails runner "Person.create_indexes"
bundle exec rake db:mongoid:create_indexes
```
We can avoid human mistakes, which may lead to catastrophic DB blocking:
> By default, creating an index blocks all other operations on a database.
> https://docs.mongodb.com/manual/core/index-creation/
These changes don't break backward …
=> MONGOID-4448 Use "background_indexing" option by default to create new indexes

lib/mongoid/attributes.rb, lib/mongoid/attributes/readonly.rb, lib/mongoid/persistable.rb, lib/mongoid/persistable/incrementable.rb, lib/mongoid/persistable/logical.rb, spec/app/models/person.rb, spec/mongoid/attributes/readonly_spec.rb, spec/mongoid/persistable/savable_spec.rb
See this gist for ActiveRecord's behavior:
https://gist.github.com/estolfo/01933abfff69bfb54c3336281b611780
=> MONGOID-4455 Make readonly attributes behavior consistent with ActiveRecord

lib/mongoid/extensions/hash.rb, spec/mongoid/extensions/hash_spec.rb
Right now, when you have a document with a key that is `false`, the `__nested__` method on hashes will incorrectly return `nil`
For example:
```ruby
my_document["nested_data"]
my_document.nested_data["some_boolean_value"]
#Doing the same thing with `read_attribute` causes the value to be `nil`
my_document.read_attribute("nested_data.some_boolean_value")
```
Internally within the nested function we end up doing `false || nil` which ruby evaluates to `nil`.
`false` is a completely valid value in this case and we should return that.
More worryingly is if you have an integer keyed hash:
```ruby
my_document["nested_data"]
my_document.read_attribute("nested_data.this_doesnt_exist")
```
😱 
Internally, there is a `to_i` call on the string key, ruby's madness converts this to `0` which in this …
=> Fixup the falsey logic of `__nested__`

lib/mongoid/traversable.rb
warning shows when running specs on my application
=> remove warning: instance variable @__parent not initialized

lib/mongoid/matchable/and.rb
Change $or to $and in documentation for And.rb
=> Fix typo in documentation for And.rb

lib/mongoid/matchable/elem_match.rb, spec/mongoid/matchable/elem_match_spec.rb
This fixes an issue when :$elemMatch is used in a query as opposed to "$elemMatch"
=> fix elemMatch when symbol is used in query

lib/mongoid/persistence_context.rb
If you used Model.with() to specify a client and the name was invalid, it would make any subsequent calls to with() break even if valid.
PersistenceContext.clear(Model) wouldn't properly unset the context because calling on client would raise NoClientConfig.
=> Fix persistence context clear

lib/mongoid/contextual/mongo.rb, spec/app/models/band.rb, spec/mongoid/contextual/mongo_spec.rb, spec/spec_helper.rb
Example usage:
```ruby
Band.where(name: 'FKA Twigs').update_all({ '$set' => { 'labels.$[i].name' => 'Sony' } },
array_filters: [{ 'i.name' => 'Cbs' }])
```
=> MONGOID-4503 Support passing array_filters to update methods

lib/mongoid/attributes.rb, lib/mongoid/attributes/dynamic.rb, lib/mongoid/changeable.rb, lib/mongoid/fields.rb, lib/mongoid/serializable.rb, spec/mongoid/attributes_spec.rb
This is a behavior change, but corrects Mongoid's behavior to be consistent with ActiveRecord.
=> MONGOID-4483 Demongoize attributes when accessing via [] or read_attribute

lib/mongoid/criteria/queryable/extensions/string.rb, spec/mongoid/criteria/queryable/extensions/string_spec.rb
Mongoid ignored Active Support timezone when parses time from string inside query object. So I used method from https://github.com/mongodb/mongoid/blob/master/lib/mongoid/extensions/string.rb extension to parse dates from strings.
=> fix query date parser with ActiveSupport timezone

lib/mongoid/factory.rb
Rails in development mode by default doesn't eager load classes, `Object.const_defined?` can return `false` for exists constants
**models/book.rb**
```ruby
class Book
end
```
```
$ rails c
Running via Spring preloader in process 95641
Loading development environment (Rails 5.2.0.rc1)
2.5.0 :001 > Object.const_defined? 'Book'
=> true 
2.5.0 :002 > Object.const_defined? 'Book'
=> true 
2.5.0 :003 > reload!
Reloading...
=> true 
2.5.0 :004 > Object.const_defined? 'Book'
=> false 
2.5.0 :005 > ^C
$ RAILS_ENV=production rails c
Running via Spring preloader in process 96786
Loading production environment (Rails 6.0.0.alpha)
2.5.0 :001 > Object.const_defined? 'Book'
=> true 
2.5.0 :002 > Object.const_defined? 'Book'
=> true 
2.5.0 :003 > Object.const_defined? 'Book'
=> …
```
=> Fix Mongoid::Errors::UnknownModel

lib/mongoid/atomic/modifiers.rb, lib/mongoid/contextual/atomic.rb, spec/mongoid/contextual/atomic_spec.rb
Replaces #4461
Also, we should consider aliasing/renaming pull_all to "pull_each", or else renaming this method as "add_all_to_set"
=> Adds new atomic method "add_each_to_set" which will do an $addToSet with the $each modifier

Gemfile, lib/mongoid/criteria/queryable/extensions/time.rb, spec/lite_spec_helper.rb, spec/mongoid/criteria/queryable/extensions/time_spec.rb, spec/spec_helper.rb
I'm having problems with Mongoid queries modifying time variables. The following example shows how a Time object looses its time zone information after being used in a query where the Time object is used to query a field with the datatype DateTime. 
```
class Person
store_in collection: "persons"
field :birthday, type: DateTime
end
=> #<Mongoid::Fields::Standard:0 ...
time = Time.new(1970, 1, 1, 0, 0, 0, "+05:00")
=> 1970-01-01 00:00:00 +0500
Person.where(:birthday => time)
=> #<Mongoid::Criteria ...
time
=> 1969-12-31 19:00:00 UTC
```
I understand that Mongo performs conversions to UTC, but it should not modify the variable 'time'. This modification does not happend when using DateTime. The problem occurs at lib/mongoid/criteria/queryable/extensions/time.rb @ 31 …
=> Stop modification of time zones when converting Time objects

lib/rails/generators/mongoid/config/templates/mongoid.yml
It's not the first time that I had to search for this option and it's quite a popular question on Stackoverflow as well. Ideally I'd like to see this uncommented in the default generated config file but just adding the comment should help a lot of folks.
https://stackoverflow.com/questions/34753530/how-to-not-truncate-mongoid-logs
=> Add truncate_logs comment to config generator

lib/mongoid/copyable.rb, spec/mongoid/copyable_spec.rb
Given you have the following relations
```ruby
class Person
embeds_one :name
end
class Name
embeds_many :translations
end
class Translation
embedded_in :name
end
```
If you try to clone the `person`, you get the following error:
```ruby
Person.new(name: Name.new(translations: [Translation.new])).clone
```
This is related to this PR: https://github.com/mongodb/mongoid/pull/4455 and reverts this commit: https://github.com/mongodb/mongoid/commit/cd54dcb603c5ad22deb885d8395ef40564e60eb0#diff-499230fc3e0945686550bb7bd4fda9e9
Fixes https://jira.mongodb.org/browse/MONGOID-4560
=> Fix cloning documents with deep embedded documents

docs/tutorials/mongoid-installation.txt
Remove table column widths in mongoid-installation tutorial doc as the number of column widths and the number of columns are not in sync
=> docs: mongoid-installation - remove table column widths

.travis.yml
Given the long running times of our Travis jobs, it has been requested that we only test the latest version of MongoDB on Travis rather than every version (since we already test all versions on Evergreen)
=> stop building every mongodb version on travis

lib/mongoid/contextual/map_reduce.rb
This never failed in CI because CI didn't test replica sets.
=> Fix map reduce with a read preference

spec/mongoid/clients/factory_spec.rb
This test was failing when run with the drivers_master gemfile. Changing the addresses to dummy ports (which won't actually be available when the tests run) fixes the issue.
=> MONGOID-4610 Use dummy addresses in Mongoid::Clients::Factory test

.travis.yml, lib/mongoid/persistence_context.rb, spec/mongoid/clients/factory_spec.rb, spec/mongoid/clients/options_spec.rb, spec/mongoid/clients/sessions_spec.rb
This PR cherry picks the commits needed to get 6.4.0-stable passing on evergreen as well as updates the travis config to match the structure of master's.
See https://evergreen.mongodb.com/version/5b96d209c9ec4420668d6ab7 for the Evergreen job (minus the travis changes commit)
=> 6.4.0 stable

lib/mongoid/factory.rb, spec/mongoid/factory_spec.rb
NoMethodError is a child of NameError
If a class's instantiation throws a NoMethodError, the instantiation will fail with a Errors::UnknownModel error.
Change to only throw Errors::UnknownModel if the constantized class can not be found, or if the constantized class does not have an #instantiate method
=>  Don't capture NoMethodError when instantiating STI

lib/mongoid/persistable/settable.rb, spec/mongoid/persistable/settable_spec.rb
#4487 introduced a regression: one can no longer `$set` a nested hash value to anything that doesn't implement `empty?`.
This PR fixes a couple of bugs with the previous PR:
- Pull out the `value` from `field_and_value_hash` _before_ checking if it's `empty?`; this ensures we're checking the actual value that is attempting to be set
- Check that it is actually a `Hash` before checking if it's `empty?`
The reason previous tests passed is because they only checked that nested values could be set to a string, which implements `empty?`.
Relevant stacktrace here:
```ruby
undefined method `empty?' for 1531794645:Fixnum
./tmp/bundle/ruby-2.3.7/ruby/2.3.0/gems/mongoid-6.4.1/lib/mongoid/persistable/settable.rb:29:in `block (2 levels) in set' …
```
=> Fix Settable: allow setting a nested value to a non-string (for 6.4 stable)

lib/mongoid/matchable.rb, lib/mongoid/matchable/nor.rb, spec/app/models/array_field.rb, spec/mongoid/matchable/nor_spec.rb, spec/mongoid/matchable_spec.rb
Lets you use the `$nor` comparison operator for local comparisons: https://docs.mongodb.com/manual/reference/operator/query/nor/
If this is accepted, it would be great to backport to at least the 6.4 branch, too.
=> Add support for $nor to the Mongoid matcher.

docs/tutorials/mongoid-queries.txt, lib/mongoid/criteria/modifiable.rb, lib/mongoid/criteria/queryable/selectable.rb, spec/mongoid/criteria/modifiable_spec.rb
I ran each of the operations against ActiveRecord to determine how it behaves and modified the tests to assert those results instead. This PR does change the results of a number of operations, but the API  remains the same, so it doesn't require a major version bump.
=> MONGOID-4539 Fix behavior of create_with to match ActiveRecord

docs/tutorials/mongoid-installation.txt, docs/tutorials/mongoid-rails.txt, docs/tutorials/mongoid-upgrade.txt
Backport of https://github.com/mongodb/mongoid/commit/12e6b3effe7d9f68846db762cd5df103d03d1e3d to 6.4.0-stable
=> Add Ruby 2.5 & rails to support matrix (#4511) (#4551)

docs/tutorials/mongoid-configuration.txt
Update the Mongoid Configuration tutorial to show the default for `socket_timeout` is `nil` not `5`.
From the mongo driver documentation:
> *socket_timeout*
> The number of seconds to wait for an operation to execute on a socket before raising a timeout exception. It should take into account network latency and operation duration. The default is no value; the default is effectively infinity. Please consider using max_time_ms per-operation instead, as the socket_timeout does not stop the operation on the server; a long-running operation will continue to run on the server, beyond a socket timeout being reached.
— https://docs.mongodb.com/ruby-driver/master/tutorials/ruby-driver-create-client/index.html#details-on-timeout-options
Nothing in the driver code appears to set/default …
=> docs: socket_timeout default is nil, not 5

lib/mongoid/scopable.rb, lib/mongoid/threaded.rb, spec/mongoid/scopable_spec.rb, spec/mongoid/threaded_spec.rb
The method `Mongoid::Scopable.without_default_scope` has the peculiar behavior of suppressing default scopes of models not called upon to do so. For example:
```ruby
Appointment.without_default_scope do
Appointment.all.selector.empty? #=> true
Audio.all.selector.empty? #=> true
end
```
I have fixed this behavior, and have written specs to ensure it continues exhibiting the appropriate behavior. Additional methods were added to `Mongoid::Threaded` to allow for easily adding and removing classes from the `:without_default_scope` stack of the current thread, which now contains all the classes whose default scopes are being actively suppressed, rather than just containing `true` to denote a global suppression of default scopes.
I have left blank the `@since` doc attribute of the new methods …
=> Ensure without_default_scope does not suppress default scopes of other models

docs/tutorials/mongoid-rails.txt, lib/mongoid/railtie.rb, lib/mongoid/railties/controller_runtime.rb, spec/rails/controller_extension/controller_runtime_spec.rb
Hi there, I'm bringing back an issue about logging mongoid runtime per rails controller action. 
there was https://github.com/mongodb/mongoid/pull/3885 that failed to get into mongoid, not sure why, but now that code is incompatible.
the log message `Completed 200 OK in 52ms (Views: 0.2ms | ActiveRecord: 0.4ms | MongoDB: 0.1ms)` is nice but marginal feature.
we needed to collect some metrics about our rails application; this allows us to use standard rails notification:
```ruby
ActiveSupport::Notifications.subscribe 'process_action.action_controller' do |*args|
data = args.extract_options!
data[:mongo_runtime] # accessible here
end
```
and please, would it be possible to put it in older versions too? (we're currently on mongoid 5.1)
=> Rails controller runtime logging

lib/mongoid/extensions/regexp.rb, lib/mongoid/extensions/time.rb, spec/mongoid/extensions/regexp_spec.rb
Currently, setting a field of type regexp to nil results in the Ruby type error: `TypeError: no implicit conversion of nil into String` 
This PR nil guards the regexp mongoize extension similar to with the Time extension (mongoid/lib/mongoid/extensions/time.rb:72)
Please let me know if this should be submitted differently.
=> MONGOID-4666 Allow fields of type Regexp to be set to nil.

docs/tutorials/mongoid-documents.txt, lib/mongoid/criteria/queryable/extensions/date_time.rb, spec/mongoid/criteria/queryable/extensions/date_time_spec.rb
`DateTime.__evolve_time__` is supposed to return the `DateTime` as a `Time` in UTC.
However, when converting a non-UTC `DateTime` to a UTC `Time`, it throws away the `DateTime`'s timezone, instead assuming that it's in local time.
This PR fixes `__evolve_time__` to instead convert the `DateTime` to UTC, and then pass the result to `Time.utc`.
All the spec was wrong too; updated.
Before:
```ruby
DateTime.now.utc
=> 2018-12-08 06:14:21 UTC
DateTime.evolve(DateTime.now.in_time_zone('Eastern Time (US & Canada)').to_datetime)
=> 2018-12-08 09:14:21 UTC
DateTime.evolve(DateTime.now.in_time_zone('Pacific Time (US & Canada)').to_datetime)
=> 2018-12-08 06:14:21 UTC
DateTime.evolve(DateTime.now.in_time_zone('America/Menominee').to_datetime)
=> 2018-12-08 08:14:21 UTC
```
After:
```ruby …
```
=> MONGOID-4673 Fix DateTime.evolve - respect specified time zone

lib/rails/generators/mongoid/config/templates/mongoid.yml
The very important option for `uri` was missing in the doc! It exists in the official [docs](https://docs.mongodb.com/mongoid/master/tutorials/mongoid-configuration/) but not in the generated `mongoid.yml`.
=> Update mongoid.yml to add _uri_ option

lib/mongoid/extensions/big_decimal.rb, spec/mongoid/criteria/queryable/extensions/big_decimal_spec.rb, spec/mongoid/criteria/queryable/selector_spec.rb, spec/mongoid/criteria_spec.rb, spec/mongoid/extensions/big_decimal_spec.rb, spec/mongoid/fields_spec.rb, spec/mongoid/persistable/incrementable_spec.rb
To fix warning:
> BigDecimal.new is deprecated; use BigDecimal() method instead
Since:  ruby v2_6_1 & v2_6_0_rc2
Source: https://github.com/ruby/ruby/commit/62b55d9483d72a11345300296190b1e9c0ffd652#diff-cdf5d288e028f232ff6979d98276904a
=> MONGOID-4681 Replace BigDecimal.new with BigDecimal()

lib/mongoid/matchable.rb, lib/mongoid/matchable/eq.rb, lib/mongoid/matchable/ne.rb, spec/mongoid/matchable/eq_spec.rb
Currently Matchable doesn't support `#_matches?` against selectors that use the mongodb `$eq` operator. This adds support for it to do so.
=> MONGOID-4728 Adds Support for $eq operator in Matchable

lib/mongoid/association/referenced/eager.rb, spec/mongoid/association/referenced/belongs_to/eager_spec.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/eager_spec.rb, spec/mongoid/association/referenced/has_and_belongs_to_many_models.rb, spec/mongoid/association/referenced/has_many_models.rb
Let's say we have a "seats" collection and seats can optionally belong to a user. If we query all the seats and eager load the users, but none of the seats actually belong to a user, Mongoid will still query the database for users where the id is ```{"$in"=>[nil]}```. I see something like this in the logs: ```{"find"=>"users", "filter"=>{"_id"=>{"$in"=>[nil]}}...```
This change will skip the trip to the db if all the foreign keys are nil.
I applied the change to the v7.0.2 release and it worked for me. On v7.0.2 with this change, all the specs passed.
=> MONGOID-4729 Skip query if all keys from docs are nil

docs/tutorials/mongoid-documents.txt
Added docs of mongoid & mongo (mongo-ruby-drver) to a GitHub.io site (https://msp-greg.github.io/), using Pandoc for most ReST docs.  Skipped the docs with needed 'includes'.  Most of the docs are based on 'master' branches.
Others may be doing something similar locally...
=> mongoid-documents.txt - small fixes for pandoc/yard [skip ci]

lib/rails/generators/mongoid/model/model_generator.rb, lib/rails/generators/mongoid/model/templates/model.rb.tt
The principal changes are as follows. 
- Remove `-timestamp` options from the files generated when use `rails g model` command
- Add `include Mongoid::Timestamps` instead of it.
=> MONGOID-4741 Include timestamps in generated model by default

lib/mongoid/association/relatable.rb, spec/app/models/other_owner_object.rb, spec/mongoid/association/referenced/belongs_to_spec.rb
Following the rework of the `:class_name` option in v7.0.3, a value of '::SomeClass' causes a NameError exception. This fixes it so it works again (as it did in 7.0.2 and prior).
Example:
```
class Child
belongs_to :parent, class_name: '::OtherClass'
end
```
=> MONGOD-4749 Fix: association with class_name: '::SomeClass'

lib/mongoid/atomic/paths/embedded.rb, lib/mongoid/criteria/queryable/selector.rb, lib/mongoid/extensions/string.rb, lib/mongoid/positional.rb, lib/mongoid/query_cache.rb, lib/mongoid/validatable/macros.rb, spec/mongoid/criteria/queryable/extensions/numeric_spec.rb, spec/mongoid/criteria/queryable/selector_spec.rb
https://jira.mongodb.com/browse/MONGOID-4754
=> Fix MONGOID-4754 Some regular expressions are missing beginning/end anchors or are using them incorrectly

spec/README.md
This is primarily for documenting the `ulimit -n 10000` trick. For completeness, I've provided a simple "quick start" guide to running the tests against a single MongoDB instance.
=> Add README file to spec

mongoid.gemspec
It's because rubyforge was EOL. I referred to rubygems/rubygems#2798.
Following is a warning message for this.
```
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /Users/tnakata/.rbenv/versions/2.7.0-dev/lib/ruby/gems/2.7.0/bundler/gems/mongoid-555eb55c9d9f/mongoid.gemspec:27.
```
=> Remove `rubyforge_project` from gemspec because rubyforge was EOL

docs/tutorials/mongoid-relations.txt
For `target` begin changed to `_target`.
=> Fix the Mongoid Associations Extensions code example

docs/tutorials/mongoid-configuration.txt, docs/tutorials/mongoid-documents.txt, docs/tutorials/mongoid-indexes.txt, docs/tutorials/mongoid-persistence.txt, docs/tutorials/mongoid-queries.txt, docs/tutorials/mongoid-relations.txt, docs/tutorials/mongoid-upgrade.txt, lib/mongoid/config.rb, lib/mongoid/criteria/queryable/pipeline.rb, lib/rails/generators/mongoid/config/templates/mongoid.yml
https://jira.mongodb.com/browse/MONGOID-4852
Most of this PR is documenting the features that were added in the 7.0 development cycle rather than release notes themselves which are quite brief.
- I've finally located the aggregation pipeline builder DSL. It is very minimal though, only supports 3 operators.
- A big chunk of the diff is the rework of Mongoid option documentation. They were mentioned in 3 places (definition itself, tutorial documentation and mongoid.yml config template) with each defining/explaining some options that none of the others documented. Now all 3 have identical documentation.
- Added Mongoid option references to the rest of documentation where the affected functionality is described.
=> MONGOID-4852 add release notes for 7.0 and document missing features

lib/mongoid/persistable/pushable.rb, spec/mongoid/persistable/pushable_spec.rb
It seems when an instance is loaded from a database, its `attributes`
method returns an instance of `BSON::Document`. This causes some
surprising behavior when we use `#add_to_set` on that loaded instance.
When a value is assigned to a `BSON::Document` instance, it gets
modified:
https://github.com/mongodb/bson-ruby/blob/master/lib/bson/document.rb#L87-L89
During modification, the attribute loses its reference to the original
value, however the `add_to_set` method relies on this reference:
https://github.com/mongodb/mongoid/blob/136ccbc140b25719f48ff5185bb471f90c063148/lib/mongoid/persistable/pushable.rb#L27-L31
Since that reference is broken, it no longer update the instance's
attribute and the value is lost in memory, though still retained in the
DB.
This ensures that the reference …
=> Fix MONGOID-4874 Values seem to be lost when using add_to_set on a non-existent attribute on a loaded instance

lib/mongoid.rb, spec/app/models/delegating_patient.rb, spec/integration/document_spec.rb
https://jira.mongodb.com/browse/MONGOID-4833
=> MONGOID-4833 MONGOID-4849 Ruby 3.0 compatibility for 7.0 branch

.evergreen/config.yml, docs/tutorials/mongoid-queries.txt, spec/mongoid/contextual/map_reduce_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/criteria_spec.rb, spec/mongoid/shardable_models.rb, spec/mongoid/shardable_spec.rb, spec/spec_helper.rb
- Add 4.4 configurations
- Add documentation for map/reduce statistics, which are no longer available in 4.4
- Skip map/reduce statistics tests on 4.4
- Skip code with scope tests until 4886 is done
- Sort map/reduce results in tests because they arrive in different order in 4.4 after being executed through aggregation pipeline
- 4.4 allows a combination of hashed and non-hashed shard keys, use two hashed keys which 4.4 does not allow instead to produce failures
=> MONGOID-4848 Add server 4.4 configurations to evergreen

docs/tutorials/mongoid-upgrade.txt, docs/tutorials/sharding.txt, lib/mongoid/reloadable.rb, spec/mongoid/clients/sessions_spec.rb, spec/mongoid/reloadable_spec.rb, spec/support/models/profile.rb
https://jira.mongodb.org/browse/MONGOID-4902
I included some extra documentation for sharding with Global Clusters, since I initially thought that the `shard_key` method didn't actually modify the atomic selector for the document. I thought the tutorial was only used for setting up sharding on the cluster itself via rake tasks.
=> MONGOID-4902 Include shard key when reloading documents for improved query performance with Atlas Global Write clusters

lib/config/locales/en.yml, lib/mongoid/association/depending.rb, spec/mongoid/association/depending_spec.rb
https://jira.mongodb.com/browse/MONGOID-4912
=> MONGOID-4912 Use a translated message for when an association fails validation during deletion due to dependent documents existing

lib/mongoid/association/many.rb, lib/mongoid/association/referenced/has_many/enumerable.rb, spec/mongoid/association/depending_spec.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb
This is a pretty weird fix... Since _target can be either an enumerable or an array I had to make a method in enumerable that was already defined on arrays. This method turned out to be any?, which returns a boolean based on whether there is an element in the array.
Also note that `in_memory` and `_added` are both hashes in the any? function.
=> MONGOID-4890 change blank? to use exists and not count

lib/mongoid/matcher/all.rb, lib/mongoid/matcher/field_operator.rb, lib/mongoid/matcher/gt.rb, lib/mongoid/matcher/gte.rb, lib/mongoid/matcher/lt.rb, lib/mongoid/matcher/lte.rb, lib/mongoid/matcher/regex.rb, spec/integration/matcher_operator_data/all.yml, spec/integration/matcher_operator_data/and.yml, spec/integration/matcher_operator_data/elem_match.yml, spec/integration/matcher_operator_data/eq.yml, spec/integration/matcher_operator_data/gt.yml, spec/integration/matcher_operator_data/gte.yml, spec/integration/matcher_operator_data/lt.yml, spec/integration/matcher_operator_data/lte.yml, spec/integration/matcher_operator_data/nor.yml, spec/integration/matcher_operator_data/or.yml, spec/integration/matcher_operator_data/regex.yml, spec/integration/matcher_operator_data/size.yml
https://jira.mongodb.com/browse/MONGOID-4918
=> MONGOID-4918 Test embedded matchers with unusual document value types

lib/mongoid/traversable.rb, spec/mongoid/traversable_spec.rb
If the discriminator key changes before the class is created then it is created with the correct field, otherwise a second field is added in addition to type.
=> MONGOID-4928 implemented custom discriminator key fields

lib/mongoid/traversable.rb, spec/mongoid/traversable_spec.rb
On new instance of a class the correct discriminator field is being populated in the _type field.
=> MONGOID-4940 included discriminator_value field and added tests

lib/mongoid/query_cache.rb, spec/lite_spec_helper.rb, spec/mongoid/query_cache_spec.rb, spec/support/session_registry.rb
https://jira.mongodb.org/browse/MONGOID-4977
The current `Mongoid::QueryCache::View.each` method is in sync with `Mongo::Collection::View::Iterable` from [5 years ago](https://github.com/mongodb/mongo-ruby-driver/commit/2df954f609d0d29b517a27784e0408894e39466b).
Since then, `Iterable` has been updated with a number of new features:
- `close_query` [support](https://github.com/mongodb/mongo-ruby-driver/commit/e7dce35c2e66a24a954659de433db560abf23e6b)
- `sessions` [support](https://github.com/mongodb/mongo-ruby-driver/commit/9769cbeea128c5d77e243486306f255cfa543aa7)
- [support](https://github.com/mongodb/mongo-ruby-driver/commit/fc8d2e9af4907d0a6786d096bf9df3bcf7a7da38) for `write?` or `out?` queries
The primary issue with this is that any queries through the query cache don't utilize …
=> MONGOID-4977 Use recent driver APIs in Mongoid QueryCache for compatibility with sessions & modern retryable reads

lib/mongoid/query_cache.rb, spec/mongoid/query_cache_spec.rb, spec/support/session_registry.rb
This is a backport of RUBY-2338 into Mongoid ([see corresponding driver PR](https://github.com/mongodb/mongo-ruby-driver/pull/2072)).
There was a bug in the query cache implementation where it would cache _all_ queries, not just single batch queries. Thus, when the user tried to perform the same multi-batch query twice, it would attempt to re-iterate the cached query, which isn't allowed in the Ruby driver, and would raise an error.
=> MONGOID-4978 Stop raising error when performing multi-batch query with QueryCache enabled

lib/mongoid/query_cache.rb, spec/mongoid/query_cache_spec.rb
Limit functionality is broken on the Mongoid query cache because the tests don't actually check that the query results are correct. This PR fixes this issue and modifies the tests to check for it. It will be backported to 7.1 and 7.0.
=> MONGOID-4944 Test that query cache properly uses limits

lib/mongoid/query_cache.rb, spec/lite_spec_helper.rb, spec/mongoid/query_cache_spec.rb, spec/support/session_registry.rb
You can see the tests running in this patch: [https://spruce.mongodb.com/version/5f91d81c0ae606431f650bc7/tasks](https://spruce.mongodb.com/version/5f91d81c0ae606431f650bc7/tasks)
=> MONGOID-4977 (backport): Use recent driver APIs in Mongoid QueryCache for compatibility with sessions & modern retryable reads

lib/mongoid/document.rb, spec/mongoid/document_spec.rb
Fixes https://jira.mongodb.org/browse/MONGOID-5040
=> MONGOID-5040 Revert Document#to_ary to be a private method

.gitmodules
fixes inability of users to update submodules when they do not have an SSH key configured for GitHub
=> use https protocol for spec/shared submodule

lib/mongoid/matcher.rb, spec/mongoid/matcher/extract_attribute_data/traversal.yml
extract_attribute() fails to correctly handle cases with a numeric hash key. When the current code finds a numeric hash key, but sees that 'src' is NOT an array, it returns that the field does not exist.
This PR adds a test case that fails for the old code, and then passes with the new code.
```
1) Matcher.extract_attribute traversal.yml numeric hash key matching the split position has the expected exists flag
Failure/Error: actual[0].should == expected_exists
expected: true
got: false (using ==)
Diff:
@@ -1 +1 @@
-true
+false
2) Matcher.extract_attribute traversal.yml numeric hash key matching the split position has the expected value
Failure/Error: actual[1].should == expected_value
expected: true
got: nil (using ==)
XYZ examples, 2 failures
```
```
XYZ examples, 0 failures
```
=> MONGOID-5063 Support numeric path components when traversing hashes with dot notation in extract_attribute

lib/mongoid/matcher/elem_match.rb, spec/integration/matcher_operator_data/elem_match.yml
`Mongoid::Matcher::ElemMatch.matches?()` didn't consistently convert input keys within its condition to Strings. This PR doesn't include a new unit test verifying this behavior because `ElemMatch` is clearly out of sync with the `k = k.to_s` pattern used in other `lib/Mongoid/matcher/*.rb` files. Existing examples of correctly using `k = k.to_s` in other of these Matcher sub-modules are:
* [expression.rb](https://github.com/mongodb/mongoid/blob/master/lib/mongoid/matcher/expression.rb)
* [field_expression.rb](https://github.com/mongodb/mongoid/blob/master/lib/mongoid/matcher/field_expression.rb)
* [not.rb](https://github.com/mongodb/mongoid/blob/master/lib/mongoid/matcher/not.rb)
=> Fix MONGOID-5068 ElemMatch matcher operates on pre-stringified keys in condition verification path against impossible values

docs/tutorials/mongoid-documents.txt, docs/tutorials/mongoid-upgrade.txt, spec/mongoid/document_fields_spec.rb
If a document has a field with type Regexp, it is still possible to assign strings to this field. In this case the field still should be persisted as regexp.
=> MONGOID-4668 Add test for regexp field

docs/tutorials/mongoid-persistence.txt, docs/tutorials/mongoid-queries.txt, docs/tutorials/mongoid-relations.txt, lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/selectable.rb, lib/mongoid/shardable.rb, spec/integration/associations/embeds_many_spec.rb, spec/mongoid/atomic/paths_spec.rb, spec/mongoid/persistable/deletable_spec.rb, spec/mongoid/persistable/destroyable_spec.rb, spec/mongoid/persistable/upsertable_spec.rb, spec/mongoid/reloadable_spec.rb, spec/mongoid/shardable_spec.rb
=> MONGOID-5078 add tests and documentation pertaining to atomic_selector usage in Mongoid

lib/mongoid/association/accessors.rb, spec/mongoid/document_query_spec.rb
As reported in https://jira.mongodb.org/browse/MONGOID-5116, there's an issue when a record was loaded by a query that was built using `without` and we then try to access a field on one of its embeds.
```ruby
duck = Pet.new(name: 'Duck')
Person.create!(username: 'Dev', title: 'CEO', pet: duck)
person = Person.where(username: 'Dev').without(:title).first
person.pet.name
#! ActiveModel::MissingAttributeError:
#!  Missing attribute: 'name'
```
This is due to the way fields filtering happens as it only accounts for cases where `only` was used.
This PR is a fix that will ignore fields selection if it's only rejecting fields that don't involve the association.
=> Fix MONGOID-5116 Using 'without' breaks access to attributes of embedded documents

lib/mongoid.rb, lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/proxy.rb, lib/mongoid/association/referenced/has_many/enumerable.rb, lib/mongoid/association/referenced/has_many/proxy.rb, lib/mongoid/criteria.rb, lib/mongoid/interceptable.rb, mongoid.gemspec, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/belongs_to/proxy_spec.rb, spec/mongoid/criteria_spec.rb, spec/support/models/address.rb, spec/support/models/person.rb
https://jira.mongodb.org/browse/MONGOID-5123
This PR fixes issues with argument delegation in various versions of Ruby. It also adds some tests to cover cases that are handled differently in different Ruby versions.
=> MONGOID-5123 Fix methods incompatible with Ruby 3

lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/referenced/has_many/proxy.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb
See: https://jira.mongodb.org/projects/MONGOID/issues/MONGOID-5125
Since #4817 `find` can take a block, however this is not used when a has many relation proxy is used. This is a simple change to allow the block to be passed through to the criteria.
Example:
```
class Widget 
has_many :screws
def find_flat_screw 
screws.find { |screw| screw.head == 'flat' }
end
end
```
The find method above will currently return an empty set incorrectly, instead of the first item in the has_many collection
=> MONGOID-5125 find: does not return the correct results for has_many relations

.evergreen/config.yml, gemfiles/driver_oldstable.gemfile, gemfiles/driver_oldstable_jruby.gemfile, gemfiles/driver_stable.gemfile, gemfiles/driver_stable_jruby.gemfile, spec/mongoid/clients/factory_spec.rb, spec/mongoid/clients/options_spec.rb, spec/mongoid/contextual/geo_near_spec.rb, spec/mongoid/persistable/updatable_spec.rb
This PR proposes new structure to our evergreen configurations. We extensively test actual versions using stable version of the driver:
- ruby 2.6 - 3.0
- jruby 9.2
- mongodb 3.6 - 5.0
- rails 5.2 - 6.1
We test all possible combinations of these on all mongodb topologies.
For other versions of components that may be not that actual, but still supported by mongoid (ruby <= 2.5, mongodb <= 3.4, rails 5.1, oldstable and min driver, etc.) we limit number of configurations. 
However, this setup starts 161 tasks on Evergreen for every PR opened. Maybe this is too many, but I am not sure. I am looking forward to your feedback.
=> MONGOID-5118 Add 5.0 configurations to evergreen

docs/release-notes.txt, docs/release-notes/mongoid-7.4.txt, lib/mongoid/document.rb, spec/mongoid/equality_spec.rb
This PR modifies the `===` method override on `Mongoid::Document` classes to just call `is_a?`.
Currently, for a document such as:
```ruby
class User
field :first_name, type: String
end
```
this returns `true`:
```ruby
User === Object
=> true
```
However, the `Object` class is not an instance of `User`, which means it's overriding the expected semantics of `===` for classes (`is_a?`).
This breaks things like `RSpec::Mock`, which uses `===` to determine which class to mock: https://github.com/rspec/rspec-mocks/blob/b1b32716114727a9257e834f0b72015208ca217f/lib/rspec/mocks/space.rb#L108. This causes errors like:
```ruby
allow_any_instance_of(User).to receive(:first_name)
=> RSpec::Mocks::MockExpectationError: Object does not implement: first_name
```
Note this is a …
=> MONGOID-5126 Bring Mongoid::Document's === implementation in alignment with Ruby behavior

lib/mongoid/association/relatable.rb, spec/mongoid/association/referenced/belongs_to_query_spec.rb, spec/mongoid/association/referenced/has_many_models.rb
When an association is defined with the `inverse_of: nil` option, I believe its inverse should not be looked up in any case.
This PR fixes that by skipping the lookup when the option is explicitly defined and set to `nil` but will still let the lookup happen if the option was not specified and is thus `nil`.
I didn't push as to create a `inverse_of_set?` method in the `Options` module as it would not be defined for any other option but I suppose it could make sense.
We actually got a bug while migrating to mongoid 7 where we have the kind of relationship I defined in the spec and due to the way inverse are looked up, trying to get the inverse of `previous_academy` here would return the inverse of `current_academy` and that would in the end cause this error:
``` …
```
=> MONGOID-5149 Skip inverse detection when inverse_of: nil is set

lib/mongoid/contextual/atomic.rb, spec/mongoid/contextual/atomic_spec.rb
Fixes MONGOID-5140
The native MongoDB interface for $unset uses a Hash object rather than an array. Therefore, for consistency, Mongoid should allow a Hash to be the argument to `.unset` in addition to the currently allowed types (String/Symbol/Array)
```
{ $unset: { <field1>: "", ... } }
```
According to [MongoDB's docs](https://docs.mongodb.com/manual/reference/operator/update/unset/):
> The specified value in the $unset expression (i.e. "") does not impact the operation.
So I'm simply taking the Hash keys, even if the value is nil or false.
=> MONGOID-5140 Atomic #unset method should allow Hash args (in addition to current String/Symbol/Array)

docs/reference/queries.txt
Fixes MONGOID-5111
- Documents limit, skip, and batch_size operators
- Add warning to Queries + Persistence section about limit, etc being ignored.
**QUESTION:** Is there a way I can preview these docs--what format are they? I've made this PR without actually seeing a rendered preview, so please check the docs are formatted properly (especially links, etc.)
=> MONGOID-5111 [Documentation Only] Add docs for limit/skip/batch_size

.github/workflows/test.yml
Proposed changed are based on https://github.com/mongodb-labs/drivers-evergreen-tools/blob/master/.evergreen/download-mongodb.sh with an exception for 3.6 (it is available for 18.04, even though not listed in the script).
Unfortunately, we do not have builds of all mongodb versions for all ubuntu versions. So we should not run everything on latest, but be explicit about version.
=> MONGOID-5131 Use proper mdb <-> ubuntu versions

spec/mongoid/document_spec.rb
I suggest removing these tests from Mongoid. There is no code that does something with `_id`. And we agreed that we rely on `bson-ruby` implementation of json serialisation.
=> MONGOId-5185 Remove tests for _id serialization

docs/reference/fields.txt
https://jira.mongodb.com/browse/MONGOID-4592
=> MONGOID-4592 Add examples of using read_attribute and write_attribute to implement custom field behavior

docs/reference/configuration.txt, docs/reference/queries.txt
Adds docs for MONGOID-5144
This PR changes docs only, primarily in queries.txt:
1. Make Query Cache section more compact
2. Make warning about legacy query cache more clear (now near top of section)
3. Make usage of middleware more clear, and make it its own sub-section so that readers don't miss it.
4. Move Query Cache section to end of doc. Right now it's in the middle and flow-wise that doesn't make sense. I've also moved up Scoping by one section by one for flow/readability reasons. The last 3 sections are now:
- Scoping
- Queries + Persistence
- Query Cache
In addition, I have one question. The docs seem to indicate that the legacy query cache does not support non-batched queries (no `GETMORE` support), however the Ruby Driver query cache *can* cache batched queries. Is this the …
=> MONGOID-5144 Improve query cache docs

lib/mongoid/reloadable.rb, spec/mongoid/clients/transactions_spec.rb
The error occurs on the following code: 
```
Band.with_session do |s|
s.start_transaction
label = Label.new(name: "Neil")
b = Band.new(label: label)
b.save!
label.reload
puts b.label # error
s.commit_transaction
end
```
Full class code is in the [MONGOID-5199](https://jira.mongodb.org/browse/MONGOID-5199) ticket.
While investigating this I also noticed another issue:
```
Canvas.with_session do |s|
s.start_transaction
p = Palette.new
c = Canvas.new(palette: p)
c.save!
c.palette = nil
c.palette = p
c.save!
c.reload
expect(c.palette).to_not be_nil # fails
s.commit_transaction
end
=> MONGOID-5199 Reloadable#reload_embedded_document doesn't respect session

spec/integration/matcher_operator_spec.rb, spec/mongoid/attributes/projector_spec.rb, spec/mongoid/matcher/extract_attribute_spec.rb
Change YAML.load to YAML.safe_load as it is the default in Ruby 3.1+. This change only affects specs.
=> MONGOID-5207 Use YAML.safe_load in specs

docs/README.md, docs/reference/fields.txt
**HELP: I cannot create tickets in MongoDB JIRA. When I open "Create Ticket" then press submit, the JIRA server returns 200 but no ticket is made. (I've tried in multiple browsers and with multiple JIRA accounts.) In order to follow ticket process as best as possible, until the issue is resolved I will:**
* **mark Github PRs with `MONGOID-????`**
* **include this message in each affected PR**
---
Documentation only.
In summary:
* `$` and `.` fields (introduced in MongoDB 5.0) are special "hidden fields" that can only be accessed with special "shadow" operators.
* Mongoid query operators / field names will behave as normal post-MongoDB 5.0
* The `field` function will not allow `.` and `$` in field names; Ruby doesn't support such method names anyway.
=> MONGOID-5161 - [Documentation Only] Clarify the policy for working with . and $ named fields which were introduced in MongoDB 5.0

docs/reference/fields.txt, docs/release-notes/mongoid-7.5.txt, lib/config/locales/en.yml, lib/mongoid/fields.rb
Fixes MONGOID-5209
This adds documentation for previously undocumented "Custom Field Options" functionality (`Mongoid::Fields.option`)
I've also improved a number of things for clarity in various places.
This is a precursor to https://github.com/mongodb/mongoid/pull/5119
=> MONGOID-5209 Document "Custom Field Options" functionality + various docs improvements

lib/mongoid/extensions/range.rb, spec/integration/persistence/range_field_spec.rb, spec/mongoid/extensions/range_spec.rb
Fixes MONGOID-5098 (along with #5023 and #5025 which were already merged.)
MongoDB supports `Range` as a storable field type. Currently, when storing a `Range` of `Time` objects, the `Range#mongoize` method does not call `Time#mongoize` on the inner objects.
In addition, this PR improves `Range.mongoize` handling of `Hash` as an input, by removing keys which are unrelated to `Range` and would be junk data in DB. This case is *highly unlikely* to be used in any real-world app, but the existing Mongoid code supports it so we should make it work properly.
(* This PR does NOT add support for endless/beginless ranges; that will be addressed in a separate PR.)
=> MONGOID-5098 Bug fix: Range.mongoize should mongoize its members

lib/mongoid/criteria/queryable/storable.rb, spec/mongoid/criteria_spec.rb, spec/mongoid/scopable_spec.rb, spec/support/models/audible_sound.rb, spec/support/models/sound.rb
Look at the following comment: https://jira.mongodb.org/browse/MONGOID-5204?focusedCommentId=4328701&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-4328701
The functionality after this PR is as follows: 
```
(byebug) Sound.where(active: true)
#<Mongoid::Criteria
selector: {"active"=>true}
options:  {}
class:    Sound
embedded: false>
(byebug) Sound.where(active: true).where(active: true)
#<Mongoid::Criteria
selector: {"active"=>true}
options:  {}
class:    Sound
embedded: false>
(byebug) Sound.where(active: true).where(active: true).where(active:false)
#<Mongoid::Criteria
selector: {"active"=>true, "$and"=>[{"active"=>false}]}
options:  {}
class:    Sound
embedded: false>
(byebug) Sound.where(active: true).where(active: …
```
=> MONGOID-5204 default_scopes duplication, query scope inconsistency

lib/mongoid/stringified_symbol.rb, lib/mongoid/validatable/uniqueness.rb, spec/integration/stringified_symbol_field_spec.rb, spec/support/models/order.rb, spec/support/models/purchased_item.rb
The changes here fix the mongoize in the `create_criteria` method for the uniqueness validator. Previously, the selector was `mongoize`d using `Object`'s `.mongoize` method. This was not type specific, so for the `StringifiedSymbol` type, a `Symbol` was not `mongoize`d into a string. These changes extract the field for the attribute we're trying to `mongoize` and `mongoize` based on the type of that field. 
There is a special case when reading the field from the document for a `localized` field. This field is already `mongoized` by the time it gets to the `create_criteria` function and so I have a special case for it.
MONGOID-5219
=> MONGOID-5219 Uniqueness validation for StringifiedSymbol field in an embedded document fails

docs/reference/configuration.txt, lib/mongoid/config.rb, lib/mongoid/matcher/eq_impl.rb, lib/mongoid/matcher/eq_impl_with_regexp.rb, spec/integration/matcher_spec.rb, spec/mongoid/config_spec.rb
=> MONGOID-5237 Add Feature Flag: _matches? should use millisecond precision when comparing Time objects

docs/reference/compatibility.txt
We should merge this after we release 7.3.4 with Rails 7 supports, to keep the docs consistent over branches.
=> MONGOID-5244 Update compatibility tables

lib/mongoid/document.rb, lib/mongoid/equality.rb, spec/mongoid/equality_spec.rb
There are no additional tests for this change because this change does not have any changes to the functionality of the instance `===` in a practical sense, but changes how we think about it. 
Note that we have multiple `===` functions, one defined for when an instance of a class is on the left hand side (lhs), and one for when a class is on the lhs. I will refer to these as instance `===` and class `===` respectively. 
Previously, the instance `===` operator call `==` if the right hand side (rhs) was another instance, but would call the class `===` if the rhs was a class. Meaning, that if `other` was a class, then we would call `self.class === other`, and since MONGOID-5126, this executes: 
```
other.is_a?(self)
```
Now, since `other` is a class, and we call `===` on `self.class` we end …
=> MONGOID-5257 make === equivalent to ==

.evergreen/run-tests.sh, docs/reference/configuration.txt, docs/release-notes/mongoid-7.4.txt, lib/mongoid/contextual/mongo.rb, lib/mongoid/fields.rb, spec/integration/criteria/alias_query_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/criteria_spec.rb, spec/mongoid/fields_spec.rb, spec/mongoid/interceptable_spec.rb, spec/support/models/label.rb, spec/support/models/passport.rb, spec/support/models/person.rb
I have not written the release notes or docs yet but I'm going to use this as scratch space:
Difference between new and old pluck and distinct:
|                                              | new                                                    | old                                          |
|----------------------------------------------|--------------------------------------------------------|----------------------------------------------|
| callbacks                                    | none                                     | none                                         |
| plucking a localized field                   | "deutsch-text"                                         | {"de"=>"deutsch-text", "en"=>"english-text"} |
| plucking an _translations                    | …
=> MONGOID-5260 Add _translations fields and dot-navigation to pluck and distinct

lib/mongoid/association/referenced/has_and_belongs_to_many/proxy.rb, lib/mongoid/document.rb, lib/mongoid/fields.rb, lib/mongoid/interceptable.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb, spec/mongoid/association/referenced/has_and_belongs_to_many_models.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/interceptable_spec_models.rb, spec/support/models/account.rb
MONGOID-3267
Optional reading: The latest change. After deferring the defaults we had the following case:
```
class Band
has_and_belongs_to_many :songs
field :name
end
class Song
has_and_belongs_to_many :bands
field :_id, type: String, overwrite: true, default: ->{ "#{name}-hello" }
field :band_name, default: -> { bands.first.name if bands.first }
field :favorite_song_id, default: -> { bands.first.song_ids.first if bands.first }
field :name
end
band = Band.create(name: "Molejo")
song = band.songs.create(name: "Cilada")
``` 
The last command yielded the following order of operations:
1. Build a `song` object
2. Defer the callbacks and defaults
3. Push the `song._id` to the band's foreign key (`song_ids`). Note that `song._id` is being set …
=> MONGOID-3267 Allow associations to be used inside defaults

spec/lite_spec_helper.rb, spec/support/spec_config.rb
Fixes MONGOID-5284
The logic `ENV['OS'] == 'Windows_NT' && !RUBY_PLATFORM.match?(/cygwin/)` is borrowed from the [OS gem](https://github.com/rdp/os/blob/master/lib/os.rb#L21).
=> MONGOID-5284 Fix spec helper on Windows

spec/mongoid/association/embedded/embeds_one_models.rb, spec/mongoid/association/embedded/embeds_one_spec.rb
MONGOID-4734 
This is working as intended. I added a test to document it.
=> MONGOID-4734 Test: Updating an association value to object instance when the instance has multiple inverses changes the wrong field

lib/mongoid/association/macros.rb, lib/mongoid/association/referenced/has_and_belongs_to_many.rb, lib/mongoid/attributes/processing.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb, spec/mongoid/association/referenced/has_one/proxy_spec.rb
MONGOID-5089 fixed the aliased_associations hash to include the foreign key field. For example if a `Bag` has_many `Tag`s, there would be an aliased association from `tag_ids => tag`. Before that PR the aliased associations hash would have `nil => tag`. However, this was only done for has_one and has_many associations. This PR fixes this for HABTM associations.
Take the following models:
```
User HABTM Addresses 
User has_many Accounts
User has_one Pet
```
- HABTM: `User.aliased_associations` has `address_ids => addresses`, `Address.aliased_associations` has `user_ids => users`
- has_many: `User.aliased_associations` has `account_ids => accounts`, `Account.aliased_associations`  does not have `user_id`. `Account.aliased_fields` has `user => user_id`.
- has_one: `User.aliased_associations` …
=> Fix MONGOID-5089 HABTM inconsistencies

lib/mongoid/criteria/queryable/extensions/numeric.rb, spec/mongoid/criteria/queryable/extensions/numeric_spec.rb
Fixes MONGOID-5289
This PR contains two performance changes and a bug fix to `__numeric__` method used in Mongoization:
- `.match?` is faster than `=~`
- 50% faster regex which is functionally equivalent to the old one.
- Fixes bugs where `foo.` and `foo.000` both match the current regex.
- Empty string behavior is preserved from existing code.
```ruby
Benchmark.bm do |bm|
bm.report { x.times { '21329.2328'.match?(/(\A[-+]?[0-9]+\z)|(\.0+\z)|(\.\z)/) } }
bm.report { x.times { '21329.2328'.match?(/\A[-+]?[0-9]*[0-9.]0*\z/) } }
end
```
Note that `.` inside `[ ]` doesn't need to be escaped.
=> MONGOID-5289 - Faster Regex for numeric mongoization + bug fixes

docs/reference/configuration.txt, docs/reference/indexes.txt, lib/mongoid/config.rb, lib/rails/generators/mongoid/config/templates/mongoid.yml
Clarify that index background / background_indexing options are deprecated as of MongoDB 4.2
Refer to: https://www.mongodb.com/docs/manual/core/index-creation/#comparison-to-foreground-and-background-builds
=> MONGOID-5318: Documentation: Deprecate "background" index option as per MongoDB 4.2+

spec/integration/associations/has_one_spec.rb
This PR is just for adding a failing test to this ticket for later use
=> MONGOID-3999 Test: Assigning to a belongs_to association overwrites fields in previous association target

lib/mongoid/association/accessors.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/interceptable_spec_models.rb
MONGOID-5306
The `_id`s method uses the `.only` method to get only the `_id`s for an association, which was causing a `MissingAttributeError` to be raised when accessing another association later in the `after_initialize` callback. This was fixed by using `.pluck` over `.only`.
The move from `only` to `pluck` should not have backwards breaking changes, as `pluck` still causes the documents to be "actualized." i.e. during the `pluck`, the `after_initialize` callback that was called (in which the error was raised) during `only`, will also be called during the `pluck`.
=> MONGOID-5306 Use pluck instead of only to avoid projecting when referencing association _ids

docs/release-notes/mongoid-8.0.txt, lib/mongoid/factory.rb
It is not used in the code.
Don't think this one needs documentation in release notes but I'm happy to add it if you'd like.
=> MONGOID-5324 Remove deprecated Mongoid::Factory::TYPE constant

docs/release-notes/mongoid-8.0.txt, lib/mongoid/extensions/date.rb, lib/mongoid/extensions/time.rb
It is not used anywhere.
Don't think this needs to be added to release notes, but happy to add it if you'd like.
=> MONGOID-5324 Remove deprecated EPOCH constant from Date and Time

docs/reference/indexes.txt, docs/release-notes/mongoid-8.0.txt, lib/config/locales/en.yml, lib/mongoid/indexable/specification.rb, lib/mongoid/indexable/validators/options.rb, spec/mongoid/indexable/specification_spec.rb, spec/mongoid/indexable_spec.rb
Mongoid 8.0 supports MongoDB server version 3.6+. `:drop_dups` was removed in MongoDB server version 3.0.
=> MONGOID-5341: Remove :drop_dups option from index macro

docs/reference/configuration.txt, docs/release-notes/mongoid-7.5.txt, docs/release-notes/mongoid-8.0.txt, lib/mongoid/config.rb, lib/mongoid/criteria/queryable/mergeable.rb, lib/mongoid/criteria/queryable/selectable.rb, spec/mongoid/config_spec.rb, spec/mongoid/criteria/queryable/selectable_spec.rb, spec/mongoid/criteria_spec.rb
This PR changes certain functions to combine using $and instead of replacement. For example, given the following query: 
```
Person.gt(age: 2).gt(age: 1)
```
We currently get:
```
{"age"=>{"$gt"=>1}}
```
And we should expect:
```
{"age"=>{"$gt"=>2}, "$and"=>[{"age"=>{"$gt"=>1}}]}
```
Now, I have enumerated the functions below that I believe require this change, and I have also added a list of functions that I believe should not get this change. 
Functions to fix:
- gt
- gte
- lt
- lte
- ne
- near 
- near_sphere 
- eq
- mod
- elem_match
Note that these functions all currently use the ``__override__`` strategy when adding to the criteria.
No longer doing: 
Previously, I thought to not make this change for `eq` and `mod` for the following reason:
> The logic behind the list of functions to …
=> MONGOID-5330 Operator methods overwrite previous conditions

lib/config/locales/en.yml, spec/mongoid/validatable/uniqueness_spec.rb
Changes value to `mongoid.errors.taken` to match Rails-I18n gem and ActiveRecord:
```
OLD: "is already taken"
NEW: "has already been taken"
```
=> MONGOID-5353: I18n: Change "taken" error message text to match I18n/ActiveRecord

lib/mongoid/association/embedded/batchable.rb, lib/mongoid/atomic/paths/embedded/many.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/embedded/embeds_many_models.rb
MONGOID-5352
Should we backport this to 7.3-stable and 7.4-stable?
CI failure are unrelated and appear on other PRs
=> MONGOID-5352 assign_attributes is working incorrectly since 7.3.4

lib/config/locales/en.yml, lib/mongoid/errors/document_not_found.rb, lib/mongoid/reloadable.rb, spec/mongoid/errors/document_not_found_spec.rb
```
message:
Document not found for class Foo with id 6290f569d1327a17ddfb7ed8 and shard key a: 538.
summary:
When calling Foo.find with an id and a shard key, each parameter must match a document in the database or this error will be raised. The search was for the id: 6290f569d1327a17ddfb7ed8 with shard_key: a: 538 and it was not found.
resolution:
Search for an id/shard key that is in the database or set the Mongoid.raise_not_found_error configuration option to false, which will cause a nil to be returned instead of raising this error when searching for a single document.
```
=> MONGOID-5077 DocumentNotFound message fails to account for shard key

lib/mongoid/association/referenced/has_and_belongs_to_many/proxy.rb, spec/mongoid/association/syncable_spec.rb
MONGOID-4520 
The idea here is that we don't always want to clear the value for the foreign key in the `changed_attributes` hash. There is a situation, when setting the foreign key of a HABTM association on an unpersisted model, when you want the `changed_attributes` hash to contain a value for the foreign key, since:
1) it entered the << method with a value for the foreign key already
2) it is used later in the Syncable module to update the inverse foreign keys
Note that this doesn't really change MONGOID-4843, and all of the tests there still pass after these changes. The core of that ticket was clearing the changes caused by the `reset_unloaded` method and shouldn't necessarily have been getting rid of all presence of the foreign key value in the `changed_attributes` hash. 
Also note …
=> MONGOID-4520 Set inverse keys on HABTM relationship when subsequently persisting document

docs/reference/aggregation.txt, docs/working-with-data.txt
This is a redux of my changes from https://github.com/mongodb/mongoid/pull/5308. It basically adds an intro section to the Aggregation Pipeline docs page, since its a standalone, along with a few small fixes.
I haven't changed any links and manually tested that all the links I could find work.
=> MONGOID-5369 - Improvements to the Aggregation Pipeline doc page

docs/release-notes/mongoid-8.0.txt, lib/mongoid/contextual/memory.rb, spec/mongoid/contextual/memory_spec.rb
Fixes MONGOID-5390
Conveniently, we can now use ActiveSupport's `Array#pluck` here, which was introduced in Rails 5.0.
The #pluck method was also missing a doc comment, so I added it.
In addition, the original method called `Array.wrap(fields)`. However, this had no useful effect. If the method was called with a first-arg Array like `pluck([:a, :b])`, then `Array.wrap(fields) #=> [[:a, :b]]`, which is non-sensical. So I've removed this call.
Lastly, I don't think we need to have a feature flag here. Refer to MONGOID-5390 JIRA ticket for details.
=> MONGOID-5390: Mongoid::Contextual::Memory#pluck should return nil values

docs/reference/queries.txt, docs/release-notes/mongoid-7.5.txt, lib/config/locales/en.yml, lib/mongoid/contextual/memory.rb, lib/mongoid/contextual/mongo.rb, lib/mongoid/contextual/none.rb, lib/mongoid/errors/document_not_found.rb, lib/mongoid/findable.rb, spec/mongoid/contextual/memory_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/contextual/none_spec.rb, spec/mongoid/errors/document_not_found_spec.rb
A decision I made here is that `take` should return documents instead of a criteria. This draws a distinction between `take` and `limit`, as well as I think it would be a little strange if we returned a criteria on just `Person.take` (i.e. without params) since only one document is returned.
TODO:
- memory
- none
- release note
- crud documentation
=> MONGOID-4547 Implement #take / #take! for AR feature parity

lib/mongoid/contextual/memory.rb, lib/mongoid/contextual/mongo.rb, lib/mongoid/contextual/none.rb
This contains a few things I missed in code review of #5344
1. Remove unused variable `k` in `Contextual::Mongo#extract_value`
2. Add missing code comment for `Contextual::Memory#tally`
3. Minor code comment fixes
=> MONGOID-5270: Follow-ups to tally PR

lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/contextual/aggregable/memory.rb, lib/mongoid/contextual/memory.rb, lib/mongoid/validatable/uniqueness.rb
Upon investigation, the issue described in MONGOID-5376 seems only to affect cases which are loaded in Ruby's memory (including embeds many). I couldn't find any example of calling .count on the DB itself; I think we already fixed a few of those cases in the past.
=> MONGOID-5376: Use exists? or any? instead of count to determine existence of any document

lib/config/locales/en.yml, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/criteria_spec.rb, spec/mongoid/findable_spec.rb
Ruby is nil is like Highlander: "There can only be one."
```ruby
nil.object_id       #=> 8
nil.dup.object_id   #=> 8
foo = []
foo.object_id       #=> 106240
foo.dup.object_id   #=> 117020
```
=> MONGOID-5420: "a nil" --> "nil" in various places

docs/reference/persistence-configuration.txt
Documentation only. This syntax changed in Rails 4.
(I checked all the docs but these are the only usages I found)
=> MONGOID-4992 - Fix Rails syntax in docs

lib/config/locales/en.yml, spec/mongoid/errors/no_environment_spec.rb
- Clarify RAILS_ENV, MONGOID_ENV must be set in ENV.
- Cleanup error language while we're here (e.g. "resolution" section contained info that belongs in "summary", etc.)
=> MONGOID-4829: Clarify RAILS_ENV, MONGOID_ENV must be set in ENV

docs/release-notes/mongoid-8.0.txt, lib/config/locales/en.yml, lib/mongoid/indexable/validators/options.rb, spec/mongoid/indexable_spec.rb
These options were deprecated in Ruby driver version 2.13.0
There is no mention of `geoSearch` in Mongoid.
=> MONGOID-4867 Deprecate geoHaystack and geoSearch

docs/reference/queries.txt, docs/release-notes/mongoid-7.5.txt, lib/mongoid.rb, lib/mongoid/association/referenced/has_many/enumerable.rb, lib/mongoid/contextual/memory.rb, lib/mongoid/contextual/mongo.rb, lib/mongoid/contextual/none.rb, lib/mongoid/findable.rb, lib/mongoid/warnings.rb, spec/mongoid/association/referenced/has_many/enumerable_spec.rb, spec/mongoid/contextual/memory_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/contextual/none_spec.rb, spec/mongoid/findable_spec.rb
PLEASE READ THIS before reviewing this PR. There's a lot going on here, and a lot still left to do.
First, this change is actually a few different changes wrapped in one (besides all of the #take stuff under it):
1) remove support for the `id_sort` option
2) add support for the `limit` option 
3) add support for passing options in all of our first/last methods, so that users don't get errors when they pass in options to different first/lasts. Note that our syntax differs from Ruby's. We use keyword args (well actually, a hash) whereas Ruby uses an optional arg to pass the limit. This is annoying, but I fear it would be too complicated to completely do away with the hash in favor of just a limit integer. 
Things still left to do:
- Release notes about changes to first/last
- Deprecate the …
=> MONGOID-4998 deprecate :id_sort and implement limit positional argument on #first/#last

docs/reference/fields.txt, docs/release-notes/mongoid-8.0.txt, lib/mongoid/extensions/date.rb, lib/mongoid/extensions/time.rb, spec/mongoid/extensions/date_spec.rb, spec/mongoid/extensions/date_time_spec.rb, spec/mongoid/extensions/time_spec.rb
I've decided to just use the String#__mongoize_time__ method to parse strings as it takes care of parsing the time in the configured time zone. The following outcomes result: 
- If given a string without a timezone, it is interpreted in the current configured time zone
- When given a string with a timezone, it is interpreted in that time zone, and then converted to the configured time zone
- Time/ActiveSupport::TimeWithZone correctly returned based on flag
=> MONGOID-5315 Accept formatted strings in Date/Time/DateTime.demongoize

lib/mongoid/contextual/aggregable/memory.rb, spec/mongoid/contextual/aggregable/memory_spec.rb, spec/mongoid/contextual/aggregable/memory_table.yml, spec/mongoid/contextual/aggregable/memory_table_spec.rb, spec/support/models/band.rb
This change makes the in-memory behavior closer to MongoDB's native operators.
This PR is a pared-back version of https://github.com/mongodb/mongoid/pull/5038 which contains only nil changes and not type conversion. I hope this can be merged.
=> MONGOID-4500 Mongoid::Contextual::Aggregable::Memory should ignore nil values.

docs/release-notes/mongoid-8.0.txt, lib/mongoid/contextual/mongo.rb, lib/mongoid/criteria.rb, lib/mongoid/warnings.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/criteria_spec.rb, spec/support/macros.rb
MONGOID-5414
This PR keeps the cache and cached? methods but removes all of their functionality. Do you think it would be better to remove these methods outright and put a warning in 7.5?
The failing distros are driver min, which will stop failing once we merge MONGOID-5429
=> MONGOID-5414 deprecate criteria cache functionality

docs/reference/fields.txt, spec/mongoid/extensions/string_spec.rb, spec/mongoid/extensions/time_spec.rb
MONGOID-5425
Some things to note:
- Time always mongoizes to utc. It seems like we only store dates in the db as UTC
- I didn't write expansive DateTime tests because DateTime just calls the Time.(de)mongoize methods
- I didn't write Date tests, because as far as I can tell Dates aren't affected by time zones: 
```
irb(main):005:0> Date.parse("2022-07-11 14:03:42 +1500")
=> Mon, 11 Jul 2022
irb(main):006:0> Date.parse("2022-07-11 14:03:42 -1500")
=> Mon, 11 Jul 2022
```
=> MONGOID-5425 Verify string mongoization into Date, Time, DateTime with time zones

lib/mongoid/contextual/mongo.rb, spec/mongoid/contextual/mongo_spec.rb, spec/support/macros.rb
Originally this method was cached because, before the view options were fixed to be passed into the count method, it was impossible to pass options into length. Now that it is possible to pass options into length, the following case would cause stale results to be returned:
```
crit = Band.all
crit.limit(5).length 
crit.limit(3).length
```
This is incorrect, and so I removed the caching from this method. 
The caching would get delegated to the query cache, but it seems like no caching is done on agg pipelines, which is what appears to be performed underneath the call to count.
=> MONGOID-5414 Remove caching on Mongoid::Contextual::Mongo#length

lib/mongoid/equality.rb, spec/mongoid/equality_spec.rb
This is obviously a hugely breaking change. I'm not sure how we want to proceed with this. 
This is a problem on: master, 8.0-stable, 7.5-stable and 7.4-stable
#5172 incorrectly changed this.
=> MONGOID-5436 switch the meaning of legacy_triple_equals

lib/mongoid/cacheable.rb, spec/mongoid/cacheable_spec.rb
I think that if we backport this to 7.3 we shouldn't have any problems in the future. 7.3 is the last version that supports Rails 7.
MONGOID-5433
=> MONGOID-5433 Replace calls of Time#to_s(format) with Time#to_formatted_s

docs/contributing.txt, docs/contributing/code-documentation.txt, docs/index.txt
This adds a new "Contributing" section to the top-level of docs, with a single page "Code Documentation" in this PR.
(Contributing section was also requested in [MONGOID-5082](https://jira.mongodb.org/browse/MONGOID-5082). Not sure if this would be better to add to Ruby Driver rather than Mongoid.)
Comments/opinions/etc. welcome. This PR can be merged anytime.
Things to add in future:
=> MONGOID-5415 Docs: Add code documentation guidelines

docs/release-notes/mongoid-7.5.txt
We did this in Mongoid 7.4's release notes.
Please note that as per https://jira.mongodb.org/browse/MONGOID-5452, `legacy_attributes` appears to be missing from Mongoid 7.5, although it is in the release notes.
=> MONGOID-5451: Add feature flag summary for Mongoid 7.5

docs/reference/configuration.txt, docs/release-notes/mongoid-7.5.txt, lib/mongoid/config.rb, lib/mongoid/document.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb, spec/mongoid/attributes_spec.rb, spec/mongoid/config_spec.rb
This is a cherry pick of MONGOID-5365 to add the `legacy_attributes` feature flag to 7.5. I have modified the docs to have the correct defaults for this version.
=> MONGOID-5452 add legacy_attributes to 7.5

lib/mongoid/fields/localized.rb, spec/mongoid/fields/localized_spec.rb
Only use case would be if the user modified the translations hash directly, but there were already some places that checked for both string and symbol keys so I just made it work in fallbacks too.
=> MONGOID-5334 ensure localized demongoization works with symbol keys

docs/release-notes/mongoid-8.0.txt
Correct default legacy_attributes Mongoid 8.0 release notes (should be "false" as per the actual code.)
@Neilshweky
=> MONGOID-5451: Correct default legacy_attributes Mongoid 8.0 release notes

docs/release-notes/mongoid-8.1.txt, lib/mongoid/changeable.rb, spec/integration/callbacks_spec.rb, spec/mongoid/changeable_spec.rb
https://jira.mongodb.org/browse/MONGOID-4528
=> MONGOID-4528 Add more dirty methods

lib/mongoid/config/defaults.rb, spec/mongoid/config/defaults_spec.rb
Once we've back ported `legacy_attributes` to 7.5, the defaults for 7.4 should have `legacy_attributes` true, and 7.5 should have `legacy_attributes` false (as per the current default).
=> MONGOID-5293 put legacy_attributes in 7.5 defaults

docs/reference/crud.txt, docs/reference/queries.txt, docs/release-notes/mongoid-9.0.txt, lib/config/locales/en.yml, lib/mongoid/association/accessors.rb, lib/mongoid/attributes.rb, lib/mongoid/errors.rb, lib/mongoid/errors/attribute_not_loaded.rb, spec/mongoid/association/accessors_spec.rb, spec/mongoid/association/embedded/embeds_many_query_spec.rb, spec/mongoid/association/embedded/embeds_one_query_spec.rb, spec/mongoid/association/referenced/belongs_to_query_spec.rb, spec/mongoid/association/referenced/has_and_belongs_to_many_query_spec.rb, spec/mongoid/association/referenced/has_many_query_spec.rb, spec/mongoid/association/referenced/has_one_query_spec.rb, spec/mongoid/attributes_spec.rb, spec/mongoid/criteria_projection_spec.rb, spec/mongoid/document_query_spec.rb, spec/mongoid/errors/attribute_not_loaded_spec.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/persistable/savable_spec.rb, spec/mongoid/persistable/settable_spec.rb, spec/mongoid/persistable/updatable_spec.rb
This an alternate implementation of MONGOID-5320 than the one in https://github.com/mongodb/mongoid/pull/5360. **I prefer to merge this one if possible.**
In this PR, I've simply changed ActiveModel::MissingAttributeError to Mongoid::Errors:AttributeNotLoaded which inherits MongoidError, and added a release note for Mongoid 9.0.
In the other PR, I made the same error inherit ActiveModel::MissingAttributeError. Pick your poison.
=> MONGOID-5467 MONGOID-5320 Change usage of ActiveModel::MissingAttributeError to Mongoid::Errors:AttributeNotLoaded

docs/contributing/code-documentation.txt, lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/macros.rb, lib/mongoid/association/referenced/has_many/proxy.rb, lib/mongoid/criteria.rb, lib/mongoid/extensions/module.rb, lib/mongoid/fields.rb
Includes an update to the docs page, including a few unrelated items to docs like `@raise` and `@todo` which are both used currently in the codebase.
=> MONGOID-5415: Code docs for blocks should use @yield

lib/mongoid/association/referenced/has_and_belongs_to_many.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/buildable_spec.rb
There is no behavior change here, as no query was being executed anyway (as per this [line](https://github.com/mongodb/mongoid/blob/master/lib/mongoid/association/referenced/has_many/enumerable.rb#L484))... I wouldn't mind closing this as won't do, or if we want to do this because it's cleaner. 
MONGOID-5164
=> MONGOID-5164 Use None criteria instead of $in with empty list in HABTM association

lib/mongoid/criteria/queryable/extensions/big_decimal.rb, spec/mongoid/criteria/queryable/extensions/big_decimal_spec.rb, spec/mongoid/criteria_spec.rb
Refer to MONGOID-5484
Note the logic in this PR correctly respects `Mongoid.map_big_decimal_to_decimal128`
- When false, BigDecimal is queried as string.
- When true, strings are evolved to Decimal128.
=> MONGOID-5484 - Bugfix: Numeric strings should correctly evolve into BigDecimal (i.e. respecting map_big_decimal_to_decimal128)

docs/release-notes/mongoid-9.0.txt, lib/mongoid/criteria/queryable/extensions/date.rb, spec/mongoid/criteria/queryable/extensions/date_spec.rb
Currently `Date#__evolve_time__` uses "local" (not "UTC") which is not affected by Mongoid configuration.
This PR changes it to correct respect the `Mongoid.use_activesupport_time_zone` setting.
Refer to MONGOID-5488
=> MONGOID-5488 - Bugfix: Date#__evolve_time__ should use the configured zone instead of Time.local (i.e. respecting Mongoid.use_activesupport_time_zone)

docs/reference/queries.txt, docs/release-notes/mongoid-8.1.txt, lib/mongoid/contextual/memory.rb, lib/mongoid/contextual/mongo.rb, lib/mongoid/contextual/none.rb, lib/mongoid/findable.rb, spec/mongoid/contextual/memory_spec.rb, spec/mongoid/contextual/mongo_spec.rb
`#exists?` now takes a number of argument types:
- `Hash`: A hash of conditions.
- `Object`: An _id to search for.
- ``false``/``nil``: Always returns false.
I've decided to follow Rails' lead on `nil`/`false`... automatically returning `false` on `nil` makes sense, since in actuality what you're doing is checking for a `nil` or `false` _id. If that returned true, it would make no sense.
=> MONGOID-5100 allow selector arguments for .exists?

docs/release-notes/mongoid-9.0.txt, lib/mongoid/association/options.rb, lib/mongoid/atomic.rb, lib/mongoid/touchable.rb, spec/integration/callbacks_models.rb, spec/mongoid/touchable_spec.rb, spec/mongoid/touchable_spec_models.rb
Fixes MONGOID-5142
Fixes MONGOID-5274
Correct fix for MONGOID-5136 (the previous one was non-optimal)
Replaces PR https://github.com/mongodb/mongoid/pull/5039 (includes specs from it, which are passing here)
- Perform all touch operations on the document in a single write operation (MONGOID-5142)
- Remove touches from the atomic set operations, so that they are no longer there when saving the next time.
- Cleanup/refactor touch method to be much more readable. The code is also now symmetrical for parents and child docs, everything is nicely recursive.
=> MONGOID-5274 / MONGOID-5142 - Rework #touch with embedded documents

docs/reference/associations.txt, docs/release-notes/mongoid-8.1.txt, lib/mongoid/association/embedded/batchable.rb, lib/mongoid/association/embedded/embedded_in/buildable.rb, lib/mongoid/association/embedded/embedded_in/proxy.rb, lib/mongoid/association/embedded/embeds_many/buildable.rb, lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/embedded/embeds_one/buildable.rb, lib/mongoid/association/embedded/embeds_one/proxy.rb, spec/mongoid/association/embedded/embedded_in/proxy_spec.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/embedded/embeds_one/proxy_spec.rb, spec/support/models/artist.rb, spec/support/models/building.rb
Turns out this only works for embedded associations (but not `embedded_in` until this PR), but they cannot possible work for referenced associations, since any non document assigned to a referenced association is interpreted as a queryable item for retrieving the base document. 
I don't think we need to add this functionality for referenced association, and we know that referenced and embedded associations are not the same.
=> MONGOID-5331 Document hash assignment to associations

docs/tutorials.txt, docs/tutorials/getting-started-rails6.txt, docs/tutorials/getting-started-rails7.txt
This PR clones and updates the existing tutorial for Rails 7 while labelling the old tutorial as being for Rails 6.
=> MONGOID-5496: Update Getting Started (Rails) tutorial for Rails 7

docs/reference/queries.txt, docs/release-notes/mongoid-8.1.txt, lib/mongoid/criteria/queryable/selectable.rb, spec/mongoid/criteria/queryable/selectable_logical_spec.rb
Jira: https://jira.mongodb.org/browse/MONGOID-5453
This adds a new query method, `#none_of`, which works as the opposite of `#any_of`. It will wrap all of the criteria it is given in a `$nor` operator.
=> MONGOID-5453 Add .none_of query method

lib/mongoid/contextual/mongo.rb, spec/mongoid/contextual/mongo_spec.rb
`Mongo#first` and `Mongo#last` are trying to interpret the argument as either nil, an integer, or a Hash. When checking to see if the argument might be a Hash with the `:id_sort` key, the code uses `Hash#fetch`, which raises an exception if the requested key does not exist. This meant that passing an empty hash to these methods caused problems.
This PR gives those functions explicit `limit` (nil or Integer) and `opts` (Hash) values, extracted from the argument, which makes it easier to test for the `:id_sort` key without requiring it to be present.
=> MONGOID-5546 First/Last failures when empty hash passed as criteria

lib/mongoid/contextual/atomic.rb
This method should have been removed when the current_date code was removed.
Original ticket: https://jira.mongodb.org/browse/MONGOID-5442
=> Clean up a method that was missed in in #5521

mongoid.gemspec
Mongoid was previously restricting concurrent-ruby versions to be < 1.2. This caused problems recently in evergreen with the release of concurrent-ruby 1.2.0. There do not appear to be any incompatibilities in 1.2.0, so it should be okay to be more permissive with which concurrent-ruby versions we support.
=> Allow concurrent-ruby versions >= 1.2

docs/release-notes/mongoid-9.0.txt, lib/mongoid/touchable.rb, spec/mongoid/touchable_spec.rb
While working on https://jira.mongodb.org/browse/MONGOID-5504, I realized that `touch` method leaves the object in the changes state:
```ruby
band = Band.create!
band.changed? # => false
band.update(name: 'John')
band.changed? # => false
band.touch
band.changed? # => true
band.changes # => {"updated_at"=>[2023-01-30 13:12:57.477191135 UTC, 2023-01-30 13:13:11.482975646 UTC]}
```
This leads to the problem described in https://jira.mongodb.org/browse/MONGOID-5504.
This behavior seems to be as designed - https://github.com/mongodb/mongoid/blob/master/spec/mongoid/touchable_spec.rb#L258. However, I believe that this behavior should be changed to be consistent with other updating operations.
=> MONGOID-5504 Clear changes after :touch

lib/mongoid/config.rb, lib/mongoid/config/introspection.rb, lib/rails/generators/mongoid/config/templates/mongoid.yml, spec/integration/app_spec.rb, spec/mongoid/config/introspection_spec.rb
The `mongoid.yml` template previously contained the same content as the comments in `Mongoid::Config`. This PR introduces an introspection mechanism that scrapes the `Mongoid::Config` module and extracts the comments for each of the options. The `mongoid.yml` template then uses that information to build the option list that users can choose from.
=> MONGOID-5555 Avoid duplicating option documentation

spec/integration/app_spec.rb, spec/support/spec_config.rb
When running `app_spec.rb` locally, if you have Rails 7+ installed, the spec fails because the wrong `rails` script is used to run `rails new`.
Also, if `MONGODB_URI` is not set, a parse error occurs in `app_spec.rb` because the `write_mongoid_yml` method expects `SpecConfig#safe_uri` to return a valid mongodb URI, which it does not if MONGODB_URI is not set. I've refactored that logic a bit in SpecConfig to make it work more robustly when that environment variable is not set.
=> MONGOID-5566 fix breaking app_spec.rb when run locally

lib/mongoid/persistable/deletable.rb, lib/mongoid/persistable/destroyable.rb, spec/mongoid/persistable/deletable_spec.rb, spec/mongoid/persistable/destroyable_spec.rb
The `#destroy!` (bang) method takes `options = {}` as an arg, but does not pass them to `#destroy` (non-bang). This looks unintentional.
The options here look like they are intended to be used internally, but they do exist on the public interface, so they should be documented and tested.
This PR adds spec coverage for `#delete`, `#destroy`, and `#destroy!` `:persist` and `:suppress` options.
=> [READY FOR REVIEW] MONGOID-5571 Fix options arg in #destroy! being ignored + specs

.github/workflows/test.yml, spec/mongoid/clients_spec.rb, spec/spec_helper.rb
For some reason ruby 2.6 and jruby 9.3 configurations of github actions install an ancient version of actionpack (1.4). This situation is not reproducible neither on evergreen or locally. Therefore, it must be a GH actions issue.
Since we have coverage for these ruby versions on evergreen, it seems safe to remove them from GH actions.
This PR also reduces the amount of GH actions tasks and introduces mongodb 6.0.
=> MONGOID-5565 Remove Ruby 2.6 from GH Actions

docs/release-notes/mongoid-9.0.txt, lib/mongoid/association/accessors.rb, lib/mongoid/association/embedded/embedded_in.rb, lib/mongoid/association/embedded/embeds_one/proxy.rb, lib/mongoid/attributes/processing.rb, lib/mongoid/persistable/updatable.rb, lib/mongoid/touchable.rb, spec/integration/associations/embedded_spec.rb, spec/mongoid/association/embedded/embedded_in_spec.rb, spec/mongoid/association/embedded/embeds_many_models.rb, spec/mongoid/association/embedded/embeds_one_models.rb, spec/mongoid/touchable_spec.rb, spec/support/models/favorite.rb
This PR changes the default for the `embedded_in` relation from `touch: false` to `touch: true`, meaning that changing a subdocument will result in the parent being touched.
This resulted in a surprising number of broken tests, and most surprisingly, revealed a couple of bugs, as well, both of which have been addressed in this PR.
The first bug was a result of the `_descendants` list being memoized when first referenced. Given a system of models, and a series of operations like the following:
```ruby
class Person
include Mongoid::Timestamps
field :name, type: String
embeds_one :hometown
end
class Hometown
include Mongoid::Timestamps
field :name, type: String
embedded_in :person
end
bob = Person.create(name: "Bob")
home = …
```
=> MONGOID-5016 default embedded touch to true

lib/mongoid/extensions.rb
This hack can be removed as Mongoid requires Rails 5.1+ and the issue was fixed in Mongoid 5.0.
See: https://github.com/rails/rails/pull/24517
Should be fine to merge if tests pass.
=> MONGOID-5562 Remove BSON::Document#transform_keys hack

.github/workflows/test.yml
This fixes the following failure in Github Actions CI by using `ubuntu-20.04` OS everywhere.
The failure happened suddenly as it looks like either the `setup_ruby/v1` task or the CI itself dropped support for `ubuntu-18.04`
```
Error: Unsupported platform ubuntu-18.04
at Module.getAvailableVersions (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:67995:[11](https://github.com/mongodb/mongoid/actions/runs/4297541531/jobs/7490639287#step:4:12))
at setupRuby (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:68802:36)
at run (/home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:68771:11)
at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:68936:40
at /home/runner/work/_actions/ruby/setup-ruby/v1/dist/index.js:68938:3
at Object.<anonymous> …
```
=> [READY FOR REVIEW] MONGOID-5542 - Fix Github Actions unsupported Ubuntu version

lib/mongoid/config.rb
This PR fixes deprecation warning logic to work correctly on Ruby 2.7 and earlier. PR #5489 didn't support it correctly for Ruby <= 2.7, and as a result Ruby 2.7/2.6 specs are failing on `8.1-stable` branch.
As you can see in the PR, there are differences in Ruby 2.7 and earlier handle `Module#prepend` on modules. I've intentionally done if/else for the different Ruby versions so it will be easy to cleanup in the future.
=> MONGOID-5509 Fix deprecation logic broken on Ruby <= 2.7 on 8.1-stable branch

lib/mongoid/shardable.rb, spec/mongoid/shardable_models.rb, spec/mongoid/shardable_spec.rb
If a shard key referenced a field in an embedded document, Mongoid was incorrectly retrieving the value of that field when building the shard key selector. This PR properly parses and evaluates such shard keys.
See: https://jira.mongodb.org/browse/MONGOID-5582
=> MONGOID-5582 Correctly interpret shard keys in embedded documents

lib/mongoid/shardable.rb, spec/mongoid/shardable_models.rb, spec/mongoid/shardable_spec.rb
This ports the shard-key processing code from #5576 to 8.1-stable.
See: https://jira.mongodb.org/browse/MONGOID-5582
=> MONGOID-5582 port more robust shard-key processing to 8.1-stable

lib/mongoid/shardable.rb, spec/mongoid/shardable_models.rb, spec/mongoid/shardable_spec.rb
This ports the improved shard key processing from #5576 to 8.0-stable.
See: https://jira.mongodb.org/browse/MONGOID-5582
=> MONGOID-5582 port more robust shard key processing to 8.0

lib/mongoid/shardable.rb, spec/mongoid/shardable_models.rb, spec/mongoid/shardable_spec.rb
Ports the improved shard key processing from #5576 to 7.5-stable.
See: https://jira.mongodb.org/browse/MONGOID-5582
=> MONGOID-5582 port more robust shard key processing to 7.5

lib/mongoid/composable.rb, lib/mongoid/config.rb, lib/mongoid/config/encryption.rb, lib/mongoid/encryptable.rb, lib/mongoid/fields.rb, lib/mongoid/fields/encrypted.rb, lib/mongoid/fields/validators/macro.rb, spec/mongoid/config/config_spec_models.rb, spec/mongoid/config/encryption_spec.rb
This is the first PR in the series that adds support of CSFLE to Mongoid.
In this PR we implement only CSFLE schema generation from Mongoid documents. For more information about the schema syntax see https://www.mongodb.com/docs/manual/core/csfle/reference/encryption-schemas/
Schemas generated in the tests are for now manually tested with the Ruby driver. In the upcoming PRs we will implement configuring client(s) with the schema; it will allow us to add proper testing.
=> MONGOID-5585 Declare FLE schema in Mongoid document

docs/reference/sharding.txt
MONGOID-5582 updated Mongoid so that shard keys with "." in them are treated as delimited fields identifying attributes of embedded subdocuments. This precludes the possibility of using shard keys that literally contain the "." character. Since we've decided this design decision is acceptable, this PR updates the sharding documentation for Mongoid to mention this caveat.
Once accepted, I'll backport this PR to 7.5-stable, 8.0-stable, and 8.1-stable (which were also updated for MONGOID-5582).
ref: https://jira.mongodb.org/browse/MONGOID-5590
=> MONGOID-5590 Update sharding docs re: keys with "." characters in them

docs/reference/sharding.txt
This PR backports #5588 to 7.5-stable.
ref: https://jira.mongodb.org/browse/MONGOID-5590
=> MONGOID-5590 Backport sharding doc updates to 7.5-stable

docs/reference/sharding.txt
This PR backports https://github.com/mongodb/mongoid/pull/5588 to 8.0-stable.
ref: https://jira.mongodb.org/browse/MONGOID-5590
=> MONGOID-5590 Backport sharding doc updates to 8.0-stable

docs/reference/sharding.txt
This PR backports https://github.com/mongodb/mongoid/pull/5588 to 8.1-stable.
ref: https://jira.mongodb.org/browse/MONGOID-5590
=> MONGOID-5590 Backport sharding doc updates to 8.1-stable

lib/mongoid/contextual/mongo.rb, spec/mongoid/contextual/mongo_spec.rb
This allows callers to adjust any available `explain` options, as documented here:
https://www.mongodb.com/docs/ruby-driver/master/api/Mongo/Collection/View/Explainable.html
=> MONGOID-5595 Forward explain options to driver

spec/mongoid/clients/options_spec.rb
This spec seems to be failing about 1 out of every 10 times, even with 3 retries. I've changed to preserve the spirit of the test in the way that doesn't fail--ran it 1000 times without retries and it worked every time.
=> MONGOID-5598 Fix transient spec failure

lib/mongoid/document.rb, lib/mongoid/factory.rb, lib/mongoid/threaded.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb
When MONGOID-2586 landed, it made it so that a model's `initialize` method would not be called in certain circumstances, including when calling `build` on a child collection. This PR corrects that specific case (though there are other circumstances where `initialize` is still not called, typically via the `Factory` methods).
ref https://jira.mongodb.org/browse/MONGOID-5600
=> MONGOID-5600 make sure build calls initialize

lib/mongoid/document.rb, lib/mongoid/factory.rb, lib/mongoid/threaded.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb
[MONGOID-5600](https://jira.mongodb.org/browse/MONGOID-5600) fixes the initialize method not being called when creating records via foo.bars.build. This PR backports those changes to the 8.1-stable branch.
=> MONGOID-5600 Backport to 8.1-stable

lib/mongoid/persistable.rb
Should never rescue Exception because its used for things like sigkill.
=> MONGOID-5607: Rescue StandardError instead of Exception

docs/reference/configuration.txt
Update forking guidance examples to test if `Mongoid` is `defined?` to ensure these examples don't fail when run in environments where Mongoid may not have been preloaded (ex: development environments)
=> MONGOID-5514: Improve forking guidance

lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/referenced/has_and_belongs_to_many/proxy.rb, lib/mongoid/association/referenced/has_many/proxy.rb, lib/mongoid/threaded.rb, lib/mongoid/traversable.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb, spec/mongoid/attributes_spec.rb
This backports the changes to `delete_one` in MONGOID-5560 to the 8.1-stable branch.
=> MONGOID-5620 backport MONGOID-5560 to 8.1-stable

lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/referenced/has_and_belongs_to_many/proxy.rb, lib/mongoid/association/referenced/has_many/proxy.rb, lib/mongoid/threaded.rb, lib/mongoid/traversable.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb, spec/mongoid/attributes_spec.rb
This backports the `delete_one` change in RUBY-5560 to 8.0-stable.
=> MONGOID-5620 backport MONGOID-5560 to 8.0-stable

docs/reference/queries.txt
The server will optimize a single-value `$in` to an `$eq` so there's no harm in leaving the functionality in Mongoid but just removing the deprecation not.
=> MONGOID-5465: remove deprecation from docs regarding single-value $in

docs/release-notes/mongoid-8.1.txt
The release notes for 8.1 say only that the feature should be `on` or `off`, which can be assumed to mean `true` or `false`, but we should be more explicit about that.
(Note: this needs to be backported to 8.1-stable.)
=> MONGOID-5489 note explicit default values for legacy_readonly

docs/release-notes/mongoid-8.1.txt
This backports the wording change in the 8.1 release notes, relative to true/false values on the `legacy_readonly` setting.
=> MONGOID-5489 backport to 8.1

lib/mongoid/atomic.rb, lib/mongoid/changeable.rb, lib/mongoid/reloadable.rb, spec/mongoid/reloadable_spec.rb, spec/mongoid_spec.rb
This backports #5656 from master to 8.0-stable.
> Reloading a document was not resetting the atomic operation state, which meant the reloaded might object might still believe there were changes to persist. This makes sure that state is reset on reload.
> ref: https://jira.mongodb.org/browse/MONGOID-5622
=> MONGOID-5622 Reset the atomic operation state on reload (backport of #5656 to 8.0-stable)

lib/mongoid/atomic.rb, lib/mongoid/changeable.rb, lib/mongoid/reloadable.rb, spec/mongoid/reloadable_spec.rb
This backports #5656 from master to 8.1-stable.
> Reloading a document was not resetting the atomic operation state, which meant the reloaded might object might still believe there were changes to persist. This makes sure that state is reset on reload.
> ref: https://jira.mongodb.org/browse/MONGOID-5622
=> MONGOID-5622 Reset the atomic operation state on reload (backport of #5656 to 8.1-stable)

docs/release-notes/mongoid-9.0.txt, lib/mongoid/config.rb, lib/mongoid/config/introspection.rb, lib/mongoid/config/options.rb, lib/mongoid/fields.rb, spec/mongoid/config_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/fields_spec.rb
BSON 5 changes the default serialization of `BSON::Decimal128` values so that they return as native Ruby `BigDecimal` values. This change impacts Mongoid by making it impossible for fields declared as `BSON::Decimal128` to actually return `BSON::Decimal128` values.
This PR adds a configuration option (`allow_bson5_decimal128`) that re-registers the BSON::Decimal128 type handler so that these values are returned literally, rather than be translated into `BigDecimal` values.
*Caveat*: this changes the behavior of bson-ruby globally, for all requests running in the same process. If, for instance, you use Mongoid for some things, and the driver directly for others, changing this setting will impact all replies, regardless of how they were made.
=> RUBY-2993 allow Mongoid with BSON 5 to have literal BSON::Decimal128 fields

lib/mongoid/config.rb, lib/mongoid/config/options.rb, lib/mongoid/fields.rb, spec/mongoid/config_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/fields_spec.rb
This PR backports the changes from https://github.com/mongodb/mongoid/pull/5661 to 8.0-stable:
> BSON 5 changes the default serialization of BSON::Decimal128 values so that they return as native Ruby BigDecimal values. This change impacts Mongoid by making it impossible for fields declared as BSON::Decimal128 to actually return BSON::Decimal128 values.
> 
> This PR adds a configuration option (allow_bson5_decimal128) that re-registers the BSON::Decimal128 type handler so that these values are returned literally, rather than be translated into BigDecimal values.
> 
> Caveat: this changes the behavior of bson-ruby globally, for all requests running in the same process. If, for instance, you use Mongoid for some things, and the driver directly for others, changing this setting will impact …
=> MONGOID-5630 backport BSON::Decimal128 serialization flag to 8.0 stable

docs/release-notes/mongoid-8.1.txt, lib/mongoid/config.rb, lib/mongoid/config/options.rb, lib/mongoid/fields.rb, spec/mongoid/config_spec.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/fields_spec.rb
This PR backports the changes from #5661 to 8.1-stable:
> BSON 5 changes the default serialization of BSON::Decimal128 values so that they return as native Ruby BigDecimal values. This change impacts Mongoid by making it impossible for fields declared as BSON::Decimal128 to actually return BSON::Decimal128 values.
> 
> This PR adds a configuration option (allow_bson5_decimal128) that re-registers the BSON::Decimal128 type handler so that these values are returned literally, rather than be translated into BigDecimal values.
> 
> Caveat: this changes the behavior of bson-ruby globally, for all requests running in the same process. If, for instance, you use Mongoid for some things, and the driver directly for others, changing this setting will impact all replies, regardless of how they were …
=> MONGOID-5630 backport BSON::Decimal128 serialization flag to 8.1 stable

lib/mongoid/association/proxy.rb, lib/mongoid/extensions/hash.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/extensions/hash_spec.rb, spec/mongoid/tasks/database_rake_spec.rb
When `update_all` is invoked and atomic operations are given, it does not currently inspect the nested arguments for aliases. This results in broken behavior (and potentially corrupted data) when these atomic operations reference aliased fields.
This PR updates the `Hash#__consolidate__` method so that it looks for aliased fields, in addition to building the atomic set operation before an update.
=> MONGOID-5632 update_all with atomic operations and aliased fields

lib/mongoid/extensions/hash.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/extensions/hash_spec.rb
Backports MONGOID-5632 (update_all does not map :as option of the field properly) to 8.0-stable.
=> MONGOID-5636 Backport MONGOID-5632 (update_all does not map :as option of the field properly)

lib/mongoid/extensions/hash.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/extensions/hash_spec.rb
Backports MONGOID-5632 (update_all does not map :as option of the field properly) to 8.1-stable.
=> MONGOID-5637 backport MONGOID-5632 to 8.1-stable (update_all does not map :as option of the field properly)

lib/mongoid/criteria/queryable/selector.rb, spec/mongoid/criteria/queryable/selector_spec.rb
…ge $in and $nin when provided as a symbol as well as a string.
Issue was introduced with [PR-4645](https://github.com/mongodb/mongoid/pull/4645)
Behaviour before allowed $in and $nin to be provided as symbols or strings and would match correctly.
After [PR-4645](https://github.com/mongodb/mongoid/pull/4645) only $in or $nin strings would be merged.
This was breaking behaviour for our application during our upgrade from Mongoid 6.4 to 7.0 and is not mentioned anywhere as breaking in changelogs.
I have updated tests and new tests are passing with this change.
=> MONGOID-5642 Queryable::Selector#merge! does not properly handle :$in/:$nin keys

lib/mongoid/criteria/queryable/storable.rb, spec/mongoid/criteria/queryable/storable_spec.rb
Mongoid::Criteria::Queryable::Storable#add_field_expression when value is a hash with symbol operator key add values with same operator keys using $and
The keys of the hash being added are converted to a string but they keys of the corresponding hash in the selector are not converted to a string so they do not match and wrong result is given from `Mongoid::Criteria::Queryable::Storable#add_field_expression`
because `'$in' != :$in`
Currently using a symbol rather than a string will result in a different output e.g.
```
#Strings
Band.where("foo"=>{'$in' =>["bar"]}).where('foo' => {'$in' => ['zoom']})
=>  {"foo"=>{'$in'=>["bar"]}, "$and"=>[{"foo"=>{'$in'=>["zoom"]}}]}
#Symbols
Band.where("foo"=>{:$in=>["bar"]}).where('foo' => {:$in => ['zoom']})
=> {"foo"=>{:$in=>["zoom"]}}
```
With this fix …
=> MONGOID-5643 Storable#add_field_expression add values with same operator keys using $and when value is a hash with symbol operator key

lib/mongoid/attributes.rb, lib/mongoid/attributes/embedded.rb, lib/mongoid/attributes/nested.rb, lib/mongoid/extensions/hash.rb, lib/mongoid/reloadable.rb, lib/mongoid/utils.rb, spec/mongoid/attributes/embedded_spec.rb, spec/mongoid/extensions/hash_spec.rb
`Hash#__nested__` is an unnecessary monkey patch which is only used in one place. Let's remove it.
Moreover, it's logic duplicates the code in `Mongoid::Reloadable#extract_embedded_attributes`
This PR consolidates and refactors the logic, and fixes a number of edge-cases and adds lots of specs.
This PR also removes the `maybe_integer` Util method, because it doesn't do the correct thing. For example, a Hash may have a string literal key `"100"`, but `maybe_integer` will always convert this to numeric 100. (This case was actually covered in the pre-existing `__nested__` specs.)
=> MONGOID-5653 - Move Hash#__nested__ monkey patch method to new module Mongoid::Attributes::Embedded.traverse

lib/mongoid/contextual/mongo.rb, spec/mongoid/contextual/mongo_spec.rb
=> MONGOID-5647 #for_js with #count (backport to 8.1-stable)

.evergreen/config.yml, .evergreen/config/variants.yml.erb, .github/workflows/test.yml, lib/mongoid/tasks/database.rb, lib/mongoid/tasks/encryption.rake, spec/mongoid/tasks/database_rake_spec.rb
The Rails specs in the Mongoid evergreen suite do not enable FLE for the database rake tasks, which means those specs are consistently being skipped.
=> MONGOID-5656 Rails specs ought to enable FLE

docs/release-notes/mongoid-9.0.txt, lib/mongoid/config.rb, lib/mongoid/interceptable.rb, spec/integration/callbacks_spec.rb, spec/mongoid/interceptable_spec.rb
This is a band-aid for [MONGOID-5658](https://jira.mongodb.org/browse/MONGOID-5658)
The existing implementation of callbacks guarantees a sane order of execution; however, it causes stack overflow if there are many embeddeds (even in a flat structure). To fix this issue we suggest ignoring around callbacks for embedded documents. This allows us to patch the existing implementation of the callbacks and keep the proper order of callbacks.
If something still needs to be done around a database operation for an embedded document, it can be done in corresponding callback of the parent document.
We should discuss a necessity of callbacks for embedded documents in general. If we still feel that we should keep this functionality, the callbacks implementation in general should be revised.
=> MONGOID-5658 Fix callbacks for embedded

lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/referenced/has_many/proxy.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb
Adds extended support for `#exists?` on `embeds_many` and `has_many` associations, so the API is the same as is present elsewhere in Mongoid, where the `#exists?` accepts conditions that can be used to narrow the scope of the query.
=> MONGOID-5608 allow using `#exists?` with args on relations

lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/referenced/has_many/proxy.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb
Backports https://jira.mongodb.org/browse/MONGOID-5608 (#5736) to 8.1-stable.
=> MONGOID-5608 allow using `#exists?` with args on relations (for 8.1-stable)

lib/mongoid/contextual/memory.rb, lib/mongoid/extensions/false_class.rb, lib/mongoid/extensions/object.rb, lib/mongoid/extensions/true_class.rb, spec/mongoid/extensions/false_class_spec.rb, spec/mongoid/extensions/object_spec.rb, spec/mongoid/extensions/true_class_spec.rb
Fixes MONGOID-5663
`Object#__sortable__` is a kernel monkey patch which is only used in `Contextual::Memory`.
This PR moves it to a private method in `Contextual::Memory` with a minor amount of refactoring. Existing tests already cover all the functionality.
=> MONGOID-5663 [Monkey Patch Removal] Remove Object#__sortable__

lib/mongoid/association/relatable.rb, lib/mongoid/extensions/nil_class.rb, lib/mongoid/extensions/object.rb
Fixes [MONGOID-5664](https://jira.mongodb.org/browse/MONGOID-5664)
`Object#__setter__` is a kernel monkey-patch used only in `Mongoid::Association::Relatable`. This is a trivial method so I've just inlined it. (The same logic is already inlined in several other places.)
=> MONGOID-5664 [Monkey Patch Removal] Remove Object#__setter__ monkey-patch

lib/mongoid/atomic_update_preparer.rb, lib/mongoid/contextual/mongo.rb, lib/mongoid/extensions/hash.rb, spec/mongoid/atomic_update_preparer_spec.rb, spec/mongoid/extensions/hash_spec.rb
This PR takes the work by @johnnyshields  (here: https://github.com/mongodb/mongoid/pull/5689) and reworks it so that the `Hash#__consolidate__` method is deprecated, rather than removed. (In an ideal world, we would indeed just remove the method, but even though the naming of the method strongly suggests it is not part of the public API, the method itself was never explicitly declared to be `@api private`, and so out of an abundance of caution we are opting to deprecate it until the next major release.)
=> MONGOID-5654: refactor and deprecate Hash#__consolidate__

lib/mongoid/extensions/big_decimal.rb, lib/mongoid/extensions/object.rb, lib/mongoid/persistable/incrementable.rb, lib/mongoid/persistable/multipliable.rb
This extends @johnnyshields work in https://github.com/mongodb/mongoid/pull/5709 and deprecates `Object#__to_inc__` and `BigDecimal#__to_inc__`.
Though these are implicitly private API methods, they were never explicitly declared as such, and so we're opting to deprecate them for now and remove them in a later major release.
=> MONGOID-5662 Deprecate Object#__to_inc__ and BigDecimal#__to_inc__

lib/mongoid/extensions/integer.rb, lib/mongoid/extensions/string.rb
Fixes MONGOID-5667
These methods currently serve no purpose and are not called anywhere. They are probably relics of the past.
=> MONGOID-5667 [Monkey Patch Removal] Remove String/Integer#unconvertable_to_bson?

lib/mongoid/extensions/string.rb, lib/mongoid/extensions/symbol.rb, spec/mongoid/extensions/string_spec.rb, spec/mongoid/extensions/symbol_spec.rb
Fixes MONGOID-5668
These methods are not called anywhere in the code, and they do not serve any clear purpose. They are unlikely to be in use by actual users.
They need to be deprecated before removal.
=> MONGOID-5668 [Monkey Patch Removal] Remove String/Symbol#mongoid_id?

lib/mongoid/association/nested/many.rb, lib/mongoid/association/nested/nested_buildable.rb, lib/mongoid/association/nested/one.rb, lib/mongoid/criteria.rb, lib/mongoid/extensions/hash.rb
Fixes MONGOID-5670
Moved to Nested::NestedBuildable
These should first be marked deprecated, so I will raise a PR to 8.1 branch.
Also it seems there are no specs for these. Since they are private, it will stay that way.
=> MONGOID-5670 [Monkey Patch Removal] Remove Hash#delete_id and Hash#extract_id

lib/mongoid/association/bindable.rb, lib/mongoid/association/embedded/embedded_in/binding.rb, lib/mongoid/association/embedded/embeds_many/binding.rb, lib/mongoid/association/embedded/embeds_one/binding.rb, lib/mongoid/association/referenced/has_and_belongs_to_many/binding.rb, lib/mongoid/cacheable.rb, lib/mongoid/extensions/object.rb, lib/mongoid/validatable.rb, spec/mongoid/extensions/object_spec.rb
Fixes MONGOID-5673
Object#do_or_do_not and Object#you_must are kernel monkey patches which are similar to #try. Someone got cute and added Star Wars Yoda references `#do_or_do_not, there is no #try`.
For `#do_or_do_not` usages which can obviously be replaced with `#try` or `#send` I've done so. The remaining usages are localized to the `Bindable` module, so I've added a convenience method there which I've named `#try_method`.
For `#you_must`, I've inlined the call the `if frozen?`
No tests added here because the method is private and trivial.
> Don't be too proud of this technological terror you've constructed.
> -- Darth Vader.
`#try` (and `#try_method` used here) are code smells. `#try_method` should be removed entirely in in the future, but at least for now it's localized to the …
=> MONGOID-5673 [Monkey Patch Removal] Remove Object#do_or_do_not and Object#you_must

docs/reference/configuration.txt, lib/rails/generators/mongoid/config/templates/mongoid.yml
This PR adds the "compressors" option to the auto-generated `mongoid.yml` template. Note that since it is a driver option, it is not covered by the Introspection feature. This is important, because I think many users look at the generated `mongoid.yml` as their primary reference for config options.
In addition, I've removed a line from the docs about setting compressors via connection string. Although this is *technically possible*, it is not something that should be recommended to users. (Virtually _all options_ can be set via connection string, and the Mongoid docs never recommend to use it, so it feels out-of-place in this specific instance.)
=> RUBY-2807 - Add "compressors" option to Mongoid.yml

spec/mongoid/criteria/queryable/extensions/symbol_spec.rb, spec/mongoid/monkey_patches_spec.rb
Fixes [MONGOID-5661](https://jira.mongodb.org/browse/MONGOID-5661)
This PR adds a spec to check which kernel monkey patches Mongoid has added. It will help the team to remove them overtime, and will help ensure Mongoid developers do not add new monkey patches going forward.
=> MONGOID-5661 [Monkey Patch Removal] Add test which checks for monkey patches

Rakefile, docs/reference/configuration.txt, lib/rails/generators/mongoid/config/templates/mongoid.yml
Refreshes the documentation for the configuration options so it mirrors the current mongoid.yml template.
=> MONGOID-5691 Ensure that all Mongoid config options are mentioned in the documentation

lib/mongoid/extensions/range.rb
This PR removes a note which is relevant to Ruby 2.6.
I think we should still catch ArgumentError here as it is still possible to occur, e.g. if min and max are both blank, or if they aren't range compatible, etc.
=> [READY FOR REVIEW] MONGOID-5715 - [Ruby 2.6 Removal] Remove note about range in Ruby 2.6

docs/reference/configuration.txt, docs/release-notes/mongoid-9.0.txt, lib/mongoid/association/referenced/auto_save.rb, lib/mongoid/association/referenced/counter_cache.rb, lib/mongoid/clients/options.rb, lib/mongoid/clients/storage_options.rb, lib/mongoid/config.rb, lib/mongoid/config/defaults.rb, lib/mongoid/document.rb, lib/mongoid/persistable/creatable.rb, lib/mongoid/persistence_context.rb, spec/mongoid/clients/options_spec.rb, spec/mongoid/config/defaults_spec.rb, spec/mongoid/config_spec.rb, spec/mongoid/document_persistence_context_spec.rb
Makes the storage options writable for individual records, and incorporates those individualized storage options into the persistence context so that subsequent operations on that document object will then fall back to those storage options, if others are not overriding them.
See MONGOID-5472.
=> MONGOID-5472 Save models using the overridden storage options used for their loading

lib/rails/generators/mongoid/config/templates/mongoid.yml
If my English is not failing me, this seems like a typo/leftover.
=> Fix typo/leftover in mongoid.yml file generator template

lib/mongoid/railtie.rb
Because directly referencing `ActiveJob` constant would cause `NameError` on Rails apps that do not bundle AJ.
This follows up #5676.
=> Wrap ActiveJob custom Serializers handling with on_load(:active_job) hook

lib/mongoid/validatable.rb, lib/mongoid/validatable/associated.rb, spec/mongoid/validatable/associated_spec.rb, spec/support/models/name.rb
When validating a belongs_to association, Mongoid was loading the associated record and validating it, which could result in a recursive chain of records being loaded and validated, even though they had been persisted and had not changed.
This PR fixes the regression by only validating the associated record if it is (1) already loaded, and (2) either new (unpersisted), or changed.
=> MONGOID-5704 Fix performance regression on belongs_to validation

.github/workflows/test.yml, lib/mongoid/validatable.rb, lib/mongoid/validatable/associated.rb, spec/mongoid/validatable/associated_spec.rb, spec/support/models/name.rb
* MONGOID-5740 don't try to validate persisted, unchanged associations
* we just need the attribute name
* fix failing specs
* tread very carefully so we don't trigger a load while validating
* hopefully fix has-many behavior
* documentation
* simplify
* make sure attributes getter is defined
* Fix typo -- records are not loaded *from the database*
---------
=> MONGOID-5740 Fix performance regression on belongs_to validation (backport to 8.1-stable)

.github/workflows/test.yml, lib/mongoid/validatable.rb, lib/mongoid/validatable/associated.rb, spec/mongoid/validatable/associated_spec.rb, spec/support/models/name.rb
* MONGOID-5740 don't try to validate persisted, unchanged associations
* we just need the attribute name
* fix failing specs
* tread very carefully so we don't trigger a load while validating
* hopefully fix has-many behavior
* documentation
* simplify
* make sure attributes getter is defined
* Fix typo -- records are not loaded *from the database*
---------
=> MONGOID-5740 Fix performance regression on belongs_to validation (backport to 8.0-stable)

docs/release-notes/mongoid-8.0.txt
JIRA - https://jira.mongodb.org/browse/DOCSP-37327
Staging - https://preview-mongodbnorareidy.gatsbyjs.io/mongoid/DOCSP-37327-staging/release-notes/mongoid-8.0/
=> DOCSP-37327: Fix table format

mongoid.gemspec
BSON 5 is released, and Mongoid ought to support it.
=> MONGOID-5739 Support BSON 5

docs/reference/queries.txt
https://jira.mongodb.org/browse/DOCSP-37326
We're working with a third-party vendor to localize our documentation. One of their linguists reported the following formatting error on one of the Mongoid docs pages:
[live site](https://www.mongodb.com/docs/mongoid/current/reference/queries/#:~:text=Mongoid%3A%3AErrors%3A%3ADocumentNotFound%20if%20any%20of%20the)
Minor change to correct formatting, as shown here:
[staged changes](https://docs-mongodbcom-staging.corp.mongodb.com/mongoid/docsworker-xlarge/DOCSP-37326/reference/queries/#:~:text=Mongoid%3A%3AErrors%3A%3ADocumentNotFound)
[build log](https://workerpool-boxgs.mongodbstitch.com/pages/job.html?collName=queue&jobId=65e64de111db7b04277925c7)
=> DOCSP-37326: fix formatting

gemfiles/driver_master.gemfile, gemfiles/driver_stable.gemfile, lib/mongoid/clients/sessions.rb
Mongoid's test suite exhibits some new failures when run against the latest version of the driver (2.20).
=> MONGOID-5754 Making sure Mongoid works right with latest driver

docs/reference/configuration.txt, lib/mongoid.rb, lib/mongoid/clients.rb, spec/mongoid/clients_spec.rb, spec/mongoid_spec.rb
This PR does the following:
- Add `Mongoid.reconnect_clients` method analogous to `Mongoid.disconnect_clients`. The reason for adding this is to simplify web server hooks (see added docs.)
- Corrects the `@return` in the docs for `disconnect_clients`. Also added specs which cover the existing behavior.
- Updates documentation related to web server forking.
This will hopefully help others avoid [issues we saw in our production](https://github.com/puma/puma/issues/3134).
See also: https://github.com/mongodb/mongo-ruby-driver/pull/2856
=> MONGOID-5758: Add Mongoid.reconnect_clients and improve forking webserver documentation

README.md, lib/mongoid/version.rb
Mongoid 9.0 is a new major update to the Mongoid ODM. It includes many bug fixes, updates, improvements, and new features.
Significant new features include the following:
* You can now create and manage Atlas search indexes directly from Mongoid, by specifying your search index definitions directly on the relevant models. (MONGOID-5601)
* You can now declare a transaction with a block, using syntax that should be familiar to Rails programmers. (You must still be using a MongoDB topology that supports transactions, like a replica-set or sharded topology.) Along with this new syntax, support has also been added for `after_commit` and `after_rollback` callbacks. (MONGOID-5530, MONGOID-5531 and MONGOID-5708)
* Around callbacks on embedded documents are now disabled by default, for performance …
=> MONGOID-5762 Prep for 9.0 release

lib/mongoid/atomic_update_preparer.rb, spec/mongoid/contextual/mongo_spec.rb, spec/support/models/band.rb, spec/support/models/lat_lng.rb
During our upgrade of mongoid to 8.x version hit into issue that that custom type field classes stops working in update_all, when
$set operator is used:
```
class LatLng
attr_accessor :lat, :lng
def self.demongoize(object)
LatLng.new(object[1], object[0])
end
def initialize(lat, lng)
@lat, @lng = lat, lng
end
def mongoize
[ lng, lat ]
end
end
class Bar
field :lat_lng, type: LatLng
end
Bar.create!
Bar.update_all('$set' => { lat_lng: LatLng.new(52.30, 13.25) })
BSON::Error::UnserializableClass: Value does not define its BSON serialized type: #<LatLng:0x000057678d11ddb0>
```
This problem is not highlighted by the tests due to mongoize does not work, but BSON still able serialize strings and send it to database:
```
context.update_all("$set" => { member_count: "1" }) …
```
=> Mongoize is not called on update_all, when $set operator is used

spec/mongoid/touchable_spec.rb, spec/mongoid/touchable_spec_models.rb
This branch adds a spec to touchable_spec.rb to test whether the symbol representing the field to touch provided to the touch option is indeed touched. Two extra models - Band and Label - were also added to touchable_spec_model.rb for this. See https://jira.mongodb.org/browse/MONGOID-5508 for more.
=> 5508 touch on custom field

sbom.json
Adds an SBOM lite file with no dependencies for onboarding to Silk
=> RUBY-3489: Add empty SBOM lite file

lib/mongoid/contextual/aggregable/memory.rb, lib/mongoid/contextual/aggregable/mongo.rb, spec/mongoid/contextual/aggregable/memory_spec.rb, spec/mongoid/contextual/aggregable/mongo_spec.rb
Hi, in accordance with Ruby's enumerable API, I've added support for initial value when a block is given to `Enumerable#sum`.
Tell me if the provided changes are ok and I could replicate the same changes to `min` and `max` methods.
Cheers!
=> MONGOID-5786: Fix some compatibility issues with Enumerable API

lib/mongoid/config.rb, lib/mongoid/scopable.rb, spec/mongoid/scopable_spec.rb
As currently implemented, named scopes are merged with the default scope (see [here](https://github.com/mongodb/mongoid/blob/a5657dc6044c1f870dc36db3aed3cfdea66e7b66/lib/mongoid/scopable.rb#L297)). This means you cannot declare a named scope that unsets any part of the default scope; if you try, the default scope will simply be merged back into it.
Merging the default scope is not necessary, because any scope you pass in will already be based on the default scope:
```ruby
class Person
default_scope { where(deleted_at: nil) }
scope :germans, -> { where(country: 'DE') }
end
```
Here, `Person.germans` will always use the default scope, even without it being merged in, because calling `where` will initialize a new `Criteria` object using that default scope. Merging …
=> MONGOID-5785 allow named scopes to remove a default scope

lib/mongoid/touchable.rb, spec/mongoid/association_spec.rb
The problem manifested when a class declared an association on a class that hadn't yet been loaded; when the touchable module began adding its functionality, there were a few lines that tried to load the referenced class, e.g.:
```ruby
class Child
embedded_in :parent
end
class Parent
embeds_many :children
end
```
This would result in a `NameError` because the `embedded_in` association could not find the `Parent` class at load-time.
I started by checking to see if we could just raise a more informative error in this case, as a stop-gap before spending more time later to actually fix the issue. Imagine my joy when I realized that the entire problem was caused by a few lines of dead-code! By simply deleting the unused code, the problem went …
=> MONGOID-5790 MONGOID-5791 Fix error caused by loading a referenced class prematurely

.github/workflows/test.yml, lib/mongoid/fields.rb, lib/mongoid/touchable.rb, spec/mongoid/attributes_spec.rb, spec/mongoid/fields_spec.rb
Allow `nil` attribute access (returning `nil` instead of raising an obscure exception). See #5836.
=> MONGOID-5789 Allow nil attribute access (backport of #5836)

lib/mongoid/version.rb
Bumped the version of Mongoid from 9.0.0 to 9.0.1 in accordance with Semantic versioning. 
Here is a draft of the release notes: 
Version 9.0.1 of Mongoid is now available. 
Release Highlights 
* [MONGOID-5786](https://jira.mongodb.org/browse/MONGOID-5786): In accordance with Ruby's enumerable API, the `#sum` method now accepts an optional block. Thank you to Cristián Pérez for your contributions!
* [MONGOID-5688](https://jira.mongodb.org/browse/MONGOID-5688): Problematic recursive callstacks in cascading callbacks have been linearized using Ruby Fibers to prevent SystemStackErrors with greater numbers of embedded documents. Thank you to Adviti Mishra for your contributions! 
* [MONGOID-5769](https://jira.mongodb.org/browse/MONGOID-5769): $pop and $pull are now mongoized the same way as …
=> Bump version to 9.0.1

lib/mongoid/version.rb
Changes in 9.0.2:
- [MONGOID-5734](https://jira.mongodb.org/browse/MONGOID-5734) Allow custom polymorphic types
- [MONGOID-5806](https://jira.mongodb.org/browse/MONGOID-5806) Rails 7.2 support
- [MONGOID-5797](https://jira.mongodb.org/browse/MONGOID-5797) When using a projection with embeds many relations, accessing the inverse association will now raise MissingAttributeError
- [MONGOID-5808](https://jira.mongodb.org/browse/MONGOID-5808) Issue with using time series collections with Mongoid 9
=> MONGOID-5817 Bump version to 9.0.2

lib/mongoid/matcher.rb, spec/mongoid/association/referenced/belongs_to/proxy_spec.rb
Fixes a performance regression caused by always splitting keys at `.` characters, whether the string has them or not. By short-circuiting the common case, we can recover a significant performance improvement. (Backport from master.)
=> MONGOID-5805 Short-circuit the logic in extract_attribute to fix performance regression (backport to 8.1-stable)

lib/mongoid/association/many.rb, lib/mongoid/cacheable.rb, spec/integration/caching_spec.rb, spec/mongoid/association/embedded/embeds_many/proxy_spec.rb, spec/mongoid/association/referenced/has_many/proxy_spec.rb, spec/mongoid/cacheable_spec.rb
This PR adds a `#cache_version` method to `Mongoid::Document` instances, as well as to the `has_many` and `embeds_many` proxies, which brings Mongoid closer to API parity with ActiveRecord.
This also modifies `#cache_key` to better parallel how it works in ActiveRecord: if `cache_version` returns non-nil, `cache_key` will *not* embed the timestamp in the key. Instead, the timestamp is used as the version for the entry (which reduces key churn).
**Note**: this PR does slightly change the behavior of Mongoid when used with Rails caching (`#cache_key` will not embed the timestamp when `#cache_version` is non-nil, as mentioned). We discussed this as a team and do not believe this constitutes a breaking change; in the worst case, systems that depend on caching may find at least some of their …
=> MONGOID-4680 implement cache_version for better Rails caching support

lib/mongoid/clients/options.rb, lib/mongoid/matcher.rb, spec/mongoid/association/referenced/belongs_to/proxy_spec.rb, spec/mongoid/clients/options_spec.rb
With the creation of the 9.0-stable branch, there were a few issues in master that needed to be backported, for inclusion in a future 9.0.3 release (since master is currently slated to be the next minor release, 9.1).
The issues backported here are:
- MONGOID-5815 (respect client_override for new docs)
- MONGOID-5805 (short-circuit the logic in extract_attribute to fix a performance issue)
=> Backports from master to 9.0-stable

lib/mongoid/clients/options.rb, lib/mongoid/matcher.rb, spec/mongoid/association/referenced/belongs_to/proxy_spec.rb, spec/mongoid/clients/options_spec.rb
PR #5885 was misconfigured and actually merged to master, instead of 9.0-stable. (I hate it when I do that! 🤦) This PR is the exact same changes as that one, but is targeting the correct branch now.
=> Backports to 9.0 (redux)

lib/mongoid/validatable/associated.rb, spec/mongoid/serializable_spec.rb, spec/mongoid/validatable/associated_spec.rb
(Backporting https://github.com/mongodb/mongoid/pull/5881 from master to 8.0-stable.)
Changes made for [MONGOID-5704](https://jira.mongodb.org/browse/MONGOID-5704) introduced a regression that caused associated validations to stop after the first failure, rather than validating all associated records. This PR corrects the regression by fixing the short-circuited evaluation that was introduced in that earlier PR.
=> MONGOID-5757 Fix validation checks so that all associated records are validated

lib/mongoid/persistence_context.rb, spec/mongoid/clients/options_spec.rb, spec/mongoid/persistence_context_spec.rb
(Backport of #5886 to the 9.0-stable branch.)
When [MONGOID-5472](https://jira.mongodb.org/browse/MONGOID-5472) was implemented (to enable models to remember the persistence context that was active when they were saved), it changed how storage options are interpreted in Mongoid. One overlooked pre-existing feature, however, was the ability to pass a Proc as the database name, and the new code did not account for that.
This PR updates the persistence context so that when a new client is instantiated, it does not receive the :database option (which was previously accounted for by calling client.use instead). This prevents the Proc-valued :database option from being reinterpreted as a String by the client, which was causing errors because the resulting "name" was not valid.
=> MONGOID-5819 Do not pass the :database option when creating a client (Backport to 9.0)

lib/mongoid/contextual/mongo.rb, lib/mongoid/criteria.rb, lib/mongoid/findable.rb, spec/mongoid/contextual/mongo_spec.rb, spec/mongoid/criteria_spec.rb
Mongoid now supports a new `raw` directive when building queries. When present, the resulting query will be returned as hashes, rather than instantiated document models. The hashes will not be "demongoized" -- the values will be returned exactly as provided by the database, directly.
If you specify `typed: true`, the hashes will be returned with the values translated from the raw value stored in the database, into the corresponding type defined by the `field` definitions on the model. (That is to say, they will be "demongoized".)
For example:
```ruby
result = Person.raw.first
p result  #=> {"_id"=>BSON::ObjectId(...), "name" => "...", "birth_date" => 2002-01-01 00:00:00 -0600, ... }
result = Person.raw(typed: true).first
p result  #=> {"_id"=>BSON::ObjectId(...), "name" => "...", …
```
=> MONGOID-5411 allow results to be returned as demongoized hashes

lib/mongoid/persistence_context.rb, lib/mongoid/railties/controller_runtime.rb, lib/mongoid/threaded.rb, lib/mongoid/timestamps/timeless.rb, lib/mongoid/touchable.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/interceptable_spec_models.rb, spec/mongoid/threaded_spec.rb, spec/rails/controller_extension/controller_runtime_spec.rb
(Backport from master to 9.0-stable)
MONGOID-5688 introduced a new way of processing cascading callbacks on embedded children, using Fibers to linearize the recursive calls. This proved very effective in avoiding `SystemStackError` exceptions caused by large numbers of embedded documents.
However, it turns out that `Thread#[]` and `Thread#[]=` get and set *fiber-local* variables, and not *thread-local* variables. Mongoid was using these methods quite a bit to set and manage its own internal state, which meant that any cascading callback on embedded children would be executed in a context that lacked all of Mongoid's state from the parent thread.
This PR fixes this issue by changing Mongoid's state handling routines (`Mongoid::Threaded`) to use actual thread-local storage …
=> MONGOID-5823 Use proper thread-local variables instead of fiber-local variables (Backport to 9.0)

lib/mongoid/loadable.rb, spec/mongoid/loadable_spec.rb
(Backporting from master to 9.0-stable.)
When using `Mongoid.load_models`, it will blindly try to load all Ruby files in the model load path. This can fail when the loader tries to load files (like concerns) that do not define models, but which reference models that have not yet been loaded.
This PR attempts to address this by adding a new `ignore_patterns` option, which defaults to an array with a single string, `*/concerns/*`. Any path that matches this pattern will be ignored by the loader.
=> MONGOID-5829 Add a way to ignore paths for model loading (backport to 9.0-stable)

lib/mongoid/persistence_context.rb, spec/mongoid/persistence_context_spec.rb
(This backports #5906 to 9.0-stable.)
Previously, it was possible to provide the client as a proc (returning the name of the client to use). This broke in Mongoid 9.
This PR adds a call to `__evaluate__` the client name to ensure that if it is a proc it is properly handled.
=> MONGOID-5830 Client name may be a proc (backport to 9.0-stable)

lib/mongoid/equality.rb, spec/mongoid/equality_spec.rb
[MONGOID-5737](https://jira.mongodb.org/browse/MONGOID-5737)
Mongoid defines <=> but errors if both documents are not Mongoid::Document instance. Default to super's implementation of <=> if other doc is not of same class.
=> MONGOID-5737 Fix issue where <=> errors if there's a non-document (backport for 9.0)

lib/mongoid/criteria/queryable/selectable.rb, spec/mongoid/criteria/queryable/selectable_spec.rb
[MONGOID-5780](https://jira.mongodb.org/browse/MONGOID-5780)
Ensure that chaining "not" results in the correct negating state.
=> MONGOID-5780 Fix chaining nots resulting in incorrect negation state (backport for 8.1)

lib/mongoid/criteria/queryable/selectable.rb, spec/mongoid/criteria/queryable/selectable_spec.rb
[MONGOID-5780](https://jira.mongodb.org/browse/MONGOID-5780)
Ensure that chaining "not" results in the correct negating state.
=> MONGOID-5780 Fix chaining nots resulting in incorrect negation state (backport to 9.0)

lib/mongoid/attributes/readonly.rb, spec/mongoid/attributes/readonly_spec.rb
[MONGOID-5816](https://jira.mongodb.org/browse/MONGOID-5816)
When we have two classes A and B that are subclasses from Base, declaring attr_readonly in the context of A or B leaks that declaration into the entire class hierarchy. Currently, all classses share the same readonly attributes at the end of declaration. Fixed so that A and B inherit the read only attributes of Base but including additional readonly attributes in the subclasses is instance specific.
=> MONGOID-5816: attr_readonly leaks into sibling classes (backport for 8.1)

lib/mongoid/attributes/readonly.rb, spec/mongoid/attributes/readonly_spec.rb
[MONGOID-5816](https://jira.mongodb.org/browse/MONGOID-5816)
When we have two classes A and B that are subclasses from Base, declaring attr_readonly in the context of A or B leaks that declaration into the entire class hierarchy. Currently, all classses share the same readonly attributes at the end of declaration. Fixed so that A and B inherit the read only attributes of Base but including additional readonly attributes in the subclasses is instance specific.
=> MONGOID-5816: attr_readonly leaks into sibling classes (backport for 9.0)

lib/mongoid/validatable/associated.rb, spec/mongoid/association_spec.rb
MONGOID-5822
In the case where there is an association with validation dependent on a parent condition, the document is not marked as invalid if the parent update results in an invalid association unless there was also a change in the child.
=> MONGOID-5822: Embedded association validations break when association depends on parent update

.evergreen/config.yml, .evergreen/config/axes.yml.erb, .evergreen/config/commands.yml.erb, .evergreen/config/variants.yml.erb, .evergreen/run-tests.sh, Rakefile, gemfiles/bson_min.gemfile, gemfiles/standard.rb, lib/mongoid/document.rb, spec/mongoid/document_spec.rb
(Backport from 8.1-stable to 8.0-stable.)
Under certain situations, and when `legacy_attributes` is true, the hash returned from `#as_document` can be the actual hash used internally to represent the model. Modifying this hash will modify the internal state of the model, which is unexpected and dangerous.
To fix this, the attributes must be deep-duplicated before being returned by `#as_document`, if `legacy_attributes` is true.
This does not affect 9.0-stable and later, because the `legacy_attributes` setting was removed when 9.0 was released.
=> MONGOID-5810 make sure we don't leak internal state via as_document (backport to 8.0-stable)

.github/workflows/release.yml
Experimental: trying to work around the problem with the wrong securerandom version being activated when pushing a new gem version.
Note: it is not possible to test the branch fully because my personal fork does not have the necessary AWS permissions to assume roles needed for the standard deployment steps. I've done a simple dry run and confirmed that there are no problems with syntax, and that our "release" github action is able to get my own fork of the drivers-github-tools repository, which has the necessary changes to support invalidating the bundler cache.
=> Invalidate bundler cache when cutting a new gem

.github/workflows/release.yml
While troubleshooting the deploy issues earlier, I pointed the release action to my own fork of the drivers-github-tools. This PR changes it back, so it points to the canonical repo.
=> Release action update

lib/mongoid/validatable/associated.rb, spec/mongoid/association_spec.rb
[MONGOID-5822](https://jira.mongodb.org/browse/MONGOID-5822)
In the case where there is an association with validation dependent on a parent condition, the document is not marked as invalid if the parent update results in an invalid association unless there was also a change in the child
=> MONGOID-5822: Embedded association validations break when association depends on parent update (backport for 8.0)

lib/mongoid/validatable/associated.rb, spec/mongoid/association_spec.rb
[MONGOID-5822](https://jira.mongodb.org/browse/MONGOID-5822)
In the case where there is an association with validation dependent on a parent condition, the document is not marked as invalid if the parent update results in an invalid association unless there was also a change in the child.
=> MONGOID-5822: Embedded association validations break when association depends on parent update (backport for 8.1)

lib/mongoid/validatable/associated.rb, spec/mongoid/association_spec.rb
[MONGOID-5822](https://jira.mongodb.org/browse/MONGOID-5822)
In the case where there is an association with validation dependent on a parent condition, the document is not marked as invalid if the parent update results in an invalid association unless there was also a change in the child.
=> MONGOID-5822: Embedded association validations break when association depends on parent update (backport for 9.0)

lib/mongoid/association/eager_loadable.rb, lib/mongoid/traversable.rb, spec/mongoid/association/eager_spec.rb
(backport to 9.0-stable)
If the root of a query is an STI subclass (e.g. `Subclass.all`) AND the query tries to eager load (`includes`) another association, the eager load was failing because it was looking for inverse associations using the STI subclass name, instead of the class at the root of the hierarchy.
=> MONGOID-5839 Fix eager-loading from STI subclasses (backport to 9.0-stable)

lib/mongoid/association/eager_loadable.rb, lib/mongoid/traversable.rb, spec/mongoid/association/eager_spec.rb
(backport to 8.1)
If the root of a query is an STI subclass (e.g. `Subclass.all`) AND the query tries to eager load (`includes`) another association, the eager load was failing because it was looking for inverse associations using the STI subclass name, instead of the class at the root of the hierarchy.
=> MONGOID-5839 Fix eager-loading from STI subclasses (backport to 8.1)

lib/mongoid/association/eager_loadable.rb, lib/mongoid/traversable.rb, spec/mongoid/association/eager_spec.rb
(backport to 8.0)
If the root of a query is an STI subclass (e.g. Subclass.all) AND the query tries to eager load (includes) another association, the eager load was failing because it was looking for inverse associations using the STI subclass name, instead of the class at the root of the hierarchy.
=> MONGOID-5839 Fix eager-loading from STI subclasses (backport to 8.0)

.github/workflows/test.yml, lib/mongoid/interceptable.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/interceptable_spec_models.rb
(Backport to 8.1-stable)
* MONGOID-5836 don't explicitly process grandchildren
Grandchildren are already accounted for when this is invoked, because if called when callbacks are cascading, the input is the full list of all children and grandchildren. Processing grandchildren recursively here causes them to be processed twice.
* specify python version to address failing mongo-orchestration
* make sure we don't break update callbacks
=> MONGOID-5836 Don't repeat callbacks for embedded grandchildren (backport to 8.1-stable)

.github/workflows/test.yml, lib/mongoid/interceptable.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/interceptable_spec_models.rb
(Backport to 9.0-stable)
* MONGOID-5836 don't explicitly process grandchildren
Grandchildren are already accounted for when this is invoked, because if called when callbacks are cascading, the input is the full list of all children and grandchildren. Processing grandchildren recursively here causes them to be processed twice.
* specify python version to address failing mongo-orchestration
* make sure we don't break update callbacks
=> MONGOID-5836 Don't repeat callbacks for embedded grandchildren (backport to 9.0-stable)

.github/workflows/test.yml, lib/mongoid/config.rb, lib/mongoid/interceptable.rb, spec/integration/callbacks_models.rb, spec/integration/callbacks_spec.rb, spec/mongoid/interceptable_spec.rb, spec/mongoid/interceptable_spec_models.rb
(Backport to 8.0-stable)
* MONGOID-5836 don't explicitly process grandchildren
Grandchildren are already accounted for when this is invoked, because if called when callbacks are cascading, the input is the full list of all children and grandchildren. Processing grandchildren recursively here causes them to be processed twice.
* specify python version to address failing mongo-orchestration
* make sure we don't break update callbacks
This also backports the `:prevent_multiple_calls_of_embedded_callbacks` feature flag, from MONGOID-5542, so that we can safely prevent duplicate callbacks in a backwards-compatible way.
=> MONGOID-5836 Don't repeat callbacks for embedded grandchildren. (backport to 8.0-stable)

lib/mongoid/version.rb
_Proposed release announcement:_
Mongoid 8.0.9 is now available. This is the most recent patch release in the 8.0 series, and includes the following bug fixes.
* MONGOID-5836 - Callbacks were being duplicated on deeply embedded children. A related issue (MONGOID-5542) was also backported to 8.0, exposing the `Mongoid.prevent_multiple_calls_of_embedded_callbacks` setting to preserve backwards compatibility in most cases (defaults to `false`).
* MONGOID-5757 - Child validations were being short-circuited, resulting in subsequent validation callbacks not being called after the first failing validation.
* MONGOID-5797 - Accessing the parent document from an embedded document was failing with an error when the original query applied a projection.
* MONGOID-5810 - When …
=> Prep for 8.0.9

lib/mongoid/version.rb
Release highlights:
* MONGOID-5836 - Callbacks were being duplicated on deeply embedded children.
* MONGOID-5839 - When using single-collection inheritance, eager loading (with `#includes`) was not producing the correct query when the root of the query was the document subclass.
* MONGOID-5825 - The `Mongoid::Timestamps` module would (in certain cases) attempt to timestamp deleted documents, which resulted in a `FrozenError` being raised.
=> Prepare for v8.1.9

lib/mongoid/association/referenced/has_many/enumerable.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb
(backport to 9.0)
In certain situations, calling #size on a HABTM association will return the wrong count.
This will happen if the association is
initialized to a single element (forcing the _unloaded Criteria object to be scoped to that specific element) and then assigning an array of multiple (already-persisted) elements to the association, where one of the elements is the same element that already existed there.
In this case, `_unloaded.count` will return 1, and then the _added array will have two previously-persisted records. Naive implementations will thus return either 1, or 3, rather than the correct answer of 2. To get the correct answer, it is necessary to add a filter condition to `_unloaded.count` that excludes the records in the `_added` array.
=> MONGOID-5844 Fix counting bug in HABTM associations (backport to 9.0)

lib/mongoid/association/referenced/has_many/enumerable.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb
(backport to 8.1)
In certain situations, calling #size on a HABTM association will return the wrong count.
This will happen if the association is
initialized to a single element (forcing the _unloaded Criteria object to be scoped to that specific element) and then assigning an array of multiple (already-persisted) elements to the association, where one of the elements is the same element that already existed there.
In this case, `_unloaded.count` will return 1, and then the _added array will have two previously-persisted records. Naive implementations will thus return either 1, or 3, rather than the correct answer of 2. To get the correct answer, it is necessary to add a filter condition to `_unloaded.count` that excludes the records in the `_added` array.
=> MONGOID-5844 Fix counting bug in HABTM associations (backport to 8.1)

lib/mongoid/association/referenced/has_many/enumerable.rb, spec/mongoid/association/referenced/has_and_belongs_to_many/proxy_spec.rb
(backport to 8.0)
In certain situations, calling #size on a HABTM association will return the wrong count.
This will happen if the association is
initialized to a single element (forcing the _unloaded Criteria object to be scoped to that specific element) and then assigning an array of multiple (already-persisted) elements to the association, where one of the elements is the same element that already existed there.
In this case, `_unloaded.count` will return 1, and then the _added array will have two previously-persisted records. Naive implementations will thus return either 1, or 3, rather than the correct answer of 2. To get the correct answer, it is necessary to add a filter condition to `_unloaded.count` that excludes the records in the `_added` array.
=> MONGOID-5844 Fix counting bug in HABTM associations (backport to 8.0)

gemfiles/rails-6.1.gemfile, lib/mongoid/version.rb, spec/integration/app_spec.rb, spec/support/models/book.rb, spec/support/models/cover.rb
Mongoid 8.0.10 is a patch release that includes the following bug fix:
* MONGOID-5844: querying the number of elements in a `has_and_belongs_to_many` association could return the wrong count in specific situations.
=> Prep 8.0.10

gemfiles/rails-6.1.gemfile, lib/mongoid/version.rb, spec/integration/app_spec.rb
Mongoid 8.1.10 is a patch release that includes the following bug fix:
* MONGOID-5844: querying the number of elements in a `has_and_belongs_to_many` association could return the wrong count in specific situations.
=> Prep 8.1.10

gemfiles/rails-6.1.gemfile, lib/mongoid/version.rb, spec/integration/app_spec.rb
Mongoid 9.0.6 is a patch release that includes the following bug fix:
* MONGOID-5844: querying the number of elements in a `has_and_belongs_to_many` association could return the wrong count in specific situations.
=> Prep 9.0.6

lib/mongoid/loadable.rb, lib/mongoid/matcher/eq_impl.rb, upload-api-docs
https://jira.mongodb.org/browse/DOCSP-48435
Fixes a few broken links in the API docs
=> DOCSP-48435: 404-ing links

lib/mongoid/config.rb, lib/mongoid/indexable.rb, lib/mongoid/indexable/specification.rb, spec/mongoid/indexable_spec.rb
This adds a new feature flag (`allow_duplicate_index_declarations`) which defaults to false, which is the legacy behavior. When false, superficially-duplicate indexes are silently ignored. When true, all index declarations are passed through to the server, where duplicates will trigger a server-side error.
The primary drawback of the default (legacy) behavior is that index names (and options generally) are not considered when comparing index specifications. This means that an index that is seemingly identical to another, differing only in its options, will be silently ignored, even if an explicit name is given to it.
We opted, as a team, to move toward letting the server decide which indexes are duplicates, and which are not, but as this change has the potential to break …
=> MONGOID-5827 Allow duplicate indexes to be declared

lib/mongoid/config.rb, lib/mongoid/indexable.rb, lib/mongoid/indexable/specification.rb, spec/mongoid/indexable_spec.rb
(backport to 9.0-stable)
This adds a new feature flag (`allow_duplicate_index_declarations`) which defaults to false, which is the legacy behavior. When false, superficially-duplicate indexes are silently ignored. When true, all index declarations are passed through to the server, where duplicates will trigger a server-side error.
=> MONGOID-5827 Allow duplicate indexes to be declared (backport to 9.0)

spec/support/expectations.rb
The #expect_query test helper is basically broken on Ruby 3.3+. I'm not sure how CI tests are even passing with it in its current form... probably Mongoid is not running Ruby 3.3 / Ruby 3.4 tests properly.
I encountered this while testing older Mongoid versions--7.5, 8.0, etc.--on Ruby 3.3/3.4. Several tests which call this helper deterministically fail. To reproduce, you can check out [this commit](https://github.com/tablecheck/mongoid-ultra/commit/d29325f33c2238ae4107d0905484dee44f916db1), then run the tests for `Mongoid::Association::Referenced::BelongsTo::Eager`.
It appears the reason it broke it due to Ruby 3.3's "Object Shapes" changes which affected how method interception used by RSpec's .and_call_original works, creating an infinite loop of interception.
=> MONGOID-5872 - [🛠️ Let's Fix Mongoid's Broken CI] Fix #expect_query test helper for Ruby 3.3+

.rubocop.yml, lib/mongoid/association/embedded/embeds_one/proxy.rb, spec/integration/associations/embeds_one_spec.rb
=> MONGOID-5874 Fix persisting embedded children (#5988)

.github/workflows/test.yml, lib/mongoid/contextual/mongo.rb, spec/mongoid/contextual/mongo_spec.rb
This is a backport of #5975, fixing a regression that caused calls to `#last` to override any `#skip` that had been specified.
=> MONGOID-5863 last overrides skip (backport to 9.0)

.rubocop.yml, lib/mongoid/association/embedded/batchable.rb, lib/mongoid/association/embedded/embeds_many/proxy.rb, lib/mongoid/association/referenced/has_many/proxy.rb, spec/integration/associations/embeds_many_spec.rb
When associating multiple embedded documents in a single assignment, the existing code was inefficiently looping over all records repeatedly, resulting in a significant performance impact. This PR attempts to minimize the number of loops needed to accomplish the same thing, while keeping the ordering of callbacks the same and otherwise attempting to not break backward compatibility.
To test the performance of this PR, the following benchmark (from MONGOID-4889) was used:
```ruby
class Foo
embeds_many :bars
end
class Bar
embedded_in :foo
end
require 'benchmark'
array_1k = Array.new(1000) { Bar.new }
array_2k = Array.new(2000) { Bar.new }
array_3k = Array.new(3000) { Bar.new }
array_4k = Array.new(4000) { Bar.new }
array_5k = …
```
=> MONGOID-4889 Optimize batch assignment of embedded documents

.github/workflows/release.yml, Rakefile, lib/mongoid/version.rb, product.yml
This PR backports the release process updates from master to the 8.1 branch, preparing us to be able to release a new patch release from 8.1-stable.
=> Release process updates for 8.1-stable

lib/mongoid/version.rb, product.yml
The MongoDB Ruby team is pleased to announce version 8.0.11 of the `mongoid` gem - a Ruby ODM for MongoDB. This is a new patch release in the 8.0.x series of Mongoid.
Install this release using [RubyGems](https://rubygems.org/) via the command line as follows: 
~~~
gem install -v 8.0.11 mongoid
~~~
Or simply add it to your `Gemfile`:
~~~
gem 'mongoid', '8.0.11'
~~~
Have any feedback? Click on through to MongoDB's JIRA and [open a new ticket](https://jira.mongodb.org/projects/MONGOID) to let us know what's on your mind 🧠.
MONGOID-5822 attempted to fix a regression where child callbacks that depended on parent state were no longer invoked if the child had not changed. However, the fix itself introduced an unacceptable performance regression.
This PR restores the earlier functionality, which …
=> Release candidate for 8.0.11

lib/mongoid/association/embedded/batchable.rb, lib/mongoid/association/embedded/embeds_many/proxy.rb, spec/integration/associations/embeds_many_spec.rb
_(Backported to 8.1-stable)_
When associating multiple embedded documents in a single assignment, the existing code was inefficiently looping over all records repeatedly, resulting in a significant performance impact. This PR attempts to minimize the number of loops needed to accomplish the same thing, while keeping the ordering of callbacks the same and otherwise attempting to not break backward compatibility.
To test the performance of this PR, the following benchmark (from MONGOID-4889) was used:
```ruby
class Foo
embeds_many :bars
end
class Bar
embedded_in :foo
end
require 'benchmark'
array_1k = Array.new(1000) { Bar.new }
array_2k = Array.new(2000) { Bar.new }
array_3k = Array.new(3000) { Bar.new }
array_4k = Array.new(4000) { …
```
=> MONGOID-4889 Optimize batch assignment of embedded documents (backport to 8.1)

lib/mongoid/clients/sessions.rb, spec/mongoid/clients/transactions_spec.rb, spec/mongoid/clients/transactions_spec_models.rb
This is the backport of MONGOID-5852.
=> MONGOID-5852 Fix after_action_commit callbacks (#5968)

gemfiles/rails-6.0.gemfile, gemfiles/rails-6.1.gemfile, gemfiles/rails-7.0.gemfile, gemfiles/rails-7.1.gemfile, gemfiles/rails-7.2.gemfile, gemfiles/rails-8.0.gemfile, spec/integration/shardable_spec.rb, spec/mongoid/validatable/numericality_spec.rb
Fun fact: Mongoid's CI is not testing the following versions of Rails at all:
- 6.0.x
- 7.0.x
- 7.1.x
The reason is that `gem 'actionpack', '~> 6.0'` resolves to `6.Y.Z` where Y and Z are the highest possible version. To enforce it is actually testing `6.0.Z`, one must declare it as `~> 6.0.0`
In addition, Rails 8.0 is pinned at 8.0.0-rc2, i.e. not the latest 8.0.Z release.
Please kindly backport this to any branches under stable maintenance to ensure that future patches to those branches also have proper test coverage.
=> MONGOID-5872 - [🛠️ Let's Fix Mongoid's Broken CI] Actually test Rails 6.0.0, 7.0.0, 7.1.0, and released version of 8.0.0

lib/mongoid/reloadable.rb, spec/mongoid/reloadable_spec.rb
=> MONGOID-5895 Make Reload Properly Update new_record

lib/mongoid/contextual/aggregable/mongo.rb, spec/mongoid/contextual/aggregable/mongo_spec.rb
=> MONGOID-5887 Include server hint for aggregate operations

.github/workflows/release.yml
The MongoDB Ruby team is pleased to announce version 9.0.8 of the `mongoid` gem - a Ruby ODM for MongoDB. This is a new patch release in the 9.0.x series of Mongoid.
Install this release using [RubyGems](https://rubygems.org/) via the command line as follows: 
~~~
gem install -v 9.0.8 mongoid
~~~
Or simply add it to your `Gemfile`:
~~~
gem 'mongoid', '9.0.8'
~~~
Have any feedback? Click on through to MongoDB's JIRA and [open a new ticket](https://jira.mongodb.org/projects/MONGOID) to let us know what's on your mind 🧠.
* [MONGOID-5852](https://jira.mongodb.org/browse/MONGOID-5852) Fix after_action_commit callbacks ([PR](https://github.com/mongodb/mongoid/pull/5969))
* [MONGOID-4889](https://jira.mongodb.org/browse/MONGOID-4889) Optimize batch assignment of embedded documents …
=> Tweaks for 9.0.8 deployment

lib/mongoid/attributes.rb, spec/mongoid/attributes_spec.rb
With the `map_big_decimal_to_decimal128` option enabled, Mongoid will translate between `BSON::Decimal128` and `BigDecimal` when records are loaded and saved. However, if you assign an identical floating point value to the field, it will mark the record as changed, even though it (functionally) did not. This is because `BSON::Decimal128` is not an actual numeric type, and equality comparisons with numeric types will return false.
This PR fixes the dirty tracking with regard to `BigDecimal` and `BSON::Decimal128` by adding a normalization step to the comparison and handling the `Decimal128` type specially.
=> MONGOID-5890 Handle BSON::Decimal128 specially when checking for changes
